datarobot/datarobot-user-models

jenkins/test3_drop_in_envs.sh
tests/functional/tmp_training_fixtures.py

[RAPTOR-2994] Fix functional tests after API update

---

jenkins/test3_drop_in_envs.sh

[RAPTOR-2994] uncomment tests

---

custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/resource/components/Python/python_fit/python_fit.py
tests/drum/test_custom_model.py

* Default to full row amount so as not to confuse people
* Randomly sampling from CSV rows for when people choose to use a subset
* Improve Ctrl-C Behavior
* Improve messages
* Fix error if target column is non-existent.

[RAPTOR-3025] Alpha Testing Feedback

---

tests/functional/tmp_training_fixtures.py

Fix type change in CustomTrainingBlueprint

---

custom_model_runner/datarobot_drum/drum/model_adapter.py
model_templates/inference/python3_keras_vizai_joblib/README.md
model_templates/inference/python3_keras_vizai_joblib/artifact.joblib
model_templates/inference/python3_keras_vizai_joblib/custom.py
model_templates/inference/python3_keras_vizai_joblib/model_utils.py
model_templates/training/python3_keras_vizai_joblib/README.md
model_templates/training/python3_keras_vizai_joblib/custom.py
model_templates/training/python3_keras_vizai_joblib/model_utils.py
model_templates/training/python3_keras_vizai_joblib/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5
tests/functional/conftest.py
tests/functional/test_inference_model_templates.py
tests/functional/test_training_model_templates.py
tests/testdata/cats_dogs_small_training.csv

This PR reintroduces VizAI with image featurizer capability for binary classification purpose only (regression not supported in this PR)
(Actually this PR is PR# https://github.com/datarobot/datarobot-user-models/pull/50 + git-lfs + lrs mem increase PR# https://github.com/datarobot/jenkins-jobs/pull/7036 )
Keras vizai PR

[RAPTOR-3022] Keras VizAI model template reintroduced

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/__init__.py
custom_model_runner/datarobot_drum/drum/custom_fit_wrapper.py
custom_model_runner/datarobot_drum/drum/model_adapter.py
model_templates/training/python3_sklearn/create_pipeline.py
model_templates/training/simple/my_first_pipeline.py
tests/drum/test_custom_model.py

Zach wants the simplest possible setup for demos. 
Created a weird function thing which will modify an object on import so that it is detectable by drum.

[MODEL-4201] New Simple Custom Training Models Hook And Test

---

README.md
custom_model_runner/README.md
model_templates/inference/python3_pmml/README.md

More notes about providing positive/negative-class-label params

[DOC-2145] update docs

---

custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/resource/components/Python/r_predictor/r_predictor.py

[RAPTOR-2091] Raise exceptions instead of exiting program so that DrumRuntime can do post-processing

---

jenkins/test3_drop_in_envs.sh
requirements_dev.txt
requirements_test.txt

[RAPTOR-3153] install requirements file from the jarvis triggered script

---

custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/datarobot_drum/drum/runtime.py

[RAPTOR-2902] Log exceptions caught by DrumRuntime

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/model_adapter.py
tests/drum/test_custom_model.py

Sometimes users like messing up in this way, so instead of failing, we'll let them mess up and adapt.

[RAPTOR-3132] custom.py files can be found in nested directories

---

custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py

Some clean up after the prev patch

[RAPTOR-3220] refactoring: clean up after prev patch

---

tests/functional/test_training_model_templates.py

Add regression and classification functional tests for R fit custom models
Leftover from previous PR adding R fit template/functionality

R training functional tests

---

custom_model_runner/datarobot_drum/drum/runtime.py

[RAPTOR-3084] Remove todo and add comment

---

custom_model_runner/CHANGELOG.md
custom_model_runner/README.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/requirements.txt
requirements.txt
tests/drum/test_custom_model.py

Users can use this so that they don't need to figure out the python virtualenv stuff if they don't want to.

[RAPTOR-3238] Allow docker flag to take a directory

---

docker/java_dropin_env_base/Dockerfile

Install packages required for H2O models.

[RAPTOR-3248] update java base container for H2O model

---

MODEL-METADATA.md
README.md
custom_model_runner/CHANGELOG.md
custom_model_runner/README.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/push.py
model_templates/inference/python3_sklearn/model-metadata.yaml
model_templates/training/python3_sklearn/model-metadata.yaml
tests/drum/test_units.py

When I pushed out the code I didn't write docs. This also fixes some bugs.

Documentation for Drum Push

---

custom_model_runner/datarobot_drum/drum/drum.py

When i provide dir as relative path with `..` , docker image get() method treats it as REST endpoint.
So first check if provided parameter is a directory, and work with dir; otherwise try to fetch image with provided name.

[RAPTOR-3258] small fixes for --docker param

---

custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/push.py
custom_model_runner/datarobot_drum/drum/runtime.py
model_templates/inference/python3_sklearn/model-metadata.yaml
model_templates/training/python3_sklearn/model-metadata.yaml
public_dropin_environments/python3_sklearn/requirements.txt
tests/drum/test_units.py

[RAPTOR-3237] Adding validation to drum push

---

custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/drum/utils.py
custom_model_runner/requirements.txt
model_templates/training/python3_sklearn/README.md
tests/fixtures/cmrun_docker_env/drum_requirements.txt

* Enhanced some user facing communication
* Show user logs when verbose is not specified
* Memory profiling

[RAPTOR-3246] changes for feedback from Jake Snyder

---

model_templates/training/python3_pytorch/README.md
model_templates/training/python3_pytorch/custom.py
model_templates/training/python3_pytorch/model_utils.py
public_dropin_environments/python3_pytorch/fit.sh
tests/drum/test_custom_model.py

Vanilla regression/classification template...I can add some preprocessing and/or a vizAI version as with the keras templates.

[RAPTOR-3292] Pytorch template

---

public_dropin_environments/python3_pytorch/env_info.json

[RAPTOR-3292] update pytorch env version id

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
dev_env/java_nginx_env/dr_requirements.txt
dev_env/python3_nginx_env/dr_requirements.txt
dev_env/rlang_nginx_env/dr_requirements.txt
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_h2o/dr_requirements.txt
public_dropin_environments/java_h2o/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/requirements.txt
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

This is a placeholder for releasing drum v1.2.0.
Once tests pass, I change version to 1.2.0, publish drum and switch envs to use this version.
Also waiting for @jlpolit 's PRs to be merged.

release drum v1.2.0 and update environments

---

README.md

Sometimes uses miss that repo requires git-lfs

Update repo readme with git-lfs instructions

---

custom_model_runner/datarobot_drum/drum/artifact_predictors/keras_predictor.py
model_templates/inference/python3_keras_vizai_joblib/artifact.joblib
model_templates/inference/python3_keras_vizai_joblib/model_utils.py
model_templates/training/python3_keras_vizai_joblib/model_utils.py
model_templates/training/python3_keras_vizai_joblib/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5

This PR is to replace the heavy VGG16 with light weight MobileNet v2 for better performance.

[RAPTOR-3435] replace heavier VGG16 with lightweight MobileNet net

---

README.md
custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
dev_env/java_nginx_env/dr_requirements.txt
dev_env/java_nginx_env/env_info.json
dev_env/python3_nginx_env/dr_requirements.txt
dev_env/python3_nginx_env/env_info.json
dev_env/rlang_nginx_env/dr_requirements.txt
dev_env/rlang_nginx_env/env_info.json
model_templates/inference/r_lang/custom.R
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_h2o/dr_requirements.txt
public_dropin_environments/java_h2o/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
tests/fixtures/custom.R
tests/fixtures/load_model_custom.R

It is recommended to keep default missing value replacement in R data frames, which is replacing with NA.
This required to fix our inference model.
Updated docs.

[RAPTOR-2697] fix handling missing values in R

---

model_templates/training/python3_pytorch/model_utils.py
public_dropin_environments/python3_keras/fit.sh
public_dropin_environments/python3_pmml/fit.sh
public_dropin_environments/python3_pytorch/fit.sh
public_dropin_environments/python3_xgboost/fit.sh
public_dropin_environments/r_lang/fit.sh

Updating the fit.sh files for all python and r envs to be able to run unsupervised variant of drum fit command

Update fit for unsupervised

---

custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/push.py
model_templates/training/python3_sklearn/model-metadata.yaml
tests/conftest.py
tests/functional/test_drum_push.py

Drum push didn't have a bunch of stuff in its runtime (unsupervised, as well as a few monitoring fields). This handles those, and puts in a functional test to avoid breaking drum push by accident in the future.
Note- I moved the drum conftest up a level to use those fixtures....don't hesitate to tell me that was stupid

[RAPTOR-3496] fix drum push

---

custom_model_runner/datarobot_drum/drum/drum.py
tests/drum/test_drum_runtime.py
tests/drum/test_drum_server_failures.py
tests/drum/test_fit_inference.py
tests/drum/test_mlops_monitoring.py
tests/drum/test_other_cases.py
tests/drum/test_performance_check.py
tests/drum/test_units.py
tests/drum/test_unstructured_mode.py
tests/drum/test_validation_check.py

[RAPTOR-3506] refactoring tests - a bit of pylint

---

custom_model_runner/datarobot_drum/drum/artifact_predictors/keras_predictor.py
custom_model_runner/datarobot_drum/drum/model_adapter.py

Add a check for keras model is instance of keras included into tensorflow.

[RAPTOR-3643] import keras from TF in drum keras predictor

---

custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/utils.py
custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
model_templates/training/r_lang/create_pipeline.R
model_templates/training/r_lang/custom.R
tests/drum/test_fit.py
tests/drum/test_fit_variety.py

Moving all of the data handling from python into R for the r_fit functionality in DRUM.

[RAPTOR-3644] Move R fit data handling into R language

---

tests/drum/test_fit.py

fix failing r test

---

custom_model_runner/README.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/requirements.txt

Show error if uwsgi is not available in production mode, which is the case on Windows machines.
Tested manually

[RAPTOR-3554] show error if uwsgi is not available in production mode

---

tests/testdata/variety_samples/DR_Demo_AML_Alert_sample.csv
tests/testdata/variety_samples/DR_Demo_AWS_Job_Optimization_sample.csv
tests/testdata/variety_samples/DR_Demo_Banking_CustomerChurn_sample.csv
tests/testdata/variety_samples/DR_Demo_Car_Insurance_Fraud_sample.csv
tests/testdata/variety_samples/DR_Demo_Employee_Attrition_sample.csv
tests/testdata/variety_samples/DR_Demo_Fire_Ins_Claims_sample.csv
tests/testdata/variety_samples/DR_Demo_Fire_Ins_Loss_only_sample.csv
tests/testdata/variety_samples/DR_Demo_HumanResources_Hiring_GenderCleaned_sample.csv
tests/testdata/variety_samples/DR_Demo_HumanResources_Hiring_GenderRemoved_sample.csv
tests/testdata/variety_samples/DR_Demo_HumanResources_Hiring_sample.csv
tests/testdata/variety_samples/DR_Demo_HumanResources_Hiring_target_Gender_sample.csv
tests/testdata/variety_samples/DR_Demo_InsuranceExposure_sample.csv
tests/testdata/variety_samples/DR_Demo_LendingClub_Guardrails_sample.csv
tests/testdata/variety_samples/DR_Demo_LifetimeCustomerValue_sample.csv
tests/testdata/variety_samples/DR_Demo_Listing_Interest_sample.csv
tests/testdata/variety_samples/DR_Demo_LossGivenDefault_sample.csv
tests/testdata/variety_samples/DR_Demo_Medical_Fraud_sample.csv
tests/testdata/variety_samples/DR_Demo_NBA_2017-2018_sample.csv
tests/testdata/variety_samples/DR_Demo_Next_Best_Action_sample.csv
tests/testdata/variety_samples/DR_Demo_Offer_Layaway_sample.csv
tests/testdata/variety_samples/DR_Demo_Pred_Main_Bin_sample.csv
tests/testdata/variety_samples/DR_Demo_Pred_Main_Reg_sample.csv
tests/testdata/variety_samples/DR_Demo_SCMS_sample.csv
tests/testdata/variety_samples/DR_Demo_Telco_Next_Best_Offer_Multiclass_sample.csv
tests/testdata/variety_samples/DR_Demo_Telecomms_Churn_sample.csv
tests/testdata/variety_samples/DR_Demo_Temporal_Nature_Of_Claims_sample.csv
tests/testdata/variety_samples/DR_Demo_Who_is_a_promoter_sample.csv
tests/testdata/variety_samples/DR_Demo_credit_card_default_sample.csv
tests/testdata/variety_samples/DR_Demo_cross_sell_sample.csv
tests/testdata/variety_samples/Lending_Club_sample.csv

Going to remove all the "variety" samples from the repo for now, and add things back as I'm sure they're cleared (by cross-referencing [here](https://datarobot.atlassian.net/wiki/spaces/CFDS/pages/1525809555/Redistributable+Datasets))
I'll continue to work on making fixes that the related test surfaced on my local machine- I can share the data and/or code to reproduce it if others are interested as well

remove potentially sensitive data

---

DRCODEOWNERS

getting us set up to get proper notifications for needs review

[YOLO] add codeowners file

---

CODEOWNERS

the empty codeowners seems to be confusing the bot

[YOLO] remove bad codeowners

---

dev_env/rlang_nginx_env/start_server.sh
public_dropin_environments/r_lang/start_server.sh

R nginx started to fail with OOM
Switch to Flask

Switch R envs to flask because of OOM

---

dev_env/python3_nginx_env/requirements.txt
dev_env/rlang_nginx_env/dr_requirements.txt
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/dr_requirements.txt
requirements.txt

I wanted to update rpy2, but it didn't work well with older pandas.
Also unify pandas versions across the repo.

Update deps: pandas==1.1.0, rpy2==3.3.6

---

model_templates/inference/python3_unstructured/README.md
model_templates/inference/python3_unstructured/custom.py
model_templates/inference/r_unstructured/README.md
model_templates/inference/r_unstructured/custom.R

Added model templates for unstructured models

[RAPTOR-3574] model templates for unstructured

---

custom_model_runner/datarobot_drum/drum/args_parser.py

[RAPTOR-3554] hide 'pip show uwsgi' output

---

custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
tests/drum/test_fit.py

[RAPTOR-3769] find nested custom files for R fit

---

README.md
custom_model_runner/CHANGELOG.md
custom_model_runner/README.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_h2o/dr_requirements.txt
public_dropin_environments/java_h2o/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Release drum v1.4.0

---

README.md

Fixing the README has been overwritten by another PR>

Fix readme, release v1.4.0

---

model_templates/inference/python3_pytorch_multiclass/README.md
model_templates/inference/python3_pytorch_multiclass/artifact.pth
model_templates/inference/python3_pytorch_multiclass/class_labels.txt
model_templates/inference/python3_pytorch_multiclass/custom.py
model_templates/inference/python3_pytorch_multiclass/expected_columns.pkl
model_templates/inference/python3_pytorch_multiclass/model_utils.py
model_templates/inference/python3_pytorch_multiclass/preprocessing.py
model_templates/inference/python3_pytorch_multiclass/preprocessor.pkl
model_templates/inference/python3_pytorch_multiclass/requirements.txt
model_templates/training/python3_pytorch_multiclass/README.md
model_templates/training/python3_pytorch_multiclass/custom.py
model_templates/training/python3_pytorch_multiclass/model_utils.py
model_templates/training/python3_pytorch_multiclass/preprocessing.py
model_templates/training/python3_pytorch_multiclass/requirements.txt
tests/functional/conftest.py
tests/functional/test_inference_model_templates.py
tests/functional/test_training_model_templates.py

Adding multiclass examples with requirements and multiple model artifacts

[RAPTOR-3835] Add more realistic multiclass examples

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/start_server.sh
public_dropin_environments/java_h2o/dr_requirements.txt
public_dropin_environments/java_h2o/env_info.json
public_dropin_environments/java_h2o/start_server.sh
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/start_server.sh
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/start_server.sh
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/start_server.sh
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/start_server.sh
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/start_server.sh
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/start_server.sh

Prev PR has been automerged.
I'll make this one a release of 1.4.1

switch public envs from Flask to uwsgi

---

tests/functional/conftest.py
tests/functional/test_inference_model_templates.py

Add functional test for unstructured model

---

custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/custom/H2OPredictorPipeline.scala

DRUM currently supports H2O DAI Mojo Pipelines, but is leveraging DAI internals with respect to binary and multiclass problem target labels.   For binary and multiclass problems DAI prepends the target column name to the class label.  The H2OPredictorPipeline class has been updated to leverage the arguments passed to drum via `--positive-class-label` and `--negative-class-label` for binary and `--class-label-file` or `--class-labels` for multiclass problems.  
This has not been incorporated into automatic testing

[RAPTOR-3887] Fix Target Labels DAI Mojo Pipeline

---

custom_model_runner/datarobot_drum/drum/push.py
jenkins/test3_drop_in_envs.sh
tests/functional/test_drum_push.py

[RAPTOR-3813] test for unsupervised drum push

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
custom_model_runner/requirements.txt
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Two major changes:
* Catch user's exceptions that might occur during predictions, log them and return a proper response
* Pump up mlpiper version dependency to mlpiper v2.4.0
**Note:** the tests for this PR will not pass until the `mlpiper v2.4.0` will be pushed to DataRobot artifactory

[RAPTOR-3866] Catch exception from user's code, log it and return proper response

---

model_templates/training/python3_calibrated_anomaly_detection/custom.py

get rid of y in fit function of calibrated anomaly template

---

README.md
model_templates/inference/python3_sklearn_anomaly/README.md
model_templates/inference/python3_sklearn_anomaly/anomaly_helpers.py
model_templates/inference/python3_sklearn_anomaly/build_pipeline.py
model_templates/inference/python3_sklearn_anomaly/sklearn_anomaly.pkl

[RAPTOR-3899] add anomaly inference template

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
jenkins/test3_drop_in_envs.sh
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
tests/functional/test_inference_model_templates.py

A placeholder for 1.4.3 release after arrow support was fix on DR side.
We'd like to release 1.4.3 to pin version in the tests on DR side.
Before merging:
- change version to 1.4.3
- update env version ids

release v1.4.3

---

custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/push.py
custom_model_runner/setup.py
requirements_test.txt
tests/conftest.py
tests/drum/utils.py
tests/functional/conftest.py
tests/functional/test_drum_push.py

[YOLO] Fix drum push

---

public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

[RAPTOR-4033] update envs with drum 1.4.4, release 1.4.4

---

custom_model_runner/datarobot_drum/drum/push.py
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/start_server.sh
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/start_server.sh
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/start_server.sh
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/start_server.sh
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/start_server.sh
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/start_server.sh
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/start_server.sh
tests/fixtures/cmrun_docker_env/start_server.sh

* Improved error messaging in push
* Don't override pythonpath in start_server.sh

[YOLO] Don't override pythonpath

---

jenkins/test3_inference_model_templates.sh
jenkins/test3_training_model_templates.sh

[RAPTOR-4182] split functional tests into several jobs

---

custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Add monitoring to R and Java predictors.
Tested manually.

[RAPTOR-4106] add monitoring to R and Java predictors

---

custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/resource/utils.py
tests/drum/test_performance_check.py

fix perf-test for multiclass:
- class labels were not passed into the command
- add test cases

[RAPTOR-3982] fix perf-test for multiclass

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/utils.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
tests/drum/test_utils.py

Fix a bug with numeric class labels containing 0 for binary classification not correctly creating a class order list.

[RAPTOR-4164] fix binary num class order

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/artifact_predictors/artifact_predictor.py
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/drum/perf_testing.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
requirements.txt
tests/drum/test_args_parser.py

class labels should always be compared as `not None` and strings

[RAPTOR-4199] force class labels to be strings

---

model_templates/inference/h2o_mojo/README.md
model_templates/inference/h2o_mojo_pipeline/README.md
model_templates/inference/h2o_pojo/README.md

The labels in the readme is wrong, which will cause errors during scoring if used

[RAPTOR-4239] fix class labels in readmes

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/push.py
tests/drum/test_units.py

Update drum push to correctly handle multiclass.  I did not update the version of datarobot in requirements since this the version needed is as of yet unreleased

[RAPTOR-4161] fix drum push for multiclass

---

public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

update to 1.4.11

---

custom_model_runner/CHANGELOG.md
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

release 1.4.12

---

custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/custom/BasePredictor.java

Need this to build Predictors outside of this source code.

[YOLO] make BasePredictor class public

---

custom_model_runner/datarobot_drum/drum/drum.py

Add a better error message for the case when multiple custom.py/R files are present in subdirectories.  The current message does not make it clear why the model failed to run correctly.

[RAPTOR-4243] Update error messages 

---

custom_model_runner/requirements.txt
jenkins/test3_drop_in_envs.sh
jenkins/test3_inference_model_templates.sh
jenkins/test3_training_model_templates.sh

quantum can't install latest version of pyarrow and we should pin dependencies anyway

[RAPTOR-4521] drum not being installed during tests

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/env_info.json

adds the sagemaker extension used in the multiclass pytorch example model to the pytoch dropin environment.

[RAPTOR-4601] update environment for pytorch

---

tests/functional/test_training_model_templates.py

comment out test

---

.gitignore
custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
tests/drum/test_performance_check.py
tests/drum/test_unstructured_mode.py

* return proper response if user tries to requiest /predict/ endpoint in unstructured mode; or /predictUnstructured endpoint in structured mode
* fix perf-test table formatting
* 
release v1.5.0
This PR will go after https://github.com/datarobot/datarobot-user-models/pull/293

[RAPTOR-4790,4791] bug fixes, release v1.5.0

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Release 1.5.2

---

public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_pmml/requirements.txt
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/requirements.txt
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/dr_requirements.txt

A memory leak is present in pandas to_json() call for Series (columns) and its hard to work this around in code with some current versions of pandas.
In order to work this around before any fix is out, we can use a bit lower version of pandas which is not too old and not leaking.
Likely related pandas issue here: 
https://github.com/pandas-dev/pandas/issues/24889
A container running sklearn model based on environment with 2 different versions of pandas:
Before (1.1.0):
After (1.0.5):
Performance check to make sure we dont downgrade:
Before (1.1.0):
```
size    samples   iters    min     avg     max    used (MB)   total physical (MB)
=================================================================================
64 KB      1000    1000   0.011   0.015   0.081     135.781 …
```

[RAPTOR-4976] Downgrade pandas version to workaround pandas to_json() memory leak

---

requirements.txt
tests/fixtures/cmrun_docker_env/requirements.txt

Downgrade pandas version to workaround pandas to_json() memory leak - drop 2

---

custom_model_runner/datarobot_drum/drum/push.py
tests/drum/test_units.py
tests/functional/test_training_model_templates.py

Updates the user blueprint add-to-menu route to a non-experimental route.

[RAPTOR-5806] Update user blueprint add to menu route

---

README.md
custom_model_runner/CHANGELOG.md
custom_model_runner/README.md
custom_model_runner/drum_server_api.yaml
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

[RAPTOR-5017,5019] fix documentation on the API endpoints, release v1.5.3

---

README.md
custom_model_runner/README.md

[RAPTOR-5017,5019] fix links in docs

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/requirements.txt
custom_model_runner/setup.py
requirements_test.txt
tests/fixtures/cmrun_docker_env/drum_requirements.txt

[YOLO] pin DR client version to 2.24.0

---

custom_model_runner/datarobot_drum/resource/drum_server_utils.py
docker/drum_integration_tests_base/Dockerfile
docker/drum_integration_tests_base/build_test_docker.sh
docker/drum_integration_tests_base/sysim.jl
requirements.txt
tests/fixtures/custom_pred_consistency/custom.py

* Update datarobot / drum_integration_tests_base container
* Add packages to support Julia language (@timsetsfire  implements Julia DRUM predictor)
* Fix a couple of bugs I encountered when running tests locally in the datarobot /drum_integration_tests_base
The docker image has already been updated on dockerhub. Tests in this PR, have been ran in the container, these changes implement.
https://hub.docker.com/repository/registry-1.docker.io/datarobot/drum_integration_tests_base/tags?page=1&ordering=last_updated

[RAPTOR-5197] update DRUM test container, add support for Julia

---

README.md

[YOLO] fix unstructured mode docs

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Bump to include --verbose stdout for score + predict. Will publish to pypi shortly after

[YOLO] Bump version to 1.5.5

---

MODEL-METADATA.md
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/typeschema_validation.py
custom_model_runner/requirements.txt
tests/drum/test_units.py
tests/fixtures/cmrun_docker_env/drum_requirements.txt

This adds the validators needed for the type schema definition, however does not run the validation tests.  That will be added in a future PR

[RAPTOR-5193] Validation system for type schema

---

custom_model_runner/datarobot_drum/drum/typeschema_validation.py
tests/drum/test_units.py

Add support for the contains_missing validation field.

[RAPTOR-5302] contains missing validation

---

custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
model_templates/training/python3_pytorch_multiclass/custom.py
model_templates/training/python3_xgboost/custom.py
tests/drum/test_drum_server_failures.py
tests/drum/test_units.py

Refactor some repeating calls  into a one function.

[YOLO] code clean up and optimization

---

custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml

update h2o dependencies to work with latest version of h2o

[RAPTOR-5317] update h2o dependencies in pom

---

VALIDATION-SCHEMA.md

Detailed documentation for schema validation.  Also a small fix to one of the validators

[RAPTOR-5286] Add detailed docs for validations schema

---

MODEL-METADATA.md
custom_model_runner/datarobot_drum/drum/common.py

[RAPTOR-5407] fix documentation to reflect all supported types.

---

public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/julia_mlj/dr_requirements.txt

We missed pinning pandas version in a couple of public envs

[YOLO] pin pandas version

---

custom_model_runner/datarobot_drum/drum/language_predictors/julia_predictor/score.jl

a small bug was present in the score.jl language predictor.  If a MLJ artificat was provided with custom.jl file which defined load_hook and no score hook, then necessary libraries to complete scoring would not be loaded.

[Yolo] bug fix in score.jl

---

docker/java_dropin_env_base/Dockerfile

Define JAVA_HOME in the image intended to be Java source of truth

[YOLO] define JAVA_PATH env var in the java base image

---

custom_model_runner/datarobot_drum/resource/drum_server_utils.py
requirements_test.txt
tests/drum/run-drum-tests-in-container.sh
tests/drum/test_drum_server_failures.py
tests/drum/test_units.py
tests/drum/unit/test_typeschema_validation.py

Attempt to speed up integration tests using xdist
🏃

[YOLO] Try xdist out for test performance

---

custom_model_runner/CHANGELOG.md
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Bump the version to include all of the latest R and other bug fixes

[YOLO] Bump to version 1.5.7

---

custom_model_runner/datarobot_drum/drum/description.py

Forgot to update in this PR: https://github.com/datarobot/datarobot-user-models/pull/370

[YOLO] Update description for new version

---

custom_model_runner/datarobot_drum/drum/typeschema_validation.py
tests/drum/unit/test_typeschema_validation.py

Get the correct string representation from the elements of a list of enums.

[RAPTOR-5492]deal with ugly list representation in f-string

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

I forgot to update environments to 1.5.8, when released 1.5.8.
Since then there was another patch to DRUM, so just release a new version, in order not to create mess

Release v1.5.9

---

custom_model_runner/requirements.txt
requirements.txt
tests/fixtures/cmrun_docker_env/drum_requirements.txt

The old version of strictyaml caused issues when running drum in staging, due to comments in yamlfiles not working.

[RAPTOR-5867] Update StrictYaml

---

README.md
docker/drum_builder/build_docker.sh
jenkins/test3_drop_in_envs.sh
jenkins/test3_inference_model_templates.sh
jenkins/test3_training_model_templates.sh
tools/create-drum-dev-image.sh
tools/image-build-utils.sh

We needed a way to easily test new changes to DRUM inside of DataRobot, so I wrote a shellscript to do it. I refactored a bunch of currently existing jenkins jobs which already accomplished this idea to a separate library, and then used that library for my script.

[RAPTOR-5924] Add script to test images in DR, refactor of jenkins shellscripts

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Making new release for strictyaml bugfix.

[RAPTOR-5867] Release drum 1.5.10

---

custom_model_runner/datarobot_drum/drum/drum.py

This will help users tell how much mem is used from serving vs fit. Useful bc LRSes have max 2gb memory to use.

[RAPTOR-5789] Add server memory usage

---

VALIDATION-SCHEMA.md
task_templates/pipelines/python3_anomaly_detection/model-metadata.yaml
task_templates/pipelines/python3_calibrated_anomaly_detection/model-metadata.yaml
task_templates/pipelines/python3_keras_joblib/model-metadata.yaml
task_templates/pipelines/python3_keras_vizai_joblib/model-metadata.yaml
task_templates/pipelines/python3_pytorch/model-metadata.yaml
task_templates/pipelines/python3_pytorch_multiclass/model-metadata.yaml
task_templates/pipelines/python3_sklearn_binary/model-metadata.yaml
task_templates/pipelines/python3_sklearn_with_custom_classes/model-metadata.yaml
task_templates/pipelines/python3_sparse/model-metadata.yaml
task_templates/pipelines/python3_xgboost/model-metadata.yaml
tests/fixtures/python3_sklearn_binary_hyperparameters/model-metadata.yaml
tests/functional/test_custom_task_templates.py

Add appropriate type schemas for all task_template pipelines.  This will help make it obvious when data that can't work with the model is used and the model does not work.  Future PRs will add this for estimators and transforms.

[RAPTOR-5822] Add type schema for pipelines

---

MODEL-METADATA.md
VALIDATION-SCHEMA.md

Update documentation to reflect the default used for transforms, and utilize consistent language about tasks.

[RAPTOR-5866] update docs for schema validation

---

.ignore
custom_model_runner/datarobot_drum/drum/artifact_predictors/sklearn_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/drum/utils.py
pyproject.toml
tests/drum/test_data_marshalling.py
tests/drum/test_other_cases.py
tests/drum/test_units.py

In  https://github.com/datarobot/datarobot-user-models/pull/377 we started checking if values could be converted into floats, and sorting them by their float-equivalent values if they could. Here I use the same technique in python.

[RAPTOR-5739] Applying Jesse's technique to python

---

VALIDATION-SCHEMA.md
custom_model_runner/datarobot_drum/drum/typeschema_validation.py

Update instances of model to task in the documentation for schema validation, as well as in the messages used by the validation methods.

[YOLO] update wording from models to tasks

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
task_templates/pipelines/python3_keras_joblib/model-metadata.yaml

[RAPTOR-6035] Release DRUM v1.5.11

---

custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py

Tied to bug report https://datarobot.atlassian.net/browse/RAPTOR-5781
Transform hook can return either a tuple or a dataframe -> updated generic_predictor.py accordingly.

[RAPTOR-5781] update generic_predictor.py

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
tools/env_version_update.py

Tagging & releasing new version of DRUM to pypi, staging, and prod
Periodic update to ship latest versions

[RAPTOR-6355] Duncan/release commit 1.5.12

---

custom_model_runner/datarobot_drum/drum/typeschema_validation.py

Update a couple of the messages for users when schema validation fails.  This should make it more obvious what the issue is.

[RAPTOR-5872]update messages for users

---

custom_model_runner/CHANGELOG.md
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Release of DRUM version 1.5.14.

[YOLO] publish new drum version

---

model_templates/python3_pytorch/README.md
public_dropin_environments/python3_pytorch/requirements.txt
requirements.txt
tests/drum/test_drum_docker.py

currently used `torch==1.2.0` is super old and is not supported by Py3.8.
Trying to update to 1.6.0
Speak up if you are against and suggest version to update to.

[YOLO] update torch to 1.6.0

---

custom_model_runner/datarobot_drum/drum/data_marshalling.py
custom_model_runner/datarobot_drum/drum/model_adapter.py
tests/drum/test_data_marshalling.py

[RAPTOR-6106] Fast follow

---

custom_model_runner/CHANGELOG.md
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/env_info.json

**New release overview:**
- support for Java Unstructured Models (https://github.com/datarobot/datarobot-user-models/pull/472)
- Add new exit code (3) and improve schema validation exception handling (https://github.com/datarobot/datarobot-user-models/pull/478)
**What is next:**
Update the drop-in env in staging/prod (https://datarobot.atlassian.net/wiki/spaces/RAPTOR/pages/1416691967/Install+drop-in+environments+on+staging+production)

[RAPTOR-5500] New release 1.6.2

---

custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/r_lang/dr_requirements.txt

This is the follow-up pr of https://github.com/datarobot/datarobot-user-models/pull/481. This PR updates the version number of new release.

[RAPTOR-5500] Update new release version number

---

custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/resource/components/Python/python_fit/python_fit.py
custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
custom_model_runner/datarobot_drum/resource/pipelines/python_fit.json.j2
custom_model_runner/datarobot_drum/resource/pipelines/r_fit.json.j2
tests/conftest.py
tests/drum/constants.py
tests/drum/test_fit.py
tests/fixtures/custom_pred_consistency/custom.py
tests/fixtures/python_xform_estimator/custom.py
tests/fixtures/r_xform_estimator/custom.R

Make sure transform hook is called before fit for prediction tasks

Call transform hook before fit [RAPTOR-6103]

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

[RAPTOR-7318] Release v1.6.4

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Release 1.6.5

---

public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Backporting:
- update envs with DRUM v1.6.2.post1

Update envs with DRUM v1.6.2.post1

---

public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Update envs with DRUM v1.6.2.post2

---

custom_model_runner/requirements.txt

Forgot to update the requirements.txt here in my last PR https://github.com/datarobot/datarobot-user-models/pull/523

[MODEL-7540] Update cmrunner dr client

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Release v1.6.6

---

custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/enum.py
custom_model_runner/datarobot_drum/drum/model_metadata.py
custom_model_runner/datarobot_drum/drum/push.py
tests/drum/test_other_cases.py
tests/drum/test_units.py

In this PR, the validation on hyperparameter section of model metadata yaml is added.

[RAPTOR-7292] Add validation on custom task hyperparameters

---

task_templates/3_pipelines/15_python3_keras_vizai_joblib/custom.py
task_templates/3_pipelines/15_python3_keras_vizai_joblib/model-metadata.yaml
task_templates/3_pipelines/15_python3_keras_vizai_joblib/model_utils.py

This template was broken because it:
1) imported torch for no reason (which isn't in the dependencies list)
2) tried to download weights at fit time (which won't work because it's our docker container has no internet access) 
3) used an old version of MobileNet which is out of sync with core DataRobot (v2 vs. v3)
We need working templates, this came up because a CFDS tried to use this template and couldn't

[RAPTOR-7352] Fix keras vizai pipeline

---

DRCODEOWNERS

Update code owners so that core modeling is included as appropriate.  Also for files only related to custom tasks remove custom-models as a code owner.

[MODEL-7730] update codeowners

---

model_templates/README.md
model_templates/julia/README.md
model_templates/python3_pmml/README.md
model_templates/python3_sklearn_anomaly/README.md
model_templates/python3_xgboost/README.md

Just fixed some dead links in the READMEs throughout different levels in the repo. Thanks for the review!

Minor relational link fixes in a couple READMEs

---

README.md
custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Retroactively merge  back 1.6.7 

---

requirements_test.txt

[MODEL-7886] Fix failing functional tests by updating bp workshop

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

DRUM bump to 1.6.2.post6

---

public_dropin_environments/python3_pmml/Dockerfile
public_dropin_environments/python3_pmml/dr_requirements.txt

Pmml environment uses java environment as a base.
Forgot to update in the previous patch

[RAPTOR-7659] update pmml env image

---

DRCODEOWNERS
custom_model_runner/CHANGELOG.md
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Created this PR to get ready for the v1.8.0 release, whenever we want to bundle all desired changes.
Thanks in advance for the review.

Get ready for v1.8.0 release

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

[MODEL-8376] add 1.8.0 to version, update changelog

---

public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

[RAPTOR-7869] update envs with DRUM 1.9.0, prepare for install

---

custom_model_runner/CHANGELOG.md
custom_model_runner/README.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/drum/server.py
custom_model_runner/datarobot_drum/resource/drum_server_utils.py
custom_model_runner/requirements.txt
tests/drum/test_drum_server_failures.py

remove deprecated shutdown api

[RAPTOR-3909] drop 2: unpin werkzeug, release DRUM 1.9.2

---

public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

[RAPTOR-7939] release envs with DRUM 1.9.2

---

task_templates/2_estimators/3_r_sparse_regression/model-metadata.yaml

Updates the custom task template to have the same additional comments as all others, and correctly define missing value information

[MODEL-7545] update model metadata with additional info

---

public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/fit.sh
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_onnx/fit.sh
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/fit.sh
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/fit.sh
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/fit.sh
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/fit.sh

Add fit report generation to all fit.sh files in the dropin environments.  This will allow for more precise memory allocation when run within DataRobot.

[MODEL-9265] update fit.sh and the environments

---

custom_model_runner/setup.py

Update the license metadata for the python package to match the actual license of this repository.
The license metadata we publish to Pypi is not accurate.

Update setup.py license metadata

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

[RAPTOR-8155] release DRUM 1.9.4

---

model_templates/python_multiple_codegen/README.md
model_templates/python_multiple_codegen/custom.py

Add an inference model template example featuring multiple ScoringCode artifacts

[POC] Python orchestrator running multiple scoring code predictors

---

public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt
task_templates/2_estimators/11_python_huggingface_vit/custom.py
task_templates/2_estimators/11_python_huggingface_vit/requirements.txt

Some small optimizations and code cleanup for the ViT example.  Because this is a large model that is slower to run on CPU we need to use some tricks to make it faster in use.

[MODEL-9532] faster vit

---

public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/requirements.txt

[RAPTOR-8239] remove sagemaker sklearn extension from sklearn environment

---

model_templates/python_multi_codejen_reg_class/README.md
model_templates/python_multi_codejen_reg_class/custom.py
model_templates/python_multiple_codegen/custom.py

[POC] another multi codegen example with multiclass/binary + regression artifacts

---

custom_model_runner/CHANGELOG.md
public_dropin_environments/python3_pmml/Dockerfile
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/requirements.txt
requirements.txt

[RAPTOR-8213] update pypmml environment to Python 3.9

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/env_info.json

[RAPTOR-8244] provide Python version in the env's names

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
tests/drum/test_drum_docker.py

[MODEL-9698] bump version to 1.9.8

---

jenkins/test_integration_general.sh
requirements_test.txt

Though tests in my prev PR passed and it was merged., following PRs started to fail.
I can not figure out the exact reason. Probably this is due to packages cross dependency, so change that to what it was before tests splitting.

[RAPTOR-8303] fix tests, comments cleanup

---

custom_model_runner/CHANGELOG.md
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Release DRUM v1.9.11, update envs

[RAPTOR-8683] release DRUM v1.9.11, update envs

---

model_templates/flask_extension_httpauth/README.md
model_templates/flask_extension_httpauth/custom_flask.py
model_templates/flask_extension_httpauth/requirements.txt

Minor updates to new Flask extension model template.
Final documentation review before closing out the project.

[DOC-4789] Documentation README.md review.

---

custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/server.py
custom_model_runner/datarobot_drum/drum/templates_generator.py

Unused imports were found, this removes them.

[MODEL-10345] remove unused imports

---

task_templates/1_transforms/1_python_missing_values/custom.py
task_templates/1_transforms/3_python3_sklearn_transform/custom.py
task_templates/2_estimators/9_python_calibrator/custom.py

This implements suggestions that were missed in the refactor of custom tasks PR.

[MODEL-10337] missed pr suggestions

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Release DRUM 1.9.14.
Prepare environments for installation.

[RAPTOR-8938] release DRUM 1.9.14, update environments

---

example_dropin_environments/julia_mlj/dr_requirements.txt
example_dropin_environments/julia_mlj/env_info.json

Update drum in the Julia environment.
We removed Julia environment from the public environment, as we don't have anyone specialized in Julia, but the env is still available in the examples.
Older drum doesn't pin flask version, so there will be problems if someone decides to play with the env.

[RAPTOR-9013] update drum for Julia environment

---

requirements_test.txt
tests/functional/conftest.py

The recent `dr-usertool` uses API Keys to set up users.

[RAPTOR-9004] Upgrade dr-usertool to 1.0.0

---

custom_model_runner/CHANGELOG.md
custom_model_runner/requirements.txt
example_dropin_environments/julia_mlj/dr_requirements.txt
example_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
requirements_test.txt
tests/functional/test_drop_in_environments.py
tests/functional/test_inference_model_templates.py

[RAPTOR-9061] bump datarobot==3.0.2, release 1.10.0

---

custom_model_runner/datarobot_drum/custom_task_interfaces/estimator_interfaces.py
custom_task_tutorial.ipynb
task_templates/2_estimators/4_python_binary_classification/custom.py

This fixes a template and updates the docstring.
here's the template in action:
with a successful run
checked the code of following, and they all use predict_proba
```
$ git grep --name-only BinaryEstimatorInterfa
custom_model_runner/datarobot_drum/custom_task_interfaces/__init__.py
custom_model_runner/datarobot_drum/custom_task_interfaces/estimator_interfaces.py
custom_task_tutorial.ipynb
task_templates/2_estimators/11_python_huggingface_vit/custom.py
task_templates/2_estimators/4_python_binary_classification/custom.py
tests/fixtures/custom_task_interface_binary/custom.py
tests/fixtures/custom_task_interface_keras_visual/custom.py
tests/fixtures/custom_task_interface_pytorch_binary/custom.py
$ git grep --name-only MulticlassEstimatorInterface …
```

[MODEL-11370] fix templates

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Release a new version of drum with bugfix.

[MODEL-11423] bump version to 1.10.2

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/env_info.json

Update the version of DRUM to 1.10.3 to capture the most recent fixes and updates.

[MODEL-11519]bump version of drum

---

public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

The other environments were updated recently with the newest version of drum, however the R environment was missed.

[MODEL-11546] bump version of drum for R

---

requirements_test.txt
tests/functional/conftest.py

The latest dr-usertool requires users to be a part of an organization.

[RAPTOR-9417] Upgrade dr-usertool to v3

---

public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
public_dropin_notebook_environments/python38_snowflake_notebook/agent/requirements-agent.txt
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/extensions/dataframe_formatter.py
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/Dockerfile
public_dropin_notebook_environments/python39_notebook/agent/requirements-agent.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/extensions/dataframe_formatter.py
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/r_notebook/dr_requirements.txt
public_dropin_notebook_environments/r_notebook/env_info.json

A batch of fixes and improvements for the NBX drop-ins

[-] Upgrade NBX kernels

---

custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
task_templates/2_estimators/1_python_regression/custom.py
task_templates/2_estimators/1_python_regression/model-metadata.yaml
task_templates/2_estimators/4_python_binary_classification/custom.py
task_templates/2_estimators/4_python_binary_classification/model-metadata.yaml
task_templates/2_estimators/7_python_anomaly/custom.py
task_templates/2_estimators/7_python_anomaly/model-metadata.yaml
task_templates/README.md

Add hyperparameter examples where appropriate in custom tasks.

[MODEL-11706] simple hyperparam examples

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/data_marshalling.py
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/enum.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/r_lang/dr_requirements.txt
tests/drum/unit/test_data_marshalling.py

Supporting Text Generation targets

[RAPTOR-9519] release v1.10.7

---

custom_model_runner/CHANGELOG.md
docker/dropin_env_base/README.md
docker/dropin_env_base/build_image.sh
docker/dropin_env_base/requirements.txt
docker/dropin_env_base_jdk/README.md
docker/dropin_env_base_jdk/build_image.sh
docker/dropin_env_base_jdk/requirements.txt
docker/dropin_env_base_r/README.md
docker/dropin_env_base_r/build_image.sh
docker/dropin_env_base_r/requirements.txt
jenkins/test_integration_general.sh
model_templates/python3_onnx_multiclass/requirements.txt
model_templates/python3_pytorch_multiclass/requirements.txt
model_templates/python3_sklearn_runtime_params/requirements.txt
public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/Dockerfile
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/Dockerfile
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/Dockerfile
public_dropin_environments/r_lang/env_info.json

* update base docker images: drum==1.10.7, mlops==9.1.3
* use new base images in the envs

[RAPTOR-9530] update environments

---

public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt
tests/functional/conftest.py
tests/functional/test_inference_model_templates.py

Draft PR for revising torch drop-in env to include requirements for popular gen-ai powered apps/deployments

[RAPTOR-9604] update pytorch:  env reqs, desc for GenAI apps

---

public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/Dockerfile
public_dropin_notebook_environments/python39_notebook/env_info.json

[NB-3884] Fix openjdk version 

---

public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/r_notebook/Dockerfile
public_dropin_notebook_environments/r_notebook/env_info.json

[EPS-1199] update notebooks envs

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/requirements.txt
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311_genai/dr_requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python39_genai/dr_requirements.txt
public_dropin_environments/python39_genai/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

pin datarobot<4, release v1.10.10

[RAPTOR-9708] pin datarobot<4, release v1.10.10

---

public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/Dockerfile
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json

[NB-3234] fix notebook images

---

public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt

[MMM-14493] bump dmm library

---

public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt

https://pypi.org/project/datarobot-model-metrics/

[MMM-14465] bump dmm library to 0.2.5

---

model_templates/python3_dummy_regression/README.md
model_templates/python3_dummy_regression/custom.py

[RAPTOR-9739] Add regression dummy custom model

---

model_templates/python3_dummy_anomaly/README.md
model_templates/python3_dummy_anomaly/custom.py
model_templates/python3_dummy_binary/README.md
model_templates/python3_dummy_binary/custom.py
model_templates/python3_dummy_multiclass/README.md
model_templates/python3_dummy_multiclass/class_labels.txt
model_templates/python3_dummy_multiclass/custom.py
model_templates/python3_dummy_regression/README.md
model_templates/python3_dummy_textgen/README.md
model_templates/python3_dummy_textgen/custom.py
model_templates/python3_dummy_textgen/model-metadata.yaml
tests/testdata/simple_text.csv

Adds a bunch of other simple models.

[RAPTOR-9810] Add other problem type dummy models

---

public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt

https://pypi.org/project/datarobot-model-metrics/

[MMM-14688] bump dmm library to 0.2.6

---

public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt

[MMM-14853] bump dmm library to 0.2.7

---

example_dropin_environments/julia_mlj/start_server.sh
public_dropin_environments/java_codegen/start_server.sh
public_dropin_environments/python311_genai/start_server.sh
public_dropin_environments/python39_genai/start_server.sh
public_dropin_environments/python3_keras/start_server.sh
public_dropin_environments/python3_onnx/start_server.sh
public_dropin_environments/python3_pmml/start_server.sh
public_dropin_environments/python3_pytorch/start_server.sh
public_dropin_environments/python3_sklearn/start_server.sh
public_dropin_environments/python3_xgboost/start_server.sh
public_dropin_environments/r_lang/start_server.sh

Update shell script commands to cmply with shellcheck.
This PR is related to the: https://github.com/datarobot/DataRobot/pull/120398

[MODEL-11992] update start_server.sh to pass shellcheck

---

public_dropin_notebook_environments/README.md
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/extensions/dataframe_formatter.py
public_dropin_notebook_environments/python38_snowflake_notebook/jupyter_kernel_gateway_config.py
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/extensions/dataframe_formatter.py
public_dropin_notebook_environments/python39_notebook/jupyter_kernel_gateway_config.py
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/extensions/dataframe_formatter.py
public_dropin_notebook_environments/python39_notebook_gpu/jupyter_kernel_gateway_config.py
public_dropin_notebook_environments/r_notebook/env_info.json
public_dropin_notebook_environments/r_notebook/jupyter_kernel_gateway_config.py

[NB-4479] Increase max kernels value

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python39_genai/env_info.json
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/env_info.json

Generally there are no many changes since last envs release. But still create a PR which be used for 9.2 branch cut.

[RAPTOR-9963] update envs, release 9.2

---

pipelineController.yaml
public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/setup-ssh.sh
public_dropin_notebook_environments/r_notebook/env_info.json
public_dropin_notebook_environments/r_notebook/setup-ssh.sh

[NB-4502] fix python38 and GPU notebooks

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/runtime.py

Update a couple of confusing error messages

[RAPTOR-10002] update error messages

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311_genai/dr_requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python311_genai/fit.sh
public_dropin_environments/python39_genai/dr_requirements.txt
public_dropin_environments/python39_genai/env_info.json
public_dropin_environments/python39_genai/fit.sh
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/fit.sh
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_onnx/fit.sh
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/fit.sh
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/fit.sh
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/fit.sh
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

This updates DRUM version after all code changes are done.  On merge, will create 1.10.11 and then update drop-in envs
Here is a test from staging model_log with a dummy task
[edited_model_log.txt](https://github.com/datarobot/datarobot-user-models/files/13220376/edited_model_log.txt)
```
2023-10-31T17:17:07.259863759Z Environment variables:
2023-10-31T17:17:07.260441371Z ARTIFACT_DIRECTORY=/mnt/output
2023-10-31T17:17:07.271540402Z TRAINING_DATA_EXTENSION=.csv
2023-10-31T17:17:07.271552453Z KUBERNETES_PORT=tcp://172.20.0.1:443
2023-10-31T17:17:07.271556572Z KUBERNETES_SERVICE_PORT=443
2023-10-31T17:17:07.271559958Z FIT_RESULT_FILE=/mnt/output/FIT_RESULT.sh
2023-10-31T17:17:07.271563650Z HOSTNAME=custom-task-job-6541363d9c72b097b97b02b3-4hfpt
2023-10-31T17:17:07.271567225Z …
```

[MODEL-12560] Update versions

---

public_custom_application_environments/python39_streamlit/Dockerfile
public_custom_application_environments/python39_streamlit/README.md
public_custom_application_environments/python39_streamlit/env_info.json

[NCA-1696] Added Streamlit environment

---

custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters_schema.py
tests/drum/test_runtime_parameters.py

DRUM also needs to support deployment id as run time parameter.

[MMM-15336] DRUM should support deployment id as run time parameter

---

drapps/README.md

A copyedit of the README for the DRApps directory.

[DOC-5778] DRApps README review

---

custom_model_runner/setup.py
drapps/drapps
tests/drapps/test_drapps.py

As per request form @liororama , adding `drapps` binary and tests for it.

[RAPTOR-10068] add drapps binary

---

jenkins/test_drop_in_envs.sh

Increase the verbosity of the given test to easily track test progress.

[RAPTOR-10071] Increase verbosity of the drop-in environments test

---

public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/start_server.sh
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/start_server.sh
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/start_server.sh
public_dropin_notebook_environments/r_notebook/env_info.json
public_dropin_notebook_environments/r_notebook/start_server.sh

Suppressing a warning about dubious git location.

NB-4727: Allowlisted the working directory in the git configs

---

public_dropin_notebook_environments/python38_snowflake_notebook/agent/cgroup_watchers.py
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/agent/cgroup_watchers.py
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/agent/cgroup_watchers.py
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/r_notebook/agent/cgroup_watchers.py
public_dropin_notebook_environments/r_notebook/env_info.json

Port recent Notebooks updates:
- memory usage reporting improvement 
- https://github.com/datarobot/notebooks/pull/2854
- DR library version upgrades
- https://github.com/datarobot/notebooks/pull/2855

[NB-4861] Port recent Notebooks updates including memory usage reporting improvement and DR library version upgrades

---

public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt

https://pypi.org/project/datarobot-model-metrics/ 
Matching PR in DR Notebooks repo:
https://github.com/datarobot/notebooks/pull/2877

[MMM-15697] bump dmm library to 0.3.1

---

custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters_schema.py
tests/functional/test_runtime_parameters.py
tests/unit/datarobot_drum/runtime_parameters/test_runtime_parameters.py

Adding new runtime parameter type boolean
DataRobot PR: https://github.com/datarobot/DataRobot/pull/124180
`
If we want Bozuk models to easily add/remove support for custom metrics/side cars we need a way to pass a boolean parameter. While we can use a String parameter to do this - this is very error prune and results in errors if the wrong value is added.
`

[AGENT-5188] Adding support for boolean runtime param

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311_genai/dr_requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python39_genai/dr_requirements.txt
public_dropin_environments/python39_genai/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Release DRUM v1.10.16, and update envs. which includes support for boolean runtime parameters

[AGENT-5188] release DRUM v1.10.16

---

public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/start_server.sh
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/start_server.sh
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/start_server.sh

Port dataframe fix for codespaces - https://github.com/datarobot/notebooks/pull/2933

[NB-3656] Fix dataframe ext for codespaces

---

docker/drum_builder/Dockerfile
docker/drum_builder/build_docker.sh
jenkins/test_functional_general.sh
jenkins/test_integration.groovy
pipelineController.yaml

* add a separate job for integration tests
* update drum-builder image; already pushed

[RAPTOR-10171] add a separate job for integration tests

---

public_dropin_notebook_environments/python311_notebook/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile

Fixed issues with newly added images

[NB-4998] New images bug fixes

---

public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/r_notebook/env_info.json

Forgot to increase env versions in the previous PR (https://github.com/datarobot/datarobot-user-models/pull/907). Doing that now.

NB-4920: Increase env versions

---

public_dropin_notebook_environments/python311_notebook/dr_requirements.txt
public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python311_notebook/requirements.txt
public_dropin_notebook_environments/python38_snowflake_notebook/dr_requirements.txt
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/dr_requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/dr_requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/dr_requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt

https://pypi.org/project/datarobot-model-metrics/
Notebook PR: https://github.com/datarobot/notebooks/pull/3046

[MMM-16000] bump dmm library to 0.3.4

---

public_dropin_notebook_environments/python311_notebook/Dockerfile
public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/Dockerfile
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/r_notebook/Dockerfile
public_dropin_notebook_environments/r_notebook/env_info.json
public_dropin_notebook_environments/r_notebook/renv.lock

Follow up to: https://github.com/datarobot/datarobot-user-models/pull/925
These changes are ported over from the following notebooks PRs:
- https://github.com/datarobot/notebooks/pull/3016
- https://github.com/datarobot/notebooks/pull/3057
- https://github.com/datarobot/notebooks/pull/3053
- https://github.com/datarobot/notebooks/pull/3052
- https://github.com/datarobot/notebooks/pull/3057
Ran into errors building images after this PR:
https://github.com/datarobot/datarobot-user-models/pull/925

[NB-5277][NB-5278][NB-5279] Update dependencies in notebook drop-ins Dockerfiles

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311_genai/dr_requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python39_genai/dr_requirements.txt
public_dropin_environments/python39_genai/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

* Add support for extra model output in PPS
* Fix extra model output extraction when target name is provided (text-generation)
* Bump datarobot-model-metrics library to 0.3.6
* Other bug fixes

[RAPTOR-10337] Extra model output, bug fixes, release 1.10.20

---

custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/data_marshalling.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/model_metadata.py
custom_model_runner/datarobot_drum/drum/push.py
custom_model_runner/datarobot_drum/drum/typeschema_validation.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
requirements_lint.txt
tests/unit/datarobot_drum/drum/test_push.py
tests/unit/datarobot_drum/model_metadata/test_model_metadata.py
tests/unit/datarobot_drum/model_metadata/test_model_metadata_hyperparameters.py

I'm working on migrating test pipelines to harness.
I decided to add pylint, though for now I made pylint always exit with success even if there are errors.
I still moved some code around to get rid of circular import. There is still one import I can not get rid of. @eric-s-s maybe you could help

[RAPTOR-10422] add pylint, move code to try avoid circular deps

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
custom_model_runner/datarobot_drum/drum/enum.py
tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py

This is the first step to integrate moderations with DRUM

[AGENT-5408] Integration with moderations library

---

public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python311_notebook/requirements.txt
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt

0.5.0 version https://pypi.org/project/datarobot-model-metrics/
notebooks PR https://github.com/datarobot/notebooks/pull/3389

[MMM-16454] bump dmm library to 0.5.0

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py

Don't show any messages related to moderation framework if not required

[AGENT-5523] Hide guard presence if moderations are not enabled

---

public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python311_notebook/requirements.txt
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt

Lets make a final bump before branch cut
https://pypi.org/project/datarobot-model-metrics
Notebooks PR:  https://github.com/datarobot/notebooks/pull/3458

[MMM-16670] bump dmm to 0.5.4

---

model_templates/triton_onnx_unstructured/client/datarobot-predict.py
model_templates/triton_onnx_unstructured/client/requirements.txt

AGENT-5556 update the ONNX example: parse binary response to numpy

---

public_dropin_notebook_environments/python311_notebook/Dockerfile
public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
public_dropin_notebook_environments/python39_notebook/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu_rapids/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile

```sh
11.80 error: No package matches 'java-11-openjdk-headless-11.0.22.0.7-2.el8'
------
Dockerfile:55
--------------------
54 |     # Add any package that will be installed on system level here:
55 | >>> RUN microdnf update \
56 | >>>     && microdnf install -y python$PYTHON_VERSION-$PYT
```

[NB-5922] Update java-11-openjdk deps in notebooks

---

public_dropin_environments/python3_sklearn/Dockerfile

make changes to env

---

README.md

don't update env

---

public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python311_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt

Updating DR Python client version to v3.4

[DSX-3349] bump pysdk versions

---

public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu_rapids/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile

* Use same python version as in notebooks repo
* Update git version
```sh
19.73 Error: Unable to find a match: python3.11-3.11.5 python3.11-devel-3.11.5 git-2.39.3
```

[NB-5928] Update git in notebooks GPU kernels

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
model_templates/gpu_nemo_tensorrt_llm_textgen/model-metadata.yaml
model_templates/gpu_vllm_textgen/model-metadata.yaml
model_templates/python3_sklearn_runtime_params/model-metadata.yaml
public_dropin_gpu_environments/nim_llm/dr_requirements.txt
public_dropin_gpu_environments/triton_server/dr_requirements.txt
public_dropin_gpu_environments/vllm/Dockerfile
public_dropin_gpu_environments/vllm/dr_requirements.txt
public_dropin_gpu_environments/vllm/env_info.json

- Update runtime params example to better explain how to use newer features
- Remove chat context examples as they don't work when run in Custom Models
- Add new params for vllm env to allow more customization of server
- Bump version of vllm to support Phi-3
We want to be able to support Mistral and Phi-3 models so we need additional changes to vLLM env.

[AGENT-5735] update vLLM env

---

public_dropin_notebook_environments/README.md
public_dropin_notebook_environments/python311_notebook_base/Dockerfile
public_dropin_notebook_environments/python311_notebook_base/README.md
public_dropin_notebook_environments/python311_notebook_base/agent/README.md
public_dropin_notebook_environments/python311_notebook_base/agent/agent.py
public_dropin_notebook_environments/python311_notebook_base/agent/cgroup_watchers.py
public_dropin_notebook_environments/python311_notebook_base/agent/requirements-agent.txt
public_dropin_notebook_environments/python311_notebook_base/common-user-limits.sh
public_dropin_notebook_environments/python311_notebook_base/dr_requirements.txt
public_dropin_notebook_environments/python311_notebook_base/env_info.json
public_dropin_notebook_environments/python311_notebook_base/extensions/README.md
public_dropin_notebook_environments/python311_notebook_base/extensions/dataframe_formatter.py
public_dropin_notebook_environments/python311_notebook_base/ipython_config.py
public_dropin_notebook_environments/python311_notebook_base/jupyter_kernel_gateway_config.py
public_dropin_notebook_environments/python311_notebook_base/kernel.json
public_dropin_notebook_environments/python311_notebook_base/setup-prompt.sh
public_dropin_notebook_environments/python311_notebook_base/setup-ssh.sh
public_dropin_notebook_environments/python311_notebook_base/setup-venv.sh
public_dropin_notebook_environments/python311_notebook_base/sshd_config
public_dropin_notebook_environments/python311_notebook_base/start_server.sh

We want to provide an image that has the minimum dependencies required for the Notebook CodeSpace to work.
It will be used as a base image for custom environments that want to be used with embedded codespace.
It’s also will be the only image we provide as a built-in custom environment going forward (as we deprecate current built-in custom environments we provide).
https://datarobot.atlassian.net/browse/NB-5708

[NB-5708] Introduce base python311 notebook environment

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2

Fix port values jsonification. 
To make it work correct needed to:
* `jsonify`, which is simply defined as partial(json.dumps,...)
* explicitly cast port value to `int`
Prepare to release new DRUM version.

[RAPTOR-10839] fix port values jsonification, release v1.11.3

---

public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python311_genai/requirements.txt
public_dropin_notebook_environments/python311_notebook/env_info.json

nemo guardrails pypi package is not compatible with latest transformers version ( fastembed tokenizers version conflict )

[BUZOKNEW-473] Adjust transformers for nemo guardrails compatibility

---

public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python311_genai/requirements.txt

Bump sentence-transformers to newly released 3.0.0 ( introducing many bug fixes and new techniques )

[BUZZOK-4043] Bump sentence transformers to 3.0.0

---

public_dropin_notebook_environments/python311_notebook_base/env_info.json
public_dropin_notebook_environments/python311_notebook_base/extensions/dataframe_formatter.py

Backport https://github.com/datarobot/notebooks/pull/2656 fix
⚠️ We (nbx team) are going to deprecate all notebooks drop-ins except `notebook311_base`, so in this PR changes only that one

[NB-5419] Fix Notebooks DataFrame

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

[RAPTOR-11004] release v1.11.5

---

docker/dropin_env_base/build_image.sh
docker/dropin_env_base/requirements.txt
docker/dropin_env_base_jdk/build_image.sh
docker/dropin_env_base_jdk/requirements.txt
docker/dropin_env_base_jdk_ubi/Dockerfile
docker/dropin_env_base_jdk_ubi/build_image.sh
docker/dropin_env_base_jdk_ubi/requirements.txt
docker/dropin_env_base_r/build_image.sh
docker/dropin_env_base_r/requirements.txt

The images are already pushed to docker hub, though are not used in the envs, yet.

[RAPTOR-11006] update base images with the latest drum v1.11.5

---

public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/requirements.txt
public_dropin_environments/python311_genai/Dockerfile
public_dropin_environments/python311_genai/dr_requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/Dockerfile
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/Dockerfile
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/Dockerfile
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Update envs after DRUM release and base images update.

[RAPTOR-11008] update env's base images

---

public_dropin_environments/python39_streamlit/Dockerfile
public_dropin_environments/python39_streamlit/env_info.json

see: https://github.com/datarobot/datarobot-user-models/pull/1077#issuecomment-2206274945

[APP-2886] [10.1] Pin pillow

---

public_dropin_environments/python39_streamlit/Dockerfile
public_dropin_environments/python39_streamlit/env_info.json

see: https://github.com/datarobot/datarobot-user-models/pull/1077

[APP-2886] [10.0] Pin pillow

---

public_dropin_notebook_environments/python311_notebook_base/Dockerfile
public_dropin_notebook_environments/python311_notebook_base/env_info.json

Fix `8.010 error: No package matches 'java-11-openjdk-headless-11.0.23.0.9-3.el8'` error

Update Base Notebook 3.11 image

---

custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
custom_model_runner/datarobot_drum/resource/drum_server_utils.py
custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
tests/functional/test_inference_per_framework.py
tests/unit/datarobot_drum/drum/test_args_parser.py
tests/unit/datarobot_drum/drum/test_drum.py
tests/unit/datarobot_drum/drum/test_main.py
tests/unit/datarobot_drum/drum/test_prediction_server.py
tests/unit/datarobot_drum/runtime_parameters/test_runtime_parameters.py

Allow enable flask process via command line option --max_workers or define CUSTOM_MODEL_WORKERS  numeric runtime parameter
Option 3 from
https://docs.google.com/document/d/1yq-T7-pmjW49RsvbslNIl3BF_GRbYLti2McVmZgd_To/edit#heading=h.8vln2nt42rgh
TODO
I would like to add more test. But in general I think it is ready for review

[CODEGEN-1918] Support concurrent requests for Custom Models

---

DRCODEOWNERS
public_dropin_environments/python312_streamlit/Dockerfile
public_dropin_environments/python312_streamlit/README.md
public_dropin_environments/python312_streamlit/env_info.json
tools/image-build-utils.sh

We are advancing from the Experimental stage to a Production state. At the same time we can remove the dr_components package from environment 
- Similar environment to 3.9 python with streamlit however dr_components and other unnecessary packages removed

[APP-2364] [APPLS-2364] Add new custom app env 3.12 with streamlit 1.36.0

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
custom_model_runner/datarobot_drum/drum/description.py

[AGENT-6285] Warning message if moderation is disabled

---

tools/image-build-utils.sh

Prev PR, breaks this: https://ci1.devinfra.drdev.io/job/Custom_Models_drop_in_environment_tests/5104/

[APP-3269] follow up fix tests

---

public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311_genai/dr_requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Bump DRUM in the environments to make them have the latest for the release

[RAPTOR-11574] update DRUM version in environments

---

RELEASE.yaml

[RAPTOR-11573] update RELEASE.yaml

---

RELEASE.yaml

I made a mistake when specifying the endpoint. [Docs](https://dev-docs.drdev.io/release/branches/RELEASE.yaml.html#post_branch_cut_pipelines) specify it:
> `<organization-name>/projects/<project-name>/pipelines/<pipeline-name> for harness`

[ENGPROD-7037] Fix post branch cut job endpoint for datarobot user models

---

RELEASE.yaml

The pipeline input is already being adjusted in the respective repo

[ENGPROD-7040] Parametrize datarobot_user_models_ref and execution_environment_installer_ref

---

model_templates/gpu_nim_textgen/README.md
model_templates/gpu_nim_textgen/model-metadata.yaml
model_templates/gpu_vllm_textgen/README.md
model_templates/gpu_vllm_textgen/engine_config.json
model_templates/gpu_vllm_textgen/model-metadata.yaml

- Cleanup NIM example README
- Update to use latest version of Llama model
- Adds README for vLLM template
It's useful to have fully baked examples of how to use the NIM and vLLM envs and a readme to go along with the template files is invaluable.

Add README for vLLM example model

---

public_dropin_notebook_environments/python311_notebook_base/Dockerfile

[CFX-405] Removing strictly defined libs versions
[CFX-405]: https://datarobot.atlassian.net/browse/CFX-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CFX-405] Removing strictly defined libs versions

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

[CODEGEN-1974] Bump DRUM version

---

custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py

- Remove handling of `.remote` files
- Change order of when status updator is intialized
Need to be sure to detect the hooks before setting up status updater. Also remove code for `.remote` files because there is a dedicated project for that.

[AGENT-6475] Fix status update output

---

public_dropin_notebook_environments/README.md
public_dropin_notebook_environments/python311_notebook/extensions/dataframe_formatter.py
public_dropin_notebook_environments/python311_notebook_base/env_info.json
public_dropin_notebook_environments/python311_notebook_base/extensions/dataframe_formatter.py
public_dropin_notebook_environments/python39_notebook_gpu/extensions/dataframe_formatter.py
public_dropin_notebook_environments/python39_notebook_gpu_rapids/extensions/dataframe_formatter.py
public_dropin_notebook_environments/python39_notebook_gpu_tf/extensions/dataframe_formatter.py

Remove custom index assign in dataframe formatter

[CFX-123] Update dataframe formatter

---

public_dropin_notebook_environments/python311_notebook_base/Dockerfile

[CFX-506] Update PYTHON_EXACT_VERSION to 3.11.10

---

public_dropin_notebook_environments/python311_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt

Upgrade to DMM 0.6.12 to pick up prompt-similarity and logging improvements.

[MMMARCH-337] Upgrade to DMM 0.6.12

---

public_dropin_gpu_environments/nim_llm/README.md

Fix minor Markdown nit

---

public_dropin_gpu_environments/nim_llm/env_info.json
public_dropin_gpu_environments/triton_server/env_info.json
public_dropin_gpu_environments/vllm/env_info.json

Update the metadata for the 3 GPU envs
- Use a custom `label` so we can display a more meaningful version string to users that reflects the upstream version
- Include the base image in the version description
- Tweak name of NIM to make it more clear it is tied to specific model
The old naming and metadata of envs could use some improvement so this is the next iteration.

Update metadata for GPU envs

---

model_templates/gpu_nim_textgen/README.md
model_templates/gpu_nim_textgen/model-metadata.yaml
model_templates/gpu_vllm_textgen/README.md
model_templates/gpu_vllm_textgen/model-metadata.yaml

Update README to be more clear about resource bundles (we also changed IDs so adding more description to make them more future-proof. Update the default context length to make sure we fit inside the min resource bundle.
Also while I'm at it, fixup the README for NIM example as well.
We want the example to be plug-n-play.

Tweak defaults for vLLM example

---

custom_model_runner/datarobot_drum/drum/artifact_predictors/sklearn_predictor.py
custom_model_runner/datarobot_drum/drum/artifact_predictors/xgboost_predictor.py

Follow up PR for https://github.com/datarobot/datarobot-user-models/pull/1189.
Adding GeoPoint target type for base python predictors

[MMMDATA-875] Add geopoint to predictors

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
custom_model_runner/datarobot_drum/drum/data_marshalling.py
custom_model_runner/datarobot_drum/drum/enum.py
custom_model_runner/datarobot_drum/resource/deployment_config_helpers.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
tests/fixtures/geo_point_custom.py
tests/functional/test_deployment_config.py
tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
tests/unit/datarobot_drum/drum/test_data_marshalling.py

GEO_POINT support still in development. After some research for better future support we decided to switch output of GEO_POINT target models to WKT (Well Known Text) as it allow us easy support 2D and 3D points

[MMMDATA-875] Change geopoint output to wkt

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python311_genai/requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_onnx/requirements.txt
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/requirements.txt

Update environments:
* set DRUM v1.15.0
* assign customModel use case. By default, missing value is treated as customModel

[RAPTOR-11770] update envs: drum v1.15.0 and set use_cases

---

public_dropin_notebook_environments/python311_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt

Update to the latest DMM version (0.6.13) to get changes for handling of numerics in the environment.
The latest DMM has fixes for handling of numerics in the execution environments.

[MMMARCH-358] Update to DMM 0.6.13

---

harness_scripts/base_check/integration_tests_entrypoint.sh
harness_scripts/base_check/unit_tests_entrypoint.sh
harness_scripts/common/create_and_source_venv.sh
harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
harness_scripts/functional_general/custom_java_predictor_entrypoint.sh
harness_scripts/functional_general/general_tests_entrypoint.sh
harness_scripts/functional_general/mlops_reporting_entrypoint.sh

Make every Harness step independent and robust by creating its own Python venv and install dependencies from scratch.
It’ll will later help me to cleanly remove the tracking agent dependency and thus its jar files from the drop-in environments.

[RAPTOR-11814] Improve Harness scripts for better robustness and independence

---

public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python311_notebook/requirements.txt
public_dropin_notebook_environments/python311_notebook_base/env_info.json
public_dropin_notebook_environments/python311_notebook_base/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt

We are going to release `python311_notebook_base` environment, so addressed feedback to do so.
* Bump environmentVersionId
* Upgrade drum to the latest version

[CFX-590] Prepare Notebook base environment for release

---

tools/generate-model-artifacts.sh

This repository contains model artifacts that are generated by Jupiter Notebook scripts. Whenever new versions of related packages are bumped, it is required to re-generate these artifacts and copy them to their expected destinations in the repository. In this PR, a new script is introduced to generate these artifacts and copy them to their destination.

[RAPTOR-11863] Add a script to generate model artifacts and copy them to required destination

---

public_dropin_notebook_environments/python311_notebook_base/env_info.json
public_dropin_notebook_environments/python311_notebook_base/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt

Upgrading to latest DRUM package in DR Notebooks drop-in Envs
https://pypi.org/project/datarobot-drum/
Recently, significant updates have been have been made to datarobot-drum, including removing the mlpiper and pyarrow dependencies.

[CFX-1429] Upgrading to latest DRUM package in DR Notebooks drop-in Envs

---

public_dropin_gpu_environments/python311_genai/env_info.json
public_dropin_gpu_environments/python311_genai/requirements.txt

In the previsous PR I fogrot to bump the version id for this env.

[BUZZOK-24833] Bump version id

---

public_dropin_notebook_environments/python311_notebook_base/env_info.json
public_dropin_notebook_environments/python311_notebook_base/sshd_config
public_dropin_notebook_environments/python39_notebook_gpu/sshd_config
public_dropin_notebook_environments/python39_notebook_gpu_rapids/sshd_config
public_dropin_notebook_environments/python39_notebook_gpu_tf/sshd_config
public_dropin_notebook_environments/r_notebook/sshd_config

Updating our base notebook drop-in Env. to work with recent changes we've made to be FIPS compliant
In order for our terminals feature to work this update is required

[CFX-1527] Update base notebook image for FIPS compliance as well as others that are purely examples

---

.harness/java_codegen_update_env_version_pr_input.yaml
.harness/python311_genai_update_env_version_pr_input.yaml
.harness/python3_keras_update_env_version_pr_input.yaml
.harness/python3_onnx_update_env_version_pr_input.yaml
.harness/python3_pmml_update_env_version_pr_input.yaml
.harness/python3_pytorch_update_env_version_pr_input.yaml
.harness/python3_sklearn_update_env_version_pr_input.yaml
.harness/python3_xgboost_update_env_version_pr_input.yaml
.harness/r_lang_update_env_version_pr_input.yaml
.harness/update_env_version.yaml

Create the Harness pipeline to update the environment version ID in `env_info.json` whenever changes are made to the environment directory.
This automates the manual work for developers to bump the environment version ID each time they make a change to an environment.
Tested and verified here: 
https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/all/orgs/Custom_Models/projects/datarobotusermodels/pipelines/update_env_version/executions/bpFiSQ4CSWuh324UTVEuOw/pipeline?connectorRef=account.svc_harness_git1&repoName=datarobot-user-models&branch=nolanm%2Fupdate-env-version-pipeline&storeType=REMOTE

update environment version pipeline

---

public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311/Dockerfile
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311_genai/Dockerfile
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/Dockerfile
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/Dockerfile
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/Dockerfile
public_dropin_environments/r_lang/env_info.json

In addition to resolving the `AsymmetricPrivateKey` scanning report issue, this change significantly reduces the image size. For example, the `python311` image size decreased from **504MB** to **395MB**.

[RAPTOR-12104] Solve scanning error of AsymmetricPrivateKey in _python_rsa.cpython-311.pyc

---

custom_model_runner/datarobot_drum/drum/enum.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
requirements_test_unit.txt
tests/unit/datarobot_drum/drum/gpu_predictors/test_gpu_predictors.py

All other NIM target types should not have chat capability

[AGENT-6954] Ensure only TextGen models have chat capability

---

public_dropin_nim_environments/nim_sidecar/Dockerfile
public_dropin_nim_environments/nim_sidecar/env_info.json
tests/functional/test_inference_gpu_predictors.py

[11.0] [AGENT-7023] Default to 10 HTTP workers for nim sidecar container (#1360)

---

Makefile
requirements_test_unit.txt

Add top-level `Makefile` with `help` target.
This helps make the development process a little more similar to many of the other repositories that provide `make help` to guide developers.
Here's what the help looks like:
```shell
(drum) datarobot-user-models % make help
=====================
🛠  Available Commands
=====================
Usage:
make <target>
General
help                       Print this message
prereq                     Install the development prerequisites
clean                      Remove build artifacts
Lint
lint                       Run linting
delint                     Attempt to fix lint issues
pylint                     Run pylint
Test
tests                      Run all tests
coverage                   Measure unit-test code coverage
unit-test                  Run …
```

[MMM-18647] Add top-level Makefile (with help) to guide developers

---

README.md
public_dropin_gpu_environments/vllm/Dockerfile
public_dropin_gpu_environments/vllm/env_info.json
public_dropin_gpu_environments/vllm/start_server.sh

Issue 1. Venv was not activated, hence DRUM used wrong python to start vllm.
error: vllm module not found.
Issue 2. Torch used by vllm tries to resolve the current user. We don't create the user 1000.
Issue 3. Make sure .cache in the HOME dir has user permissions (1000)
master PR
https://github.com/datarobot/datarobot-user-models/pull/1371
Tested on EKS 11.0:
```
2025-04-05 13:35:16,202 INFO drum.datarobot_drum.drum.gpu_predictors:  Load-model hook completed.
2025-04-05 13:35:16,261 INFO drum.datarobot_drum.drum.gpu_predictors.base:  Loading CLI args from config file: /opt/code/engine_config.json...
2025-04-05 13:35:16,263 INFO drum.datarobot_drum.drum.gpu_predictors:  vLLM Inference Server is launching...
2025-04-05 13:35:19,746 INFO drum.datarobot_drum.drum.gpu_predictors.base:  INFO …
```

[RAPTOR-12205] Fixed vllm environment

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

see changelog for changes
based off of conversation here: https://github.com/datarobot/datarobot-user-models/pull/1392#discussion_r2052932337

[MODEL-18996] updated drum version

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

Bump DRUM version to include the most recent changes

[MMM-19225] Bump DRUM version

---

public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311/Dockerfile
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311_genai/Dockerfile
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/Dockerfile
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/Dockerfile
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/Dockerfile
public_dropin_environments/r_lang/env_info.json

Custom model PPS requires `chgrp` and `rm`.
Also keep `find` for convenience

[RAPTOR-12536] add more required tools into envs

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/requirements.txt
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311/requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python311_genai/requirements.txt
public_dropin_environments/python311_genai_agents/env_info.json
public_dropin_environments/python311_genai_agents/requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_onnx/requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/requirements.txt

[RAPTOR-12538] bump jinja2 flask in public envs

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/requirements.txt

* Added more robust tracing configuration, with ability to provide relevant configs via env vars
* Separated instrumentation of requests and aiottp
* Added requests/aiohttp instrumentation into dependencies, for models like nims

More robust tracer setup.

---

public_dropin_environments/python311_genai_agents/env_info.json
public_dropin_environments/python311_genai_agents/requirements.in
public_dropin_environments/python311_genai_agents/requirements.txt
public_dropin_environments/python311_genai_agents/run_agent.py

We need to add `Opentelemetry` to the GenAI Agents image to properly instrument everything.

[BUZZOK-25849] Bump requirements to add opentelemetry for LLMs

---

DRCODEOWNERS
dependbot.yml

Rename custom models

---

DRCODEOWNERS

Change agent ownership

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

For more nim testing I need most recent drum in relevant environments, here is PR that bumps version requirements files.

[MMM-19600] release DRUM v1.16.15

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py

The `moderations` library has been updated/improved to be more streamline. The improvements started in 11.1.4, and have been worked on since. This removes a couple "generations" of old interfaces with `moderations`. 
Reduce amount of code to maintain, and update testing to be more understandable.
The newer model relies on the `moderation_pipeline_factory()` and the resulting `ModerationPipeline` object (with `score()` and `chat()`) that gets stored in `PythonModelAdapter._mod_pipeline`. This code path remains unchanged.
1. Removed `PythonModelAdapter` references to `_moderation_pipeline`, `_moderation_score_hook` and `_moderation_chat_hook`.
2. Consolidate tests

[MMM-19595] Always use newer moderations library pipeline framework

---

Makefile
requirements_lint.txt
requirements_test.txt
tools/env_version_update.py

Improve tooling for updating execution-environment version.
This reduces the number of steps required (no longer need additional module installation), and provide `make` visibility to see how to update execution-environment version.

[MMM-19566] Improve tooling for updating execution-environment version

---

public_dropin_environments/python311_genai_agents/Dockerfile
public_dropin_environments/python311_genai_agents/Dockerfile.local
public_dropin_environments/python311_genai_agents/env_info.json
public_dropin_environments/python311_genai_agents/run_agent.py

Update the GenAI Agents docker image to match the changes implemented in the source component. **I think this should be the final bump before we're ready for this to go into staging as a default environment.**
- Synchronize `run_agent.py` with https://github.com/datarobot/af-component-agent/blob/main/template/%7B%7Bagent_app_name%7D%7D/docker_context/run_agent.py
- Bump Dockerfiles for `prod` and `local` to use `uv` as the primary pip installer. This speeds up image compilation times by ~30%.

[BUZZOK-26080] Bump run_agent and dockerfile for GenAI Agents

---

custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
custom_model_runner/datarobot_drum/drum/main.py
tests/unit/datarobot_drum/drum/test_main.py

* Fix OTEL when flask server is running in forking mode
* Proactively instrument OpenAI code, since custom.py is not available for users in case of GPU models.

[MMM-19667] Fix fokring and instrument OpenAI

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

[MMM-19673] Bump version.

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/requirements.txt
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311/requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python311_genai/requirements.txt
public_dropin_environments/python311_genai_agents/env_info.json
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_onnx/requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/requirements.txt
public_dropin_gpu_environments/vllm/env_info.json
public_dropin_gpu_environments/vllm/requirements.txt
public_dropin_nim_environments/nim_llama_8b/env_info.json
public_dropin_nim_environments/nim_sidecar/env_info.json
public_dropin_nim_environments/nim_sidecar/requirements.txt

Bump environments with new drum.

[MMM-19697] Bump environments with new drum.

---

example_dropin_environments/triton_server/env_info.json
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python311_genai_agents/env_info.json
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/env_info.json
public_dropin_gpu_environments/vllm/env_info.json
public_dropin_nim_environments/nim_sidecar/env_info.json
public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python311_notebook_base/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json

[RAPTOR-12716] add contextUrl to env_info.json

---

.harness/test_functional_general.yaml
harness_scripts/functional_general/general_tests_entrypoint.sh
harness_scripts/functional_general/mlops_reporting_entrypoint.sh
public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311/Dockerfile
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311_genai/Dockerfile
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python311_genai_agents/Dockerfile
public_dropin_environments/python311_genai_agents/env_info.json
public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/Dockerfile
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/Dockerfile
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/Dockerfile
public_dropin_environments/r_lang/env_info.json

Migrate opensource envs to chainguard

---

public_dropin_gpu_environments/vllm/Dockerfile
public_dropin_gpu_environments/vllm/env_info.json

[cherry-pick][RAPTOR-14024] set PYTHONUNBUFFERED=1 in vllm env 

---

harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
requirements_for_per_framework_tests.txt
requirements_test.txt
requirements_test_unit.txt

httpx was added for tests a couple of days ago.
Handle it in requirements

[RAPTOR-14039] add httpx for testing

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/requirements.txt
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311/requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_onnx/requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/requirements.txt

The `protobuf==5.29.4` was reported as a CVE. This packages is bumped to `5.29.5` for all the related envs.

[VUL-11510] Bulk resolved CVEs

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/requirements.txt
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311/requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_onnx/requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/requirements.txt

cherry pick https://github.com/datarobot/datarobot-user-models/pull/1541

[cherry-pick][VUL-11510] Bulk resolved CVEs (#1541)

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/requirements.txt
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311/requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_onnx/requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/requirements.txt
public_dropin_gpu_environments/vllm/env_info.json
public_dropin_gpu_environments/vllm/requirements.txt

This update is required
* for the 'set_api_spooler' with arugments
* to have released mlops version in requirements overall
---------

[RAPTOR-14067] bump drum and mlops in all the envs (#1546)

---

.harness/test_functional_by_framework_multisteps.yaml

Backporting : https://github.com/datarobot/datarobot-user-models/pull/1574

[cherry-pick][RAPTOR-14205] update pipeline to a new reconcile template version to show status in PR

---

.harness/reusable_build_images.yaml
.harness/test_functional_by_framework_multisteps.yaml

To prettify status message in PR, I need to change pipeline identifier.
This breaks a trigger. So I'll need to disable trigger, merge, and reenable trigger.
I'll do it later today

[RAPTOR-14207] change pipeline identifier to prettify status message

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311_genai_agents/env_info.json
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/env_info.json

This is an execution environment version ID auto bump to trigger automated
image rebuilds for rebase on the latest base image builds.
[Execution:Custom_Models/execution_environment_installer/EE_Chart_Bump_All_Environment_Versions/jxgSfOiCQ_iBqn2Q54GAuA](https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/module/ci/orgs/Custom_Models/projects/execution_environment_installer/pipelines/EE_Chart_Bump_All_Environment_Versions/executions/jxgSfOiCQ_iBqn2Q54GAuA)

[-] Autobump env_info version IDs

---

public_dropin_environments/python311_genai_agents/Dockerfile
public_dropin_environments/python311_genai_agents/requirements.in
public_dropin_environments/python311_genai_agents/requirements.txt

Port back dockerfile changes added in https://github.com/datarobot/recipe-datarobot-agent-templates/pull/235

[BUZZOK-27771] Update public execution env

---

tools/image-build-utils.sh

fix command to make env var be properly read inside container
Test on the branch has passed the failing point: https://ci1.devinfra.drdev.io/job/Custom_Models_drop_in_environment_tests/7420/console

[RAPTOR-14745] fix command to be properly populated inside container

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

[MMM-20737] Bump DRUM version for release.
