datarobot/datarobot-user-models

public_dropin_environments/python3_keras/README.md
public_dropin_environments/python3_pmml/README.md
public_dropin_environments/python3_pytorch/README.md
public_dropin_environments/python3_sklearn/README.md
public_dropin_environments/python3_xgboost/README.md
public_dropin_environments/r_lang/README.md

custom.py file is referenced with a broken link. Changing the readmes to have a link to the appropriate template
modified the link in each readme file

Update each custom.py/r link to the proper file in the templates folder

---

custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/error_handling.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/datarobot_drum/drum/runtime.py
custom_model_runner/datarobot_drum/drum/server.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
tests/drum/test_custom_model.py

In server mode, we should have an option to have the server up even when errors occur on model loading etc.
This is required so that k8s doesn't restart container as it won't help.
Instead, the server should allow getting the errors via API.
As we've discussed, fail points are
1. Imports
2. Model loading
There was an idea to check imports and model loading before running drum.
However, imports and model loading is coupled in drum: depending on model artifacts present predictors are selected, and each predictor has its own set of imports.
Additionally, having model loading _before_ drum leads to logic/code duplication.
To me, it's better to wrap _everything_ with error handling logic, that can start "error server" in case of exceptions.
Benefit 1:
we don't have to gather all imports in one …

[RAPTOR-2904] Add flag and start dummy server to propagate imports/pipeline failures

---

tests/drum/test_custom_model.py

pytest has built-in fixtures for managing temp files and directories.
Replace:
- `mkdtemp`+`shutil.rmtree` (`_delete_custom_model_dir `)
- `NamedTemporaryFile`
- `TemporaryDirectory`
with usage of `tmp_path` built-in pytest fixture, that automatically handles cleanup.

[RAPTOR-3083] Let pytest manage temp files and directories in tests

---

custom_model_runner/datarobot_drum/drum/runtime.py
custom_model_runner/datarobot_drum/drum/server.py
tests/drum/test_custom_model.py

503 status was used to signal that drum server initialization failed.
However, 503 is also used to signal issues with pods. In such a case, DR retries requests to drum server (as it expects drum server to be restarted and working).
To signal drum server initialization failure, we need a dedicated http status.
I used a custom one for this purpose - 513.
Here's draft PR how this logic will be used on DR side: https://github.com/datarobot/DataRobot/pull/65690

[RAPTOR-3088] Use custom status code to propagate drum pipeline initialization failure

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/runtime.py
tests/drum/test_custom_model.py

This PR hides error server output
```
* Serving Flask app "datarobot_drum.drum.server" (lazy loading)
* Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
* Debug mode: off
```
similarly for how it's done for prediction server.

[RAPTOR-3088] Hide error server output (similarly to pred server output)

---

.github/pull_request_template.md
README.md
custom_model_runner/README.md
model_templates/inference/java_codegen/README.md
model_templates/inference/python3_keras/README.md
model_templates/inference/python3_keras_joblib/README.md
model_templates/inference/python3_pmml/README.md
model_templates/inference/python3_pytorch/README.md
model_templates/inference/python3_sklearn/README.md
model_templates/inference/python3_xgboost/README.md
model_templates/inference/r_lang/README.md

Trying to organize docs in the following way:
Readme in the root: https://github.com/datarobot/datarobot-user-models contains information about every aspect of custom models:  Quickstart, examples, how to assemble folder, etc
Readme in the: https://github.com/datarobot/datarobot-user-models/custom_model_runner - contains everything about drum and references to the first document.
DR App docs will be changed in the way to refer to two of these readmes

[DOC-2145] update docs

---

docker/drum_integration_tests_base/Dockerfile
docker/drum_integration_tests_base/build_test_docker.sh

Drum integration tests run in a docker container.
To compile scala code JDK should be installed into this container.
Dockerhub image has been already updated

Update drum_integration_tests_base docker

---

custom_model_runner/datarobot_drum/drum/runtime.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
tests/drum/test_custom_model.py

Use a dedicated "/health/" route to check server state.
The reason to do this is that if "/predict/" is used - for healthy server we still can get 422 of dataset is not specified etc. and this error response is logged by flask.
As a result, even for healthy servers there's no easy way to get 200 response that'd mean "the server is healthy".
CM testing without this fix:
CM testing with this fix:
Note: errors are propagated via "/predict/" route as well - the current protocol is kept.

[RAPTOR-3195] Use a dedicated endpoint to check server health

---

custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/datarobot_drum/drum/runtime.py
tests/drum/test_custom_model.py

Two fixes here:
1. Fix indentation for os._exit call in a SIGINT handler.
2. Showing error messages. Drum is used locally and in the env in the app.
Locally we want to show nice error message without stacktrace and in a server mode we want to see stacktrace.
Maybe we want to add a flag `--show-stacktrace` and use it in `start_server.sh` and `fit.sh`?

[RAPTOR-3220] don't log exception if args were not parsed

---

custom_model_runner/datarobot_drum/drum/push.py
tests/drum/test_units.py
tests/functional/test_drop_in_environments.py
tests/functional/test_inference_model_templates.py
tests/functional/test_training_model_templates.py

the blueprint creation method used in the test was changed to support unreleased behavior. I changed the test to use the more verbose, but more stable path
Also, since we're using the 2.22 beta, we have to use a base env id when creating model versions in drum push

[RAPTOR-3249] don't use experimental methods that assume dependency management

---

custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py

import only required predictor - Java, python or R according to model artifact language
FOr example, when running Java model we don't need to import all the Python ml frameworks

[RAPTOR-3220] import only required language predictor

---

docker/drum_integration_tests_base/Dockerfile
requirements.txt

Install nginx, will be required for uwsgi+nginx based prediction server.
- Fix requirements: datarobot==2.22.0b0 dep is installed in `requirements_test.txt`;
- `datarobot-drum` itself doesn't need to be installed.

Update test docker: install nginx, fix requirements

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_h2o/dr_requirements.txt
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Placeholder for publishing DRUM and updating envs.
Once tests with `rcX` version pass, I publish drum 1.1.4 without rc suffix, and merge

Release DRUM 1.1.4 and env update place holder

---

tests/functional/test_drop_in_environments.py

This test will be unskipped when we implement API for calculating feature impact

Skip feature impact test before FI API is available in the API client

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
custom_model_runner/datarobot_drum/drum/model_adapter.py
tests/drum/test_custom_model.py

Allow to enforce run language with argument: --language [java, r, python]
This argument will be added into start_server.sh in the drop in environments
Added header "Running environment language: [R|Java|Python]" into error messages. Because of current code structure, I didn't find a nice way to add it into one common place.
This argument will be used in the drop in envs, to give env some control and ensure that drum will running proper framework, e.g. running Java in java env.

[RAPTOR-3319] allow to enforce run language

---

tests/functional/test_drop_in_environments.py

This should trigger calculation of Feature Impact and so test might become valid again.

[RAPTOR-3332] Fix & unskip feature impact test

---

custom_model_runner/datarobot_drum/drum/model_adapter.py

Relocate `import sklearn` into a method using sklearn.
Global `import sklearn`  in this file interferes when running inference models which don't require sklearn.

[RAPTOR-3342] relocate import sklearn

---

custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
custom_model_runner/datarobot_drum/drum/model_adapter.py

Make order of extensions and files deterministic in error messages + improve wording.

[RAPTOR-3406] Make order of extensions and files deterministic in error messages

---

model_templates/training/python3_keras_joblib/README.md
model_templates/training/python3_keras_joblib/example_code.py
model_templates/training/python3_xgboost/README.md
model_templates/training/python3_xgboost/create_pipeline.py

Our numeric preprocessing for sklearn and xgboost was causing an error if the users passed in data with a totally-missing numeric column. Arguably the user shouldn't be doing this, but it is also relatively straightforward to handle...maybe I should add some logging to indicate that we encountered a column with nothing but NaNs and had to drop it?

[RAPTOR-3395] drop any fully missing columns in preprocessing for keras and xgboost

---

dev_env/java_nginx_env/Dockerfile
dev_env/python3_nginx_env/Dockerfile
dev_env/rlang_nginx_env/Dockerfile
docker/java_dropin_env_base/Dockerfile
docker/java_dropin_env_base/README.md
docker/python3_dropin_env_base/Dockerfile
docker/python3_dropin_env_base/README.md
docker/r_dropin_env_base/Dockerfile
docker/r_dropin_env_base/README.md
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/start_server.sh
public_dropin_environments/java_h2o/env_info.json
public_dropin_environments/java_h2o/start_server.sh
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/start_server.sh
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/start_server.sh
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/start_server.sh
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/start_server.sh
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/start_server.sh
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/start_server.sh

**### This will be merged after drum release and prod drop in envs update.**
Enable uwsgi based prediction server with one worker in drop in envs.
For now, these envs will be deployed only on staging.
--with-error-server param has been removed. Error server has been used to serve error messages, if model loading fails.
With uwsgi server, loading fails on worker, so main drum process won't fail. Instead worker will be serving error message.

Switch drop-in envs to work with uwsgi server with one worker

---

custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
tests/drum/run-drum-tests-in-container.sh
tests/drum/test_mlops_monitoring.py

Adding support for MLOps monitoring in drum. This way we can monitor models running outside of DR using DR App.
Things to go in next  PR -
1. Documentation and example in the README - I consider this PR as a beta so I am not  updating the docs right now
2. Add support for java predictor and r predictor like done in the python predictors
3. Add tests to include the java and r predictors.

[RAPTOR-3430] mlops: adding mlops monitoring support

---

model_templates/training/python3_pytorch/model_utils.py

y_hat was being returned as a (batch_size, 1) shaped vector, while the y var is (batch_size) shaped, which caused pytorch to complain. This reshapes that target to the same dimension as the model's output.

Fix regression dimension mismatch in pytorch template

---

custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/drum.py

Monitoring arguments assignment should be available only for score and server modes.
But initialize those arguments to False/None, if they are needed for fit or other modes.

[RAPTOR-3555] init monitoring arguments in modes that implicitly use them

---

README.md

As has been pointed out in issue #89 Docs point to wrong R/java inference model templates.

[Issue #89] Fix readme links to r/java inference models

---

docker/drum_integration_tests_base/Dockerfile

Add libs required for changes that will be introduced in unstructured mode.
Added  R `pack` lib and relocated others to be installed from ubuntu repo
Container already built, uploaded and tested.

[RAPTOR-3574] update drum test docker with required R libs

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/common.py
model_templates/inference/python3_xgboost/custom.py
tests/drum/test_args_parser.py

Adding multiclass as a target type
> *NOTE* Does not add multiclass functionality
and adding options for configuring class labels.  Class labels can either be set using `--class-labels` with labels in the command, or `--class-labels-file`, a path to a file with newline delimited class labels
Starting the process of adding multiclass support
add multiclass functionality

[RAPTOR-3741] add options for multiclass

---

docker/java_dropin_env_base/README.md
docker/python3_dropin_env_base/README.md
docker/r_dropin_env_base/README.md

- Fixed repo names in the READMEs for the three env base images, e.g. `java_dropin_env_base` -> `java-dropin-env-base`
- markdown linting (trailing spaces, line endings)
I was testing out the drop-in environments while reviewing the Custom Models feature of DR and wanted to pull down these images. The repo names given don't exist in Docker Hub.

Fix docker image repo names in documentation

---

public_dropin_environments/python3_pmml/requirements.txt
tests/fixtures/cmrun_docker_env/requirements.txt

Bumping deps version in a couple of places i missed.

Deps up: pandas==1.1.0, numpy==1.19.0

---

dev_env/rlang_nginx_env/start_server.sh
public_dropin_environments/r_lang/start_server.sh

Switching envs back to work with nginx and uwsgi.
The problem was in mlpiper, introduced with:
https://github.com/datarobot/mlpiper/commit/ef4be49a5e2f743ef5760c07eecc5637f43b7f3f
and fixed with:
https://github.com/datarobot/mlpiper/commit/eed476a0fd09d626b43464969764be4bceb93093
I updated base R container

Switch R envs back to use nginx

---

custom_model_runner/datarobot_drum/drum/artifact_predictors/keras_predictor.py

Handle a case when standalone keras package is not installed.
A couple of days ago I removed support for standalone keras. So drum integration tests are supposed to work in the env without standalone keras, but tensorflow>=2.2.1. Tests didn't fail because old test container was in use.
Today I updated integration tests container, so there is no keras package in it.
This code is still there only for keras vizai case in functional tests which doesn't work with tf.keras (@rsugumar is expected to help).

[RAPTOR-3576] handle the case where standalone keras is not installed

---

custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/memory_monitor.py
custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
tests/drum/test_performance_check.py

`psutil.proc.name()` behaves differently on Mac and Linux, so `if current_proc.name() == ArgumentsOptions.MAIN_COMMAND` statement didn't work as expected on Mac.
Also add a "label" environment variable to a drum server subprocess to be able to kill it in case `perf-test` fails

[RAPTOR-3768] fix process detection for memory monitoring

---

custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
custom_model_runner/datarobot_drum/resource/unstructured_helpers.py
model_templates/inference/python3_unstructured/README.md
model_templates/inference/r_unstructured/README.md
tests/drum/test_unstructured_mode.py

Some cleanup for `score_unstructured` hook.
Request (and related batch functionality):
In unstructured mode we treat incoming mimetype that startswith `text/` or `application/json` or "" or missing as "textual"
If user sends request with "textual" mimetype, but charset is missing, we set default charset to `utf8`.
If user sends request with non textual mimetype, but charset is missing, we don't pass charset param into the hook.
Response (and related batch functionality):
Outgoing
If user returns string, but doesn't provide mimetype/charset, we set them to `text/plain` and `utf8`
If user returns binary, but doesn't provide mimetype/charset, we set them to `application/octet-stream` and `None`

[RAPTOR-3574] don't assign default charset if mimetype is binary

---

README.md
custom_model_runner/README.md
model_templates/inference/python3_pytorch_multiclass/custom.py
model_templates/training/python3_keras_joblib/custom.py
model_templates/training/python3_keras_vizai_joblib/custom.py
model_templates/training/python3_pytorch/custom.py
model_templates/training/python3_pytorch_multiclass/custom.py
model_templates/training/python3_sklearn_binary/custom.py
model_templates/training/python3_sklearn_multiclass/custom.py
model_templates/training/python3_sklearn_regression/custom.py
model_templates/training/python3_sparse/custom.py
model_templates/training/python3_xgboost/custom.py

Updated **drum** formatting to DRUM
An easier product reference / naming convention

DOC-2421: Updated DRUM capitalization

---

README.md
custom_model_runner/datarobot_drum/drum/artifact_predictors/keras_predictor.py
custom_model_runner/datarobot_drum/drum/description.py
model_templates/inference/python3_keras_vizai_joblib/artifact.joblib
model_templates/inference/python3_keras_vizai_joblib/model_utils.py
model_templates/training/python3_keras_vizai_joblib/model_utils.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

This PR moves the final step in the pipeline to `inference` code.
The `feature_extraction` step in the pipeline is moved to `inference` code, coz while pickling the artifact during the `drum fit` stage, the upgraded libraries is causing the error `TypeError: can't pickle _thread.RLock objects` (root cause of the issue is not very clear yet), however moving this step to inference code resolves this issue (as we're _skipping the pickling_ that step basically)

[RAPTOR-3842] fix for pickling with joblib creates issue with TF2 upgrading

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2

When executing drum with these combination flags: `--production --max-workers 1`, setup the mlpiper pipeline to use a singe uwsgi process (without a master)

[RAPTOR-3839] Add support for a single uwsgi process in production mode

---

custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
custom_model_runner/requirements.txt
tests/drum/test_inference.py
tests/fixtures/cmrun_docker_env/drum_requirements.txt

Add support for Arrow format for prediction request payload in addition to csv:`
- make predictors expose `supported_payload_formats`
- for now, only python predictors support Arrow
- in future R/Java support for Arrow can also be added
- add `GET /capabilities/` endpoint that returns supported payload formats
- add tests
Pandas dataframe to csv serialization is slow in Python 2.
Making DRUM support fast formats like Arrow gives DRUM using opportunity to have better predictions performance.

[RAPTOR-3620] Add capabilities endpoint + arrow support

---

model_templates/training/python3_pytorch/model_utils.py
tests/conftest.py
tests/drum/constants.py
tests/drum/test_fit.py
tests/functional/test_training_model_templates.py

the .flatten() call was basically undoing the reshape as far as I can tell, leading to a warning about different target/input sizes

remove flatten from pytorch template

---

custom_model_runner/datarobot_drum/drum/drum.py
tests/conftest.py
tests/drum/constants.py
tests/drum/test_fit.py
tests/testdata/10k_diabetes_sample.csv

So R has a fun thing where it thinks TRUE/FALSE is boolean while python thinks True/False is. And pandas will automatically convert TRUE to True when reading unless you tell it to read that column as a string. Which means in something like 10k diabetes, where our target values are TRUE and FALSE, pandas thinks they're a different value from R, which makes the r scoring code angry. 
I'm not convinced that this is the best solution to that problem, but it does seem to be a workable one: basically when we try to guess at the class labels, it adds an extra check for R: if pandas read a target in that's boolean, we tell it to go back and read it in as a string. 
Very open to other suggestions, since this feels like a pretty hacked-together approach to a sort of obnoxious edge case.
Turns out …

R boolean target 

---

custom_model_runner/datarobot_drum/drum/memory_monitor.py
custom_model_runner/datarobot_drum/drum/perf_testing.py

o Removing container columns from perf-test when not running inside
container
o Adding max used memory to print the maximum used memory inside the
container. This value is taken from the cgroup files

[RAPTOR-3584] drum: adding max used memory when running in container

---

tests/locust/README.md
tests/locust/empty_unstructured_model/custom.py
tests/locust/scripts/start-locust-docker.sh
tests/locust/suits/predict.py
tests/locust/suits/predict_unstructured.py

Initial implementation of performance testing for DRUM using Locust. (Locust is the project Cicada is based on.)
Cicada is implemented to work closely with DR App. Drum is separate tool and we want to test it standalone, so using just Locust.
- add locustfiles that implement Locust tasks logic to make prediction requests to DRUM
- add automation script to start Locust inside the official locust docker container.

[RAPTOR-3936] add locust testing framework

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/drum.py
model_templates/training/python3_sklearn_multiclass/custom.py
tests/drum/test_inference.py
tests/drum/utils.py

if options.class_labels exists, make sure it's added to the docker command and the class-labels-file flag is not
--class-labels-file could not be used with --docker because the labels file was not mapped or replaced with --class-labels

[RAPTOR-3980] --class-labels-file should work in docker mode

---

custom_model_runner/CHANGELOG.md
custom_model_runner/requirements.txt
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
tests/drum/test_inference.py

Currently DRUM is pinned to pyarrow==0.14.1 which is the version supported by DR app, but available only for python 3.7. Which makes it impossible to install DRUM locally in other Py versions.
Solution: unpin drum pyarrow version, pin public envs pyarrow version

[RAPTOR-4033] pin pyarrow version only for DR envs

---

custom_model_runner/datarobot_drum/drum/drum.py

Noticed, that comparison always fails because version str is `drum 1.4.5`

[RAPTOR-3784] compare host and container drum versions - drop 2

---

README.md
custom_model_runner/CHANGELOG.md
custom_model_runner/README.md
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/custom/ScoringCode.java
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/custom/H2OPredictor.scala
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/custom/H2OPredictorPipeline.scala
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/drum/server.py
custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
tests/drum/test_drum_server_failures.py
tests/drum/test_inference.py
tests/drum/test_unstructured_mode.py
tests/fixtures/drop_in_model_artifacts/sklearn_reg_sparse.pkl

* Add endpoints: `predictions`/`predictionsUnstructured` - to match PPS endpoints
* Add `ping endpoint` - to match PPS endpoints
* Allow to pass data not only as form-data param, but just as binary data; when sending mtx/arrow as binary data - mimetype should be set to `text/mtx`/`text/arrow`.
* when data is passed as binary data, we won't have saved file, so `read_input_data` receives data as bytes.
* update tests to send data in all formats to all endpoints
* Most of this is required for PPS.

[RAPTOR-4030] add support for receiving regular binary data for /predict endpoint

---

custom_model_runner/datarobot_drum/drum/model_adapter.py
tests/drum/test_units.py

`None` and `numpy.nan` values after serializing to CSV and deserializing become `numpy.nan`.
`None` and `numpy.nan` values after serializing to Arrow and deserializing become `numpy.nan` for numerical columns and `None` for object columns.
Since we support both CSV and Arrow, NA values handling should be consistent.
(+ some existing models don't expect `None`, because with CSV it's always `numpy.nan`).

[RAPTOR-4154, RAPTOR-4158] Handle NA values in Arrow consistently to CSV

---

README.md
custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/custom/ScoringCode.java
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/custom/H2OPredictor.scala
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/drum/utils.py
custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
custom_model_runner/datarobot_drum/resource/templates/custom_python_template.py.j2
custom_model_runner/datarobot_drum/resource/templates/custom_r_template.R.j2
tests/drum/test_units.py
tests/fixtures/all_predict_structured_hooks_custom.R
tests/fixtures/all_predict_structured_hooks_custom.py
tests/fixtures/custom_pred_consistency/custom.py

Currently DRUM predictors (internals and hooks) receive data as either file or bytes.
Make it receiving bytes only. e.i. if file is detected, read it as binary and pass bytes further into predictor.

[RAPTOR-4183] refactoring: read input data as binary and pass into predictor

---

custom_model_runner/datarobot_drum/resource/templates/custom_python_template.py.j2
custom_model_runner/datarobot_drum/resource/templates/custom_r_template.R.j2

[RAPTOR-3552] Align parameter names in model templates with docs

---

custom_model_runner/setup.py

Limit DRUM supported Py versions to >=3.4,<=3.8
Pyarrow fails to be installed in Py3.9.
To move forward with supported Py version we need to add a test that installs drum under different Python's.
Probably we can use  `tox`.
https://datarobot.atlassian.net/browse/RAPTOR-4230

[RAPTOR-3916] make drum require Python >=3.4,<=3.8

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
custom_model_runner/datarobot_drum/resource/transform_helpers.py
tests/drum/test_inference.py

As the name suggests; our y format is different from X format in the case of sparse data, so need to pass that info back. We also don't have colnames for mtx matrices, so need to pass them separately as a csv for sparse output.

[RAPTOR-4423] Return colnames for sparse transform server; return both X and y format in payload

---

custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/utils.py
custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
tests/drum/test_fit.py

We no longer sample data with replacement. I mistakenly thought that sampling with replacement would only happen if the asked for sample was larger than data length which is not the case. This confused CFDSes greatly when their data had repeated rows in it.

[RAPTOR-4156] Sampling with replacement was confusing modelers

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/description.py

Bump up default DRUM perf test timeout to 600s
Make it match the App timeout

[RAPTOR-4563] Bump up default DRUM perf test timeout to 600s

---

custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/push.py
tests/drum/test_units.py

* added `validate_config_fields(config, *fields)` which checks if provided fields present in config
* make validation and environmentId fields optional and use `validate_config_fields` to ensure fields present according to functionality
* added `customPredictor` section. It can contain any data that user plans to add and parse on his own. DRUM doesn't use this field, but it has to be defined to make DRUM not fail when it present.
Current YAML parsing schema for model-metadata.yaml treats `validation`, `environmentId` fields as mandatory which is relevant only for `drum push` feature. In general, required fields should be checked according to functionality.

[RAPTOR-4593] refactor YAML schema for model-metadata.yaml

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/start_server.sh
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/start_server.sh
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/start_server.sh
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/start_server.sh
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/start_server.sh
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/start_server.sh
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/start_server.sh

Pass parameters from start_server.sh to DRUM
Mainly it is needed when starting env docker image. 
For example, when container should be started with additional params to drum server:
`docker run -ti env_image --help`
`docker run -ti env_image --production`

[RAPTOR-4132] pass start_server.sh arguments to DRUM

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
tests/drum/test_inference.py

Implement `/info` endpoint:
Response is smth like that:
```
{
"DRUM server": "flask",
"DRUM version": "1.4.15",
"code_dir": "/home/yakov.goldberg/workspace/datarobot-user-models/model_templates/inference/python3_sklearn",
"language": "python",
"model metadata": {
"environmentID": "5e8c889607389fe0f466c72d",
"inferenceModel": {
"targetName": "MEDV"
},
"modelID": "5f1f15a4d6111f01cb7f91fd",
"name": "drumpush-regression",
"targetType": "regression",
"type": "inference",
"validation": {
"input": "../../../tests/testdata/boston_housing.csv"
}
},
"predictor": "scikit-learn",
"target_type": "regression"
}
```

[RAPTOR-4726] implement /info endpoint

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/runtime.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
tests/drum/test_drum_docker.py
tests/fixtures/cmrun_docker_env/Dockerfile

* show progress spinner while building docker image (when provide context folder to --docker)
* fix:  always unset `entrypoint` when we run DRUM in a container

[RAPTOR-3911] show progress spinner when building a docker image, release v1.4.16

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/drum/BasePredictor.java
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/drum/ScoringCode.java
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/drum/H2OPredictor.scala
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/drum/H2OPredictorPipeline.scala
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
tests/drum/custom_java_predictor/src/main/java/com/datarobot/test/TestCustomPredictor.java
tests/drum/test_units.py

Performance degradation investigation happened because DRUM changed the way how data is passed from Py to Java via py4j.
Before the change, incoming data was saved as a CSV file, file name was passed into predictor, and predictor read the file.
I changed this to directly pass the incoming data array into the predictor.
As we saw in the validation results, Py and R improved some performance, while Java gained some improved performance on the small data, but lost on the big chunks. (I confirmed that by switching back to files).
Implement hybrid approach where chunks of up to 33K will be sent directly as array, while bigger chunks will be saved into temp file.

[RAPTOR-4830] refactor data transfer from py to java via py4j

---

custom_model_runner/datarobot_drum/drum/common.py

Custom training models will be getting hyperparameter support in 7.1 via supplying it in the model-metadata YAML.
This PR allows the field. We will make it more specific once we add param validation in DRUM.

[RAPTOR-4967] Add parameters to DRUM metadata schema

---

custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/push.py
tests/drum/test_units.py

Make targetName field in model config optional, but validate it in the push method

[RAPTOR-4897] make targetName field in model config optional

---

custom_model_runner/datarobot_drum/drum/common.py

Custom training models will be getting support for input type validation in 7.1.  The specification will be provided through the model-metatdata YAML file.  This adds that field for future use.

[RAPTOR-4975] add validation parameter to mode-metadata.yaml

---

custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/drum/BasePredictor.java
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/drum/ScoringCode.java
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/drum/H2OPredictor.scala
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/drum/H2OPredictorPipeline.scala
tests/drum/custom_java_predictor/src/main/java/com/datarobot/test/TestCustomPredictor.java

Make configure() method abstract to make developer implement it in their code.
Fix signature in the Scala code: Java Object type has to be mapped to AnyRef type in Scala.

[RAPTOR-4478] cleanup BasePredictor: add abstract configure() method

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/push.py
tests/drum/test_inference.py
tests/drum/test_units.py

Binary and multiclass labels can be provided as CLI parameters or in metadata yaml. Eventually labels from yaml has never been plumbed through.
In this patch I resolve parameters if they are provided in CLI, yaml, or both, add testcases and do some clean up, like:
- require yaml  for PUSH mode
- don't resolve labels for FIT
- remove class labels CLI arguments from push and fit parsers, etc.
Sorry if PR is a bit long and cumbersome

[RAPTOR-4897] early detection of missing labels for binary/multiclass

---

docker/drum_integration_tests_base/Dockerfile
tests/drum/test_performance_check.py

As this container has been moved to use python from sources, it requires to libsqlite to be installed.

[RAPTOR-5197] update DRUM test container, add support for Julia - drop 2

---

custom_model_runner/README.md
custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
custom_model_runner/datarobot_drum/resource/drum_server_utils.py

Propagates --verbose to the drum server when performing `drum fit`.
This should help with local debugging
- Fix readme path
- Propagate verbose
- Add code to disable flask server banner, which is:
```
* Serving Flask app "datarobot_drum.drum.server" (lazy loading)
* Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
* Debug mode: off
```
Transform
Predict

[RAPTOR-5021] Show predict logs during drum fit when verbose is set to true

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/drum/ScoringCode.java
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/drum/perf_testing.py
tests/drum/test_inference.py
tests/drum/test_units.py
tests/drum/test_validation_check.py

Enable validation that  classification probabilities sum up to 1 during predict, into the common code in DRUM, so that validation works for all the predictors, on every predict.

[RAPTOR-5277,5301] validate classification predictions add up to one for all the predictors

---

custom_model_runner/datarobot_drum/drum/drum.py

missed updating `raise_mulitple_custom_files` function when adding julia inference support

[YOLO] fix raise_multiple_custom_files function - add arg for jl paths

---

README.md
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/typeschema_validation.py
tests/drum/test_units.py

This adds test coverage to type schema checking and then refactors type schema checking.  
The main refactoring is:
- `Fields` is responsible for supplying objects related to that field.  It gives you the revalidators (`strict_yaml.Map`) for checking a field's schema and it gives you the `BaseValidator` for validating that field's data.
- The "Enums" are now `Enum`s and have functionality to help them group things and go between enum and str.  
- The tests test from higher level code so that the internals can be ripped out and changed.
- get_type_schema_yaml_validator,
- revalidate_typeschema,
- SchemaValidator
- test_read_model_metadata_properly_casts_typeschema : this guarantees that our top function actually uses `revalidate_typeschema` and recasts the schema object as expected.
- test …

[YOLO] refactorings

---

custom_model_runner/datarobot_drum/drum/drum.py

Fix glob pattern to detect custom.r/R file
On the case insensitive filesystems, the following statement  finds `custom.r` file two times
custom_r_paths = list(Path(code_dir_abspath).rglob("{}.r".format(CUSTOM_FILE_NAME))) + list(Path(code_dir_abspath).rglob("{}.R".format(CUSTOM_FILE_NAME)))

[RAPTOR-5377] fix custom R detection

---

custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/drum/PredictorEntryPoint.java
public_dropin_environments/java_codegen/env_info.json
tests/drum/test_units.py

I was able to reproduce the error mentioned in the ticket by failing server to bind the port, thus py4j client has nothing to connect to.
So a couple of improvements are:
1. If py4j server fails to bind to a port (in PredictorEntryPoint.java), explicitly exit the program.
2. On the python side: if py4j server failed to start, print a full output.
3. I'd like to release DRUM v 1.5.6.post1 and reinstall java env, which will pull this DRUM, so we could see a proper log then it fails. (Though i think it will be a binding error, if so - i have some following steps in mind)

[RAPTOR-5369] improve error output

---

public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json

I thought version `1.5.6.post1` will be automatically pulled when version is pinned to `datarobot-drum==1.5.6`, but not.

[RAPTOR-5369] Install DRUM 1.5.6.post1 into java env

---

custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/profiler/stats_collector.py

Add total run time per test case, It can be useful , when comparing performance. It is easier to see difference in total time than in time per iteration.
size   samples   iters    min     avg     max    total   used (MB)   total physical (MB)
========================================================================================
3 KB        10     150   0.018   0.020   0.024   3.006     417.801             31442.730

[YOLO] output total run time number per test case

---

tests/functional/test_inference_model_templates.py

Disables `inference/python3_keras_vizai_joblib` test
This test requires public egress access and fails where NetworkPolicy is not ignored.

[EP-714] disable inference vizai test to support k3d

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
custom_model_runner/datarobot_drum/drum/utils.py
custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
tests/drum/test_utils.py

Previously, R errors only showed a single-line error message. This PR will run traceback() when an R runtime error occurs to print the full traceback. Additionally, does not require --verbose to show the stacktrace.

[RAPTOR-5568] Show R Traceback for fit/predict errors

---

dependbot.yml

Enabling dependbot is one of the security requirements for custom models.

[RAPTOR-5435] add dependbot configuration

---

tests/drum/unit/test_typeschema_validation.py
tests/drum/utils.py

This moves the unit tests inside the drum folder.  otherwise they don't get run.  once it is complete, you should be able to find the test in: https://jenkins.hq.datarobot.com/job/Custom_Models_Templates_CMRunner_Integration_Tests/2431/console
under tests/drum/unit
the tests were skipped before

[YOLO] moved tests

---

custom_model_runner/datarobot_drum/drum/drum.py

Adds quotes around code input path and weights input path when creating the docker command. Fixes issues with spaces in the path.

[RAPTOR-5648] Add quotes around all docker mount paths

---

custom_model_runner/datarobot_drum/drum/typeschema_validation.py
tests/drum/unit/test_typeschema_validation.py

This fixes the use of IN to match DR

[RAPTOR-5491] fix datatypes in

---

custom_model_tutorial.ipynb
tests/functional/test_drop_in_environments.py

custom model images are deprecated. don't use them.

[RAPTOR-5760] do not use deprecated custom model images in tests

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/env_info.json
tests/drum/test_units.py

py4j server doesn't have ping/health methods,
thus add retries in a way recommended by maintainer.
Release the fix right away.
py4j server is started as a separate process in current python script. So it is required to wait and ensure server is started.

[RAPTOR-5369] improve py4j gateway connection errors handling, release v1.5.8

---

MODEL-METADATA.md
VALIDATION-SCHEMA.md
custom_model_runner/datarobot_drum/drum/typeschema_validation.py
tests/drum/unit/test_typeschema_validation.py

This is to match the validation used in DR for the schema.  NO runtime validation in DRUM is supported for some types, such as audio, at this time.

[RAPTOR-5540] support all datatypes

---

custom_model_runner/requirements.txt

Constraining pandas version in cm_runner `requirements.txt`.
Resolve pip install issues in CI tests.

[BUILD-2410] Fix pandas version constraints

---

MODEL-METADATA.md
custom_model_runner/datarobot_drum/drum/typeschema_validation.py
tests/drum/unit/test_typeschema_validation.py

Audio and target only are not available in blueprint workshop and are being removed.

[RAPTOR-6036] remove types that are not supported in blueprint workshop

---

jenkins/test3_mlpiper_custom_models.sh
tests/fixtures/cmrun_docker_env/Dockerfile

Remove an ls from the dockerfile used to run tests.  The ls runs into permission issues in the jenkins environment, however access to files in /tmp is ok.  This allows the build to proceed correctly so that tests can be run.

[YOLO] remove unnecessary ls in dockerfile

---

BRANCHING.yaml

add BRANCHING.yaml so that we automatically build the environment installer during release branch cut

[RAPTOR-6115] add BRANCHING.yaml to run the installer build job for release

---

README.md

I removed the section but forgot to update the hyperlink at the beginning

RAPTOR-6038 removing dead hyperlink from top level readme

---

custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
tests/fixtures/r_transform_fit_custom_non_numeric.R

Testing the recent R sparse changes on staging, I found there was an off-by-one error.
This made me realize and fix two things:
1. If the last row in the R sparse matrix is all zeroes, it will be dropped when creating it in python
2. R indices are 1-based, python is 0-based, so we need to translate
This PR fixes both those issues. No new tests are added because the fix for (1), passing the number of rows and cols back, makes tests fail unless we implement (2) because without it, the last row would be out of range
In addition, checks are added to make sure number of input rows matches output rows

[RAPTOR-6306] R Sparse Transforms: fix off-by-one error

---

task_templates/transforms/python3_image_transform/README.md
task_templates/transforms/python3_image_transform/img_utils.py

Update the image utilities in the image transform template to output strings instead of bytes.  Bytes caused an issue now that validation of transform output is running where images were failing to load and being counted as categorical.

[YOLO] output string instead of bytes in img template

---

custom_model_runner/CHANGELOG.md
custom_model_runner/README.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

DRUM v1.5.12 has been compiled with Java 13, but public java env has Java 11 installed.
I'm going to push DRUM 1.5.13 to PyPI and update envs.

Release DRUM v1.5.13

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py

Take labels from the resulting predictions dataframe, so they always will be in the same order with the values.
Tested manually with CM PPS.
special thanks to @timsetsfire

[RAPTOR-6399] fix the order of class labels reported to MLOps monitoring

---

custom_model_runner/CHANGELOG.md
custom_model_runner/README.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/resource_monitor.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
custom_model_runner/drum_server_api.yaml
tests/drum/test_stats.py

Refactor stats reporting, separate "drum_info" section from "mem_info", i.e.
Before, stats was an object: 
```
{
"mem_info": {
"drum_info":{},
"other_mem_info":  {}
}, 
"time_info" : {}
}
```
Now:
```
{  
"mem_info":{}, 
"drum_info": {}, 
"time_info": {}
}
```
Started to add CPU usage reporting, refactored code to reflect not only Memory Info, but Resource Info that includes mem info + cpu info.

[RAPTOR-6377] refactor stats reporting

---

DEFINE-INFERENCE-MODEL.md
README.md
model_templates/README.md
public_dropin_environments/README.md
tools/image-build-utils.sh

Updating existing readme files and adding additional in child folders
The original README was too large. We are logically splitting it up into different files and removing content that is best served with a link instead.

[RAPTOR-5561] Refine readme in DRUM repo stage 1

---

custom_model_runner/CHANGELOG.md
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
tests/drum/run-drum-tests-in-container.sh
tools/image-build-utils.sh

Release v1.5.15
THere was a glitch with 1.5.14 release.
Two days ago I mistakenly published 1.5.14 and didn't remove it.
So when @scottp-ml pushed 1.5.14 to pypi it was already there, so it hasn't been replaced. And, as I noticed, twine doesn't always show an error message, that file already exists, like here:
https://jenkins.hq.datarobot.com/job/Release_DRUM_PyPI_TEST/21/console
```
16:22:43 NOTE: Try --verbose to see response content.
16:22:43 HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
16:22:43 File already exists. See https://pypi.org/help/#file-name-reuse for more information.
16:22:43 + handle_exit
16:22:43 + ec=1
```
I'm going to release 1.5.15, update env, and send out email to use DRUM publishing job.

Release v1.5.15

---

task_templates/estimators/python_anomaly/model-metadata.yaml
task_templates/estimators/python_binary_classification/model-metadata.yaml
task_templates/estimators/python_calibrator/model-metadata.yaml
task_templates/estimators/python_multiclass_classification/model-metadata.yaml
task_templates/estimators/python_regression/model-metadata.yaml
task_templates/estimators/python_regression_with_custom_class/model-metadata.yaml
task_templates/estimators/r_binary_classification/model-metadata.yaml
task_templates/estimators/r_regression/model-metadata.yaml
task_templates/pipelines/python3_anomaly_detection/model-metadata.yaml
task_templates/pipelines/python3_calibrated_anomaly_detection/model-metadata.yaml
task_templates/pipelines/python3_keras_joblib/model-metadata.yaml
task_templates/pipelines/python3_keras_vizai_joblib/model-metadata.yaml
task_templates/pipelines/python3_pytorch/model-metadata.yaml
task_templates/pipelines/python3_pytorch_multiclass/model-metadata.yaml
task_templates/pipelines/python3_sklearn_binary/model-metadata.yaml
task_templates/pipelines/python3_sklearn_binary_schema_validation/model-metadata.yaml
task_templates/pipelines/python3_sklearn_multiclass/model-metadata.yaml
task_templates/pipelines/python3_sklearn_regression/model-metadata.yaml
task_templates/pipelines/python3_sklearn_with_custom_classes/model-metadata.yaml
task_templates/pipelines/python3_sparse/model-metadata.yaml
task_templates/pipelines/python3_xgboost/model-metadata.yaml
task_templates/pipelines/r_lang/model-metadata.yaml
task_templates/transforms/custom_class_python/model-metadata.yaml
task_templates/transforms/python3_image_transform/model-metadata.yaml
task_templates/transforms/python3_sklearn_transform/model-metadata.yaml
task_templates/transforms/python_missing_values/model-metadata.yaml
task_templates/transforms/r_transform_recipe/model-metadata.yaml
task_templates/transforms/r_transform_simple/model-metadata.yaml

Adding and tweaking default metadata yaml to all transforms, estimators, and pipelines
The new model metadata example has detailed comments so users looking at the code should quickly grasp how to use it

[RAPTOR-6172] Duncan/raptor 6172/add clear schema template to tasks

---

custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/requirements.txt
tests/drum/test_args_parser.py

When such env var was defined as False, e.g.:    PRODUCTION=False, it has been treated as "defined",  
thus argument "--production" has been passed into DRUM

[RAPTOR-6439] handle defining bool args param through env var

---

custom_model_runner/datarobot_drum/resource/transform_helpers.py
tests/drum/unit/test_payload.py

For transforms, we should ensure colnames are sane and validated before we serialize
- Add validation check and conversion for both sparse and dense transform payloads
- Added unit test

[RAPTOR-6642] Validate transform colnames before serialization

---

requirements_dev.txt

it would appear that the version of the jdk we were using no longer exists

[RAPTOR-7046] Update JDK 11 version in requirements_dev.txt in DRUM repo

---

custom_model_runner/datarobot_drum/drum/enum.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
tests/drum/test_fit.py
tests/drum/test_other_cases.py
tests/functional/test_custom_task_templates.py

In this PR, the DRUM program exit code will be set to 3 when DrumSchemaValidationException is raised during the run.
**- Why**
The exit code info of DRUM is reported back in the agro-workflow log. In the DataRobot layer, it will determine the root cause of batch job execution failure (e.g., DRUM fails) based on the exit code in the agro-workflow log. This PR leverages the application specific exit code besides the standard 0 (success) and 1 (fail) and facilitates DRUM failure analysis. There is a follow-up PR in DataRobot repo to implement this in the DR layer.
**- How**
1) perf_testing.py
Update the logic in prediction server and raise DrumSchemaValidationException accordingly when schema validation fails.
2) main.py
Return the application specific exit code when …

[RAPTOR-5500] Improve pred server schema validation error handling

---

jenkins/test3_drop_in_envs.sh
jenkins/test3_inference_model_templates.sh
jenkins/test3_training_model_templates.sh
tests/functional/test_custom_task_templates.py
tests/functional/test_drum_push.py

update version of pip used by tests
the dirt old version of pip used in the functional tests are having trouble installing drum's dependencies

[RAPTOR-7113] Update version of pip used in functional tests

---

custom_model_runner/datarobot_drum/drum/data_marshalling.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/model_adapter.py
tests/conftest.py
tests/drum/test_language_predictor.py

BaseLanguagePredictor._class_labels is designed to hold multi-classification label. With the existing implementation, the BaseLanguagePredictor._class_labels will be updated even during binary classification and regression. The side effect is that the downstream logic (especially PythonPredictor.predict()) depending on the BaseLanguagePredictor._class_labels are affected. This causes functional testing failure in DR repo.
This PR fixed the logic of handling class_labels on both `BaseLanguagePredictor` and `PythonModelAdapter` levels. 
The changes in this PR were tested with the custom task functional testings of DR repo (https://github.com/datarobot/DataRobot/pull/90709). All testings pass.

[RAPTOR-7149] Improve the logic to handle class_labels

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Add a new release 1.6.3.
Why do we consider bumping a new release ?
We found the datarobot-drum dependency in DR repo custom task functional testing is out of date. We need to update it asap. The recent fix in this pr (https://github.com/datarobot/datarobot-user-models/pull/493) unblock updating the datarobot-drum dependency in DR repo. This new release will be created and referred in DR repo as the dependency.

[RAPTOR-7124] Add new release 1.6.3

---

pyproject.toml
tests/drum/run-drum-tests-in-container.sh
tests/drum/test_inference.py

Run the java predictor tests sequentially, in an attempt to avoid a pytest worker crash.
Apparently, it happens that the java predictor tests fail in a crash of a pytest worker - the whole Python engine just crash:
```
worker 'gw0' crashed while running 'tests/drum/test_inference.py::TestInference::test_custom_model_with_custom_java_predictor[regression-None]'
```
Although, it is not totally understood, in this PR there's an attempt to mitigate it by running these tests sequentially, avoiding any potential collisions.
In general, executing the tests involve in spinning up a server that listens on a dynamic selected port. When trying to run multiple tests in parallel there's a chance for port collisions. So a sequential execution might also be useful in other test cases.

[RAPTOR-7204] Run java predictor related tests sequentially

---

custom_model_runner/datarobot_drum/resource/predict_mixin.py
custom_model_runner/datarobot_drum/resource/transform_helpers.py
custom_model_runner/requirements.txt
tests/drum/test_inference.py

>Note: I haven't fixed all the logic around passing `arrow_version` argument
Properly handle pyarrow version validation. 
Get rid of unsecured `eval()` call.

[RAPTOR-7217] handle pyarrow version check in transforming

---

custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/runtime.py
custom_model_runner/datarobot_drum/resource/utils.py
tests/drum/test_args_parser.py
tests/drum/test_performance_check.py

* remove shell=True from subprocess.Popen() calls
* refactor commands represented as string into a list (or split string command with shlex.split() )

[RAPTOR-7224] refactor subprocess.Popen() to call command without shell

---

custom_model_runner/datarobot_drum/resource/predict_mixin.py
tests/drum/test_unstructured_mode.py

DRUM don't see data sent to `predictUnstructured` if user haven't specified request header explicitly (curl sends it with the `application/x-www-urlencoded`):
```
curl -i -X POST http://127.0.0.1:6788/predictUnstructured/ --data-binary @unstructured_data.txt 
```
DRUM --verbose:
```
Incoming data type:  <class 'bytes'>
Incoming data:  b''
Incoming query params:  ImmutableMultiDict([])
Model:  dummy
Incoming content type params:  {'mimetype': 'application/x-www-form-urlencoded'}
```
Use `request.get_data()` which does not tries to parse form data (see [Flask docs](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Request.get_data)).

[RAPTOR-7213] Read form data for unstructured models.

---

custom_model_runner/bin/drum

Properly wrap main call with: 
if __name__ == "__main__":
Running fit on Mac fails(probably not for everyone)  with the:
```
RuntimeError:
An attempt has been made to start a new process before the
current process has finished its bootstrapping phase.
This probably means that you are not using fork to start your
child processes and you have forgotten to use the proper idiom
in the main module:
if __name__ == '__main__':
freeze_support()
...
The "freeze_support()" line can be omitted if the program
is not going to be frozen to produce an executable.
```
Tested with the particular person who it was failing for.

[RAPTOR-7348] wrap main func with if __name__ == __main__

---

custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml

Update log4j in the drum java predictor
This updates log4j to a non-vulnerable version. While not actively exploited here, it is still concerning to continuing to use this version in these repositories.

Update log4j to non-vulnerable versions

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml
jenkins/test3_drop_in_envs.sh
jenkins/test3_inference_model_templates.sh
jenkins/test3_training_model_templates.sh

Release v1.6.2-post1

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml
tests/functional/test_custom_task_templates.py
tests/functional/test_drum_push.py

Release DRUM 1.6.2.post2 for 7.3 backporting
* backporting [RAPTOR-7113]
[RAPTOR-7113]: https://datarobot.atlassian.net/browse/RAPTOR-7113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release v1.6.2.post2

---

custom_model_runner/datarobot_drum/drum/push.py
requirements_test.txt
tests/drum/test_units.py

Use the fancy new user blueprint public api client methods instead.

[MODEL-7540] Update datarobot client, remove usage of /customTrainingBlueprints/

---

docker/drum_builder/build_docker.sh

Currently drum builder imag has been created with my user (as I was running this scripts on my laptop).
Remove using user id from image creation process.
This behavior caused that local maven repository (needed to compile some artifact) was not created in the HOME

[RAPTOR-7447] create drum build container with root user

---

custom_model_runner/Makefile
custom_model_runner/datarobot_drum/drum/enum.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/base_predictor/pom.xml
tests/drum/custom_java_predictor/pom.xml
tests/drum/run-drum-tests-in-container.sh
tests/drum/test_units.py

com.datarobot.drum-base-predictor has been published to Maven repo.

[RAPTOR-7458] don't install drum-base-predictor locally for test/build purposes

---

custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/utils.py
custom_model_runner/datarobot_drum/resource/components/Python/python_fit/python_fit.py
custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
custom_model_runner/datarobot_drum/resource/pipelines/python_fit.json.j2
custom_model_runner/datarobot_drum/resource/pipelines/r_fit.json.j2
tests/drum/test_units.py
tests/testdata/hyperparameters/model-metadata-no-hyperparameter.yaml
tests/testdata/hyperparameters/model-metadata.yaml

The `parameterFile` argument of drum is used to indicate the file of task hyper-parameter values. When the `parameterFile` is not specified, the task hyper-parameter values won't be set. With the changes of this PR, the task hyper-parameter values will be initialized with the default values from model-metadata.yaml (if 'hyperparameters' section is available) if `parameterFile` drum argument is not specified.

[RAPTOR-6049] Initialize default task parameter values with hyperparameters in model metadata config

---

custom_model_runner/datarobot_drum/drum/drum.py
tests/drum/test_fit.py

If a user sets the output dir the same as code-dir there is an error during fit that is not obvious to the user.  This change catches the issue earlier and provides a more actionable and obvious error message.  It does not make sense to allow users to use the code-dir as the output since the contents of code-dir will be copied to the output.  It is intended to create a custom model like package with the serialized model.

[MODEL-7700] code dir cannot be the same as output dir for fit

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/datarobot_drum/drum/runtime.py
custom_model_runner/datarobot_drum/drum/server.py
custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
custom_model_runner/datarobot_drum/resource/utils.py
custom_model_runner/requirements.txt
requirements_test.txt
tests/drum/test_mlops_monitoring.py
tests/drum/utils.py
tests/fixtures/unstructured_custom_mlops.py

In the context of [PBMP-4446 ](https://datarobot.atlassian.net/browse/PBMP-4446), it is required to gracefully shutdown the MLOps library in order to make sure that all the statistics were completely sent to DataRobot. 
* Add support for `terminate` hook upon drum termination in server mode, in host & docker environments.
* Add support for `terminate` callback in prediction server component
* Bump mlpiper dependency to 2.5.0, which supports the `terminate` hook
* Add tests for server termination

[RAPTOR-7554] Gracefully shutdown MLOps upon POD's completion/termination

---

custom_model_runner/requirements.txt
public_dropin_environments/r_lang/Dockerfile

- Make R evn to use Python 3.7 instead of 3.6
- unpin pyarrow dep in DRUM, so env defined version of pyarrow will be used

[RAPTOR-7654] move R environment to use Python 3.7

---

custom_model_runner/datarobot_drum/drum/drum.py
tests/drum/test_drum_docker.py

When a min/max version is specified in a tasks requirements.txt it causes an error when passed into the pip command in the docker image.  We run that directly instead of passing in a requirements.txt.  By wrapping the requirements in quotes it avoids the issue where sh looks for a file with a name after the comma.  For example `some_lib>=1.1,2` is valid, but fails if you run `pip install some_lib>=1.1,2`.  It needs to be` pip install "some_lib>=1.1,2"`

[MODEL-7755] handle min/max versions when running pip install for a docker image

---

MODEL-METADATA.md
VALIDATION-SCHEMA.md

The documentation in MODEL-METADATA.md was incomplete.  This fixes that issue and adds a link to the detailed documentation for the validation schema.

[MODEL-8112] updates to validation schema documentation

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py

Don't include default drum java predictors into java classpath when working with custom predictor.
Our default predictors depend on older packages and it may cause dep conflict.
Release v1.7.2dev1 to be able to pull artifact for easier development process

[RAPTOR-7711] don't include default drum java predictors into java classpath when working with custom predictor

---

custom_model_runner/datarobot_drum/drum/utils.py
tests/drum/unit/test_shared_fit_preprocessing.py

When reading CSV input files, we should treat blank lines as NaNs instead of skipping over them. This does not include the last newline.
- set skip_blank_lines = False when only 1 col is read
- unit test
- use existing CSV reading code in shared_fit_preprocessing

[MODEL-7979] Treat single col blank values as NAN in CSVs

---

custom_model_runner/requirements.txt

Update in markupsafe in 2.1.0 breaks an API used by jinja2. Pinning markupsafe until jinja2 is updated.

[RAPTOR-7723] Pin markupsafe

---

custom_model_runner/datarobot_drum/drum/artifact_predictors/artifact_predictor.py
custom_model_runner/datarobot_drum/drum/custom_tasks/fit_adapters/python/python_fit_adapter.py
custom_model_runner/datarobot_drum/drum/custom_tasks/fit_adapters/r/r_fit_adapter.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/drum/utils/drum_utils.py
custom_model_runner/datarobot_drum/drum/utils/stacktraces.py
custom_model_runner/datarobot_drum/drum/utils/structured_input_read_utils.py
custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
custom_model_runner/datarobot_drum/resource/drum_server_utils.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
tests/drum/test_deployment_config.py
tests/drum/test_fit.py
tests/drum/test_inference.py
tests/drum/test_stats.py
tests/drum/unit/test_args_parser.py
tests/drum/unit/test_structured_input_read_utils.py
tests/drum/unit/test_utils.py

Breaks apart the utils file into multiple files. No code added or removed, just moved.

[MODEL-8479] [Refactor] Move drum utils into separate files

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/requirements.txt
custom_model_runner/setup.py

Enable DRUM availability for Py 3.9 as per CFDSs request.
Bumped a minimal number of packages to support Py 3.9
Manually tested that it is installable for Py3.9.
No current repo tests have been updated for Py 3.9 checks.

[RAPTOR-7857] release DRUM 1.9.0 supporting Py 3.9

---

custom_model_runner/datarobot_drum/drum/adapters/drum_cli_adapter.py
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
custom_model_runner/datarobot_drum/drum/model_adapter.py
custom_model_runner/datarobot_drum/drum/utils/structured_input_read_utils.py
custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
tests/drum/unit/test_drum_cli_adapter.py

This PR adds DrumCLIAdapter into the MLPiper drum score component for structured predicts. This helps consolidate how we read sparse column names to a single place. This makes it so we can pass down the sparse column names list instead of the binary data into the predictor. Drum server locations are updated to do the same.
The end-goal is to consolidate all shared logic between fit, score, and predict (both flask and werkzeug) to a single place, and to make the entrypoints to PythonModelAdapter/RModelAdapter take in dataframes/lists/etc instead of binary data. This will allow us to...
- Call predict without MLPiper / drum server
- Make drum importable as a module, and have users run fit/predict without using the CLI within their jupyter notebooks
- Pass dataframes to their tasks to …

[MODEL-8517] Use DrumCLIAdapter for drum score

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Bump the version of DRUM to 1.9.3 to include fit metadata reports.

[MODEL-9047] bump version

---

model_templates/java_unstructured/pom.xml
tests/drum/custom_java_predictor/pom.xml

Package is used in tests and model templates, not in the DRUM's critical code.

[RAPTOR-8060] bump java jackson packages to 2.13.3

---

tests/drum/custom_java_predictor/pom.xml
tests/drum/run-drum-tests-in-container.sh

- bump a missed dependency
- fix script to take into account all the runs of pytest

[RAPTOR-8060] bump java jackson packages to 2.13.3 - drop 2

---

custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/typeschema_validation.py
tests/drum/unit/model_metadata/test_model_metadata.py

Make sure that users are given actionable info when the typeschema is not valid.  For anything other than transforms output schema is not allowed, however the user was never given a clear message with how we handle the exception in fit.

[MODEL-9340]

---

Jenkinsfile
jenkins/black_check.groovy
jenkins/build_drum.groovy
jenkins/run_integration_tests_in_a_single_container.groovy
pipelineController.yaml
tests/drum/run-drum-tests-in-container.sh

The ultimate goal is to split integration tests that run in a single huge container to run in the containers per framework.
Java cases in java container, R in R container, etc.
As `jenkins-jobs` become obsolete, these tests will be organized using pipeline controller.
Current PR adds a required boilerplate code and duplicates cmrunner_integration tests as a pipline:
black->build_drum_wheel->integration_tests
check details for the `continuous-integration/jenkins/pr-merge` task
> NOTE: There are some debugging printouts still present.

[RAPTOR-8182] introduce pipeline controller boilerplate 

---

task_templates/3_pipelines/14_python3_keras_joblib/custom.py
task_templates/3_pipelines/15_python3_keras_vizai_joblib/model_utils.py

When DR passes class labels they are represented as strings, even though the classes may be floats or ints, or strings for raw.  Label_binarize does not like getting float values, so cast them all to strings so that they match up correctly.

[MODEL-7471] manage non raw target information correctly.

---

jenkins/build_drum.groovy
jenkins/run_integration_tests_without_container.groovy
jenkins/test3_drop_in_envs.sh
jenkins/test3_inference_model_templates.sh
jenkins/test3_mlpiper_custom_models_without_container.sh
jenkins/test3_training_model_templates.sh
jenkins/test_drop_in_envs.groovy
jenkins/test_inference_model_templates.groovy
jenkins/test_training_model_templates.groovy
pipelineController.yaml
tests/drum/custom_java_predictor/src/main/java/com/datarobot/test/TestCustomPredictor.java
tests/drum/run-drum-tests-in-container.sh
tests/drum/test_inference.py
tests/drum/test_inference_custom_java_predictor.py

1. Add/duplicate DRUM functional inference/training/drop_in tests in pipeline controller
2. Separate sequential and non sequential tests to run on different nodes. We had some integration tests running sequentially. Suddenly they started to flake: https://jenkins.hq.datarobot.com/job/Custom_Models_Templates_CMRunner_Integration_Tests/3781/console
As long as I plan to split all the huge integration tests into smaller pipelines, I split those test cases to run separately outside test container. 
- separated tests  `test_integration_without_container`
- for now, left as before `test_integration_in_a_single_container`
3. Cleanups in many related scripts.

[RAPTOR-8182] add more tests into pipeline controller boilerplate

---

README.md

Fixes broken doc links which point to some preview content.
Now point to proper documentation.
Links in the README.md are broken.

Fixes Broken Doc Links

---

public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Ran SLA manually, it passed: https://ci1.devinfra.drdev.io/job/Custom_Models_drop_in_environment_tests/808/

[RAPTOR-8348] bump pandas version for R env

---

task_templates/2_estimators/11_python_huggingface_vit/custom.py
task_templates/2_estimators/11_python_huggingface_vit/model-metadata.yaml
task_templates/2_estimators/11_python_huggingface_vit/requirements.txt
task_templates/2_estimators/1_python_regression/custom.py

This adds epochs as a tunable hyperparameter for the ViT template.  Also I removed some unused imports from other templates.

[MODEL-9648] ViT epochs as hyperparameter

---

model_templates/java_unstructured/pom.xml
tests/drum/custom_java_predictor/pom.xml

Need to backport this patch into release/8.0 branch.
There are only changes in the test and example artifacts

[RAPTOR-8060] bump java jackson packages to 2.13.3 (#627)

---

custom_model_runner/datarobot_drum/drum/typeschema_validation.py
task_templates/2_estimators/4_python_binary_classification/custom.py
task_templates/2_estimators/6_python_multiclass_classification/custom.py
task_templates/2_estimators/7_python_anomaly/custom.py
task_templates/2_estimators/9_python_regression_with_custom_class/custom.py
tests/drum/unit/model_metadata/test_model_metadata.py
tests/functional/test_custom_task_templates.py

This allows integer values to be treated as categorical.  This happens in custom tasks when date derived features are used, which are passed along the categorical edge, but are integers.  
Additional change is to remove some unused numpy imports from task templates.

[MODEL-7482] support integer values as categorical values

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py

Printing debug or info in the predict step doesn't make it to the logs properly unless stdout is flushed.  This adds a simple utility to the interface class so that it is properly handled for the user and they don't need to know that detail.  This should make debugging tasks easier for users.

[MODEL-9684] log method added to custom task interface

---

custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
custom_model_runner/requirements.txt
custom_model_runner/setup.py
docker/dropin_env_base/Dockerfile
docker/drum_integration_tests_base/Dockerfile
jenkins/test3_mlpiper_custom_models_without_container.sh
requirements_test.txt
tests/drum/run-drum-tests-in-container.sh

This PR makes the logging method for the custom task interface static.  It also fixes issues related to version pinning and the install of the mlops package causing tests to fail due to package install issues.

[MODEL-9736] static logging method

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/typeschema_validation.py
tests/drum/unit/model_metadata/test_model_metadata.py

The typeschema never took into account the possibility of missing values in image datasets.  This addresses the issue by checking for nan values, which is what is provided by DataRobot in this case.

[MODEL-9671] Fix missing image values in the typeschema

---

docker/dropin_env_base/Dockerfile
docker/dropin_env_base/README.md
docker/dropin_env_base/build_image.sh
docker/dropin_env_base/requirements.txt
docker/dropin_env_base_jdk/Dockerfile
docker/dropin_env_base_jdk/README.md
docker/dropin_env_base_jdk/build_image.sh
docker/dropin_env_base_jdk/requirements.txt
docker/dropin_env_base_r/Dockerfile
docker/dropin_env_base_r/README.md
docker/dropin_env_base_r/build_image.sh
docker/dropin_env_base_r/requirements.txt
public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_pmml/Dockerfile
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_xgboost/Dockerfile
public_dropin_environments/r_lang/Dockerfile
tests/drum/test_inference.py
tests/drum/test_inference_per_framework.py
tools/image-build-utils.sh

Move a couple of test cases to be run in a dedicated env. 
Some of these test cases include `nginx + uwsgi` testing, thus I had to:
- update base environments to have `python3-dev` package. (Also pinned `DRUM` to  `v1.9.8`). Base envs pushed to docker hub.
- update public envs to use updated base envs.
- install `uwsgi` into all the envs during the tests.
- finally, the ultimate purpose of this PR, move some test cases from running in a single container to per framework env.

[RAPTOR-8303] move more test cases to be run per environment - drop 1/many

---

example_dropin_environments/julia_mlj/start_server.sh
public_dropin_environments/java_codegen/start_server.sh
public_dropin_environments/python3_keras/start_server.sh
public_dropin_environments/python3_onnx/start_server.sh
public_dropin_environments/python3_pmml/start_server.sh
public_dropin_environments/python3_pytorch/start_server.sh
public_dropin_environments/python3_sklearn/start_server.sh
public_dropin_environments/python3_xgboost/start_server.sh
public_dropin_environments/r_lang/start_server.sh

Only print environment variables if `ENABLE_CUSTOM_MODEL_RUNTIME_ENV_DUMP` is set.

[RAPTOR-8364] Check env var before printing env dump

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/predictors/pom.xml

Very old scoring code version 2.1.6 is used in DRUM.
I’m working on POC to support explanations for the scoring code models. It requires datarobot-prediction package 2.2.1

[RAPTOR-8480] bump datarobot-prediction java lib to 2.2.1

---

custom_model_runner/CHANGELOG.md
custom_model_runner/requirements.txt
custom_model_runner/setup.py
requirements_test.txt

The same as
https://github.com/datarobot/datarobot-user-models/pull/695
But pin `datarobot==2.28.1` and `datarobot-bp-workshop==0.2.5`(used only in tests)

[RAPTOR-8618] pin dr==2.28.1

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
jenkins/test3_mlpiper_custom_models_without_container.sh
tests/drum/run-drum-tests-in-container.sh
tests/drum/test_inference_custom_java_predictor.py
tests/drum/test_mlops_monitoring.py
tests/drum/unit/test_args_parser.py

Pass dir/spooler_type params to the embedded mlops monitor. They are optional now, but will be enforced starting 8.2.X (or whatever version is released next into PyPi)

[RAPTOR-7748] pass dir/spooler_type params to the embedded mlops monitor, release v1.9.10

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/predictors/pom.xml
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/py4j_entrypoint/pom.xml
custom_model_runner/requirements.txt
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
tests/drum/custom_java_predictor/pom.xml
tests/drum/custom_java_predictor/src/main/java/com/datarobot/test/TestCustomPredictor.java

- Bump mlpiper to 2.6.0 version with fixed log4j
- bump log4j to 2.19.0
- add example on log4j custom logger init
- update envs

[RAPTOR-8728] bump mlpiper, log4j, release 1.9.13

---

custom_model_runner/datarobot_drum/drum/runtime.py

Even if the --verbose flag is enabled in DRUM whenever there is a failure the message suggests adding the --verbose flag.

[RAPTOR-8100] Upon an error do not ask for verbose flag in case it is provided

---

docker/dropin_env_base/Dockerfile
docker/dropin_env_base/build_image.sh
docker/dropin_env_base/pom.xml
jenkins/test_integration_general.sh

In the attempt to remove the agent jar from MLOps python wheel we modify how DRUM gets the agent JAR and export its path for its embedded use case

[AGENT-3741] Download Agent JAR from public repository

---

DEFINE-INFERENCE-MODEL.md
custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/enum.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
model_templates/python3_unstructured/README.md
model_templates/python3_unstructured/custom.py
tests/drum/test_unstructured_mode_per_framework.py
tests/fixtures/unstructured_custom.py

Pass request headers into the score_unstructured() hook.
DRUM takes care for getting data out of request and passing it into the hook.
But some cases (e.g. sending multipart form data) require user to parse form data by himself. This requires access to the request headers (as can be seen from the example)
We already pass query params, (it is strange we didn't pas headers from the very beginning)

[RAPTOR-8817] pass request headers into score_unstructured hook

---

custom_model_runner/README.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/enum.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/datarobot_drum/runtime_parameters/exceptions.py
custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters_schema.py
tests/drum/test_runtime_parameters.py
tests/drum/unit/test_runtime_parameters.py

As part of the custom models runtime parameters project, it is require to be able to read runtime parameters from a file, for testing and debug purposes in a local development environment.
* Add new command line option to provide a runtime parameters file as input.
* Set corresponding runtime parameters in the environment.
* Tests

[RAPTOR-3939] Add support to read runtime parameters from a file

---

requirements_test.txt

The new `dr-usertool` release does not longer support the `--api-token` input argument. In order to immediately fix it, it is required to pin the proper version for this tool.

[RAPTOR-8996] Pin the dr-usertool to release 0.5.18, which supports --api-token input arg

---

custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py

Adds a _default_ value to `RuntimeParameters.get()`. Also bumps the version of the package to a dev version in preparation for release.
Similar to the dict.get() method, I think it can be useful to have a mode that doesn't raise but instead allows a user to specify a default. The usecase I imagine is with credentials that may not always be required so a `RuntimeParameters.get('API_KEY', None)` call could be used.

[AGENT-3993] Update RuntimeParameters.get() to support default val

---

jenkins/test_integration_general.groovy
jenkins/test_integration_per_framework.groovy
pipelineController.yaml

For unknown reason integration general tests fail if started together with java tests.
Run java tests first as this is quite a short job, and afterwards all the others.
There also some cleanups in the PR, but main change is - phases

[RAPTOR-8801] change test jobs run order (phases)

---

custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/enum.py
custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
custom_model_runner/requirements.txt
custom_model_runner/setup.py
tests/drum/unit/test_runtime_parameters.py

Update the way `setup.py` imports code from the target module to only import the modules directly needed. Also fix the schema for the `model-metadata.yaml` file to support runtime parameters. Finally, make sure production code uses `strictyaml` as that is used elsewhere and since we don't directly require pyaml, we can't rely on it being installed.
The root module of the `datarobot_drum` package now imports `RuntimeParameters` class which requires `trafaret` and `strictyaml` but it seems like a waste to list those as `setup_requires` when instead we can just make the setup script more stand-alone.

[AGENT-4009] Fix some bugs found during testing RuntimeParams

---

custom_model_runner/datarobot_drum/drum/runtime.py
tests/drum/test_drum_docker.py
tests/drum/test_drum_server_failures.py
tests/drum/test_fit_per_framework.py

Currently, an exception in a custom model that happens when creating a deployment is not displayed in the deployment’s logs. With this PR, an exception during a model loading will be printed as error, whatsoever and consequently can be seen in the deployment's error logs in the UI.

[RAPTOR-8948] Exception in a custom model is not properly displayed in the UI

---

custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/enum.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters_schema.py
tests/drum/test_runtime_parameters.py
tests/drum/unit/test_runtime_parameters.py

- Bump version to 1.10.0rc1
- No longer convert credential values to snake_case
- Remove fallback argument from `get()`
- Make sure all defined params have env var injected
This change makes the local exprience more in line with the behavior when run in the MLOps custom model infrastructure:
- we no longer snake_case the credentials payload so we shouldn't do that locally either
- we no longer omit params that have a `None` value so it is pointless to have a fallback in the `get()` function
- we now will utilize the default value from the definition when running locally if no value exists in the values file

[AGENT-4034] Improve how we inject runtime params during local testing

---

custom_model_runner/datarobot_drum/drum/description.py

Eventually missed changing the version param itself.

[RAPTOR-9073] set drum version to 1.10.0

---

custom_model_runner/datarobot_drum/drum/typeschema_validation.py

A debugging print statement was mistakenly left.  This removes it to avoid confusing output from schema validation.

[MODEL-10997]remove debugging print

---

custom_task_tutorial.ipynb
tests/drum/unit/model_metadata/test_model_metadata.py
tests/drum/utils.py
tests/functional/test_custom_task_templates.py

This updates tests that use the datarobot python client to use the latest method to run the project.  The old method `set_target` has been deprecated.

[MODEL-11001]update from deprecated method

---

model_templates/README.md
model_templates/proxy_model_azureml/README.md
model_templates/proxy_model_azureml/custom.py
model_templates/proxy_model_azureml/model-metadata.yaml
model_templates/proxy_model_azureml/requirements.txt
model_templates/proxy_model_datarobot/README.md
model_templates/proxy_model_datarobot/custom.py
model_templates/proxy_model_datarobot/model-metadata.yaml
model_templates/proxy_model_datarobot/requirements.txt
model_templates/python3_sklearn_runtime_params/README.md
model_templates/python3_sklearn_runtime_params/custom.py
model_templates/python3_sklearn_runtime_params/model-metadata.yaml
model_templates/python3_sklearn_runtime_params/requirements.txt

Adds model templates (i.e. examples) for proxy models and runtime params
- Adds proxy model example for AzureML
- Adds proxy model example for DataRobot deployments
- Adds example for using runtime parameters in a traditional custom model.
Proxy models are higly reusable so it is nice to have the code in a public repo that others can simply import. It also helps show fully functional examples of how to use proxy models and runtime parameters.

[AGENT-4050] Add samples for proxy models

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/requirements.txt
example_dropin_environments/julia_mlj/dr_requirements.txt
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/r_lang/dr_requirements.txt

I had a meeting with a customer who uses Mac M1 - ARM based laptops. So they need public environment image built for ARM.
We need to support AMD/ARM arch for our base images.
I succeeded to build such an image, https://hub.docker.com/layers/datarobot/dropin-env-base/debian11-py3.9-jre11.0.16-drum1.10.1.rc1-mlops8.2.7-multiplatform-test/images/sha256-b072ee076a076c0f9468850ba0ae86ccd8c4bd67e764a950bc35380c7b376750?context=repo
Though I had a problem with previously constrained pyarrow <= 3.0.0 - was not able to build ARM image with pyarrow <=3.0.
So i decided to bump it to <=10.0.1 (not 11 as it conflicts with tensorflow). 
I bumped in both DRUM and envs.  Constraint in DRUM is what important to build the base image.
If tighter constrains are needed they can be done in env, while DRUM will …

[RAPTOR-9199] update pyarrow to <=10.0.1

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/model_metadata.py
custom_model_runner/requirements.txt
custom_model_runner/setup.py
example_dropin_environments/julia_mlj/dr_requirements.txt
example_dropin_environments/julia_mlj/env_info.json
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
tests/drum/test_runtime_parameters.py
tests/drum/unit/model_metadata/test_model_metadata_hyperparameters.py

The main changes are:
* bump DRUM support for Python 3.10
* bump deps: datarobot==3.1.0, pyarrow<=10.0.1, pandas<1.4.0, rpy2==3.5.8
* switch to trafaret>=2.0.0,<2.2.0, update code + add tests
* update envs

[RAPTOR-9083] update DRUM deps, release DRUM 1.10.1

---

example_dropin_environments/julia_mlj/Dockerfile
public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_pmml/Dockerfile
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_xgboost/Dockerfile
public_dropin_environments/r_lang/Dockerfile

Make code dir inside environment cleaner by copying only start_server.sh/fit.sh into it.

[RAPTOR-9234] copy only start_server.sh/fit.sh into the code dir

---

tests/functional/test_drop_in_environments.py

The daily test suite fails once in a while due to the following test:
**tests.functional.test_drop_in_environments.TestDropInEnvironments.test_drop_in_environments[torch_regression_custom_model-regression_testing_data]**
The last failure was due to a client timeout after 10 minutes. Analyzing the logs, apparently it took around 7 minutes to pull the large environment image by k8s.
* Double the client timeout in a functional test to wait for a custom model testing completion, which include the the torch drop-in environment.

[RAPTOR-9230] Double the client timeout in a functional test to wait for custom model testing with torch drop-in to complete

---

custom_model_runner/requirements.txt
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_pmml/requirements.txt
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/requirements.txt
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/dr_requirements.txt
requirements.txt

Bump pandas to <= 1.5.3.
Pandas 2.0.0. have been released. 
I tried to bump to 2, but some API changes are required, so bump just to the latest 1.X.X

[RAPTOR-9286] bump pandas to <= 1.5.3

---

custom_model_runner/datarobot_drum/drum/typeschema_validation.py
tests/drum/unit/model_metadata/test_model_metadata.py

If numeric categorical columns contain NaN they are handled as floats instead of integers.  The typeschema check failed in this case.  This fixes the type schema to handle this case.

[MODEL-11392]fix issue with integer column NaN

---

tests/functional/conftest.py

Make test user email shorter to fit in the user email length limit.

[RAPTOR-9391] Fit in user email length limit in tests

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/predictors/pom.xml
custom_model_runner/requirements.txt
jenkins/black_check.groovy
jenkins/test_drop_in_envs.sh
jenkins/test_inference_model_templates.sh
jenkins/test_integration_general.groovy
jenkins/test_integration_general.sh
jenkins/test_training_model_templates.sh
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
requirements_test.txt
requirements_test_integration_general.txt

* bump werkzeug flask markupsafe deps
* switch some test scripts from quantum to a regular py venv
* prepare for 1.10.4 release

[RAPTOR-9422-9423] bump werkzeug flask markupsafe deps, release 1.10.4

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/perf_testing.py
custom_model_runner/datarobot_drum/profiler/stats_collector.py
example_dropin_environments/julia_mlj/dr_requirements.txt
jenkins/test_integration_general.sh
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/requirements.txt
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/requirements.txt
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/dr_requirements.txt
requirements.txt
requirements_test.txt

* bump scikit-learn==1.0.2 in public envs
* bump datarobot-mlops==9.0.7 in tests
* replace deprecated df.append() with pandas.concat()

[RAPTOR-9455] bump scikit-learn==1.0.2, release 1.10.5

---

public_dropin_environments/r_lang/Dockerfile
public_dropin_environments/r_lang/env_info.json
tests/fixtures/r_transform_custom_sparse_output.R

Use the latest R base image for R environment.
Had to fix custom.R:  change `Matrix(as.matrix())` to `Matrix(data.matrix())`  to make things work in test.

[RAPTOR-9468] use the latest base image for R env, fix test

---

public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt

According to the trivy report
https://jenkins2.devinfra.drdev.io/job/CodeExperience-addons/job/notebooks-jenkins_trivy_groovy/70/artifact/reports/trivy_kernel-python-3.8.html

[-] fix NBX kernel vulenrabilities for python 3.8

---

tests/drum/unit/test_runtime_parameters.py

While reviewing code, I found tests that claim to test things that they don't actually test and aren't in the code base.  so i fixed the tests.
The basic problem is that the original tests went in a `for` loop.  instead of testing each missing key in isolation, they tested an ever decreasing dict
original: 
```
payload = {
"credentialType": "s3",
"region": "us-west",
"awsAccessKeyId": "123aaa",
"awsSecretAccessKey": "3425sdd",
"awsSessionToken": "123aaa",
}
```
before first test in loop
```
payload = {
"region": "us-west",
"awsAccessKeyId": "123aaa",
"awsSecretAccessKey": "3425sdd",
"awsSessionToken": "123aaa",
}
```
then
```
payload = {
"region": "us-west",
"awsSecretAccessKey": "3425sdd",
"awsSessionToken": "123aaa",
}
```
so each loop correctly fails not because of missing key, but …

[MODEL-11933] fixed misleading tests

---

public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt

https://github.com/datarobot/datarobot-user-models/pull/793 updated the pytorch env to allow for faster deployment of common GenAI apps. This PR adds the cloudpickle dependency to allow for a seamless in-DR-notebook flow for customers (e.g. testing of custom hooks and deployment using the drx.deploy() helper

[RAPTOR-9604] update pytorch env to allow in-notebook deployment flows - drop 2

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/runtime.py
custom_model_runner/datarobot_drum/drum/server.py
custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
custom_model_runner/datarobot_drum/resource/drum_server_utils.py
custom_model_runner/drum_server_api.yaml
custom_model_runner/setup.py
tests/drum/test_drum_server_failures.py

When LRS starts, it pings `/` root endpoint. 
Currently in case of error, `/health` returns 513; while `/` returns 200, so in the case when model failed to load, LRS is still started.
@zohar-mizrahi and I decided to change response code to 513, and don't start LRS in case of error.
One more thing regarding **error server**.
@rvorobii @zohar-mizrahi 
I think we can get rid off error server. Currently if load model fails, DRUM server start aborted, exception is thrown, and error server is started instead.
Instead of exception+error server, we could simply save the error message, start DRUM server and return 513 with error message on all the endpoints.
That's how it is done for uwsgi server: (check lines 123 and 150-154)
https://github.com/datarobot/datarobot-user-models/blob/75937428f5695deb …

[RAPTOR-9609] return 513 from error server (flask) / production server (nginx+uwsgi)

---

public_dropin_environments/python3_genai/Dockerfile
public_dropin_environments/python3_genai/README.md
public_dropin_environments/python3_genai/dr_requirements.txt
public_dropin_environments/python3_genai/env_info.json
public_dropin_environments/python3_genai/fit.sh
public_dropin_environments/python3_genai/requirements.txt
public_dropin_environments/python3_genai/start_server.sh
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt

Duplicate pytorch env as a separate GenAI env.
Remove GenAI deps from Pytorch env.

[RAPTOR-9667] add Python3-GenAI public env, remove GenAi deps from pytorch env

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/requirements.txt
custom_model_runner/setup.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python3_genai/dr_requirements.txt
public_dropin_environments/python3_genai/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Release version 1.10.8. The main changes are:
- return 513 response code when model load fails
- allow DRUM to be installed on Py3.11.

[RAPTOR-9663] make DRUM to support Py 3.11, release 1.10.8

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/requirements.txt
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/python3_genai/requirements.txt
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_pmml/requirements.txt
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/requirements.txt
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/dr_requirements.txt
requirements.txt

As per GenAI team request, bump pandas limit to <=2.0.3
All the envs will still have pandas 1.5.3 by default as it is installed in the base images. 
But I checked that all the tests pass if explicitly set pandas to 2.0.3 in the envs.
@mxpoliakov

[RAPTOR-9684] bump pandas<=2.0.3

---

public_dropin_environments/python311_genai/env_info.json

I'm going to install this env only on prod, it is already installed on staging. So I'll keep the env verision id.

[RAPTOR-9815] update name of the Python 3.11 GenAi env

---

public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/setup-ssh.sh
public_dropin_notebook_environments/python38_snowflake_notebook/start_server.sh
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/setup-ssh.sh
public_dropin_notebook_environments/python39_notebook/start_server.sh
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/setup-ssh.sh
public_dropin_notebook_environments/python39_notebook_gpu/start_server.sh
public_dropin_notebook_environments/r_notebook/env_info.json
public_dropin_notebook_environments/r_notebook/setup-ssh.sh
public_dropin_notebook_environments/r_notebook/start_server.sh

Allowed to specify working directory dynamically in notebooks images.
Codespaces should have `/home/notebooks/storage/` as a working directory while standalone notebooks should stay with `/home/notebooks`.

NB-4449: Allowed to dynamically specify working directory

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/model_adapter.py

So,
the original error
https://datarobot.slack.com/archives/CCE1XB7RU/p1697809688880589?thread_ts=1697808116.835149&cid=CCE1XB7RU
says: TypeError: No constructor defined.
Which is probably error in the implementation of the exception we are trying to re-throw.
So instead of re-throwing with an alternative message,   log and re-throw the original one.
Probably I should change all the similar cases in this module.
@rvorobii @zohar-mizrahi @eric-s-s 
what do you think?

[RAPTOR-9976] clean exception handling logic

---

custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/stdout_flusher.py
requirements.txt
requirements_test.txt
tests/unit/datarobot_drum/resource/components/Python/prediction_server/test_stdout_flusher.py

…
The unit tests [in this class](https://github.com/datarobot/datarobot-user-models/blob/87907d8b4ff4082bd48378ea5b6e651e133476e1/tests/unit/datarobot_drum/resource/components/Python/prediction_server/test_stdout_flusher.py#L7) are flaky in that they wait for a thread to start in a fix time.
Make sure to wait for the related thread execution and wait for a relatively high number of seconds.

[RAPTOR-10016] DRUM: fix a potential flaky unit test concerning the stdout flusher

---

public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements-gpu.txt
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/r_notebook/Dockerfile
public_dropin_notebook_environments/r_notebook/env_info.json

These updates mirror the NBX PR (Private repo.) seen here:
https://github.com/datarobot/notebooks/pull/2714/
- Update R patch version
- Update [datarobot package](https://pypi.org/project/datarobot/) to the latest (supports python 3.11)
- Pin [cloudpickle](https://pypi.org/project/cloudpickle/) to version lower than the recent 3.0.0 that was causing issues
CC @dmytrokarpovych - hopefully this looks good to you.

[NB-4660] Bump R, datarobot and langchain - pin cloudpickle

---

custom_model_runner/setup.py

Adding URLs so [pypi page](https://pypi.org/project/datarobot-drum/) can have a little more information.
Docs here:
https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls
These will show similar to how they do for the [DR Python client](https://pypi.org/project/datarobot/):

[-] Add project URLs for source and changelog to show on pypi

---

jenkins/test_inference_model_templates.sh
jenkins/test_training_model_templates.sh
tests/functional/test_drop_in_environments.py

@Zohar Mizrahi and I reviewed tests failures
https://ci1.devinfra.drdev.io/blue/organizations/jenkins/Custom_Models_drop_in_environment_tests/activity/
and it seems like the reason is resources overloading.
We decided to remove this unstable feature impact test case, especially when it doesn't add any value.
The purpose of the tests is to make sure that environments are built and predictions can be made.

[RAPTOR-10086] remove feature impact unstable redundant test

---

tests/functional/test_drop_in_environments.py

/tests/functional/test_drop_in_environments.py - intend to test that drop in environment can make is correctly built and can make predictions. 
So testing that :
* DRUM correctly checks for multiple artifacts and fails;
* a single model target type (regression) check is enough so, check for classification is not needed.
I'll verify that there are DRUM integration tests, that check negative path in case of multiple artifacts: https://datarobot.atlassian.net/browse/RAPTOR-10097

[RAPTOR-10096] remove unstable redundant functional tests

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311_genai/dr_requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python311_genai/requirements.txt
public_dropin_environments/python39_genai/dr_requirements.txt
public_dropin_environments/python39_genai/env_info.json
public_dropin_environments/python39_genai/requirements.txt
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements-gpu.txt

Release DRUM v1.10.13, and update envs.
Also @mxpoliakov bumps `langchain` deps in this PR.

[RAPTOR-10110] release DRUM v1.10.13

---

tests/e2e/test_drop_in_environments.py

This test is unstable in DataRobot Daily Suite, reorder to put heavier envs in the beginning to figure out whether it may be resources related issue.

[RAPTOR-10131] reorder test by putting heavier envs first

---

custom_model_runner/datarobot_drum/drum/drum.py

When running drum with `--docker` option, there is a check for for drum version on the  host and in the container.
This check was broken, fix parsing.

[RAPTOR-10158] fix DRUM version check when running drum in container

---

custom_model_runner/datarobot_drum/drum/runtime.py
custom_model_runner/datarobot_drum/drum/server.py
tests/functional/test_dr_api_access.py
tests/functional/test_drum_server_failures.py

Added /ping method, because existing /ping/ method (with slash in the end) is not compatible with SageMaker.

[AGENT-5017] Add new "/ping" health check method compatible with SageMaker

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

Release DRUM v1.10.15 
In next PR, I'll update all the bases and envs themselves.

[RAPTOR-10166] release DRUM v1.10.15

---

public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/start_server.sh
public_dropin_notebook_environments/python39_notebook/Dockerfile
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/start_server.sh
public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/start_server.sh

Porting changes in notebooks python kernel from here -  https://github.com/datarobot/notebooks/pull/2914/files
1. copy dataframe extension to the working dir before start server instead of during image build to avoid override it by mounting ephemeral volume

[NB-3656] Port notebook changes

---

custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters_schema.py
model_templates/python3_sklearn_runtime_params/custom.py
model_templates/python3_sklearn_runtime_params/model-metadata.yaml
tests/functional/test_runtime_parameters.py
tests/unit/datarobot_drum/runtime_parameters/test_runtime_parameters.py

Adding new runtime parameter type numeric, this is very similar to boolean type added perviously (https://github.com/datarobot/datarobot-user-models/pull/887)
Additionally we are adding two fields specific for numeric runtime, max/min values that are optional, when provided there is a extra validation in DRUM as well in DR backend to enforce that the provided values is between the range
yaml configuration example:
```
name: runtime-params-example
type: inference
targetType: regression
runtimeParameterDefinitions:
- fieldName: number1
type: numeric
defaultValue: 0
minValue: -100
maxValue: 100
- fieldName: number2
type: numeric
defaultValue: 0
```
* Add unit/functional tests
* update `model_templates/python3_sklearn_runtime_params/model-metadata.yaml` template to include bool/numeric …

[AGENT-5214] Add support for numeric runtime parameters

---

DRCODEOWNERS

[RAPTOR-10198] set nbx team as DRCODEOWNERS for nbx envs

---

custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
custom_model_runner/datarobot_drum/custom_task_interfaces/user_secrets.py
custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
tests/unit/datarobot_drum/custom_task_interfaces/test_custom_task_interface.py
tests/unit/datarobot_drum/custom_task_interfaces/test_user_secrets.py
tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py

This adds functionality to scrub output from logging and printing.
```python
thing1: BasicSecret = self.secrets["ONE"]
thing2: GCPSecret = self.secrets["TWO"]
self.log_message(f"SELF.LOG_MESSAGE: {self.secrets}, {thing1.password}")
print(f"PRINT: {thing1.username}, {thing2.gcp_key.type}")
logger.error(f"CREATED LOGGER: {thing1.username}, {thing2.gcp_key.type}")
logging.error("ROOT LOGGER %s", thing1.password)
```
```
drum fit -cd ../mldev-scripts/custom-task-examples/binary/ --input ../mldev-scripts/custom-task-examples/test_data.csv --target readmitted --user-secrets-mount-path ~/dr_workspace/mldev-scripts/custom-task-examples/secrets/ --verbose --logging-level info --show-stacktrace
```
```
SELF.LOG_MESSAGE: {'ONE': BasicSecret(username='*****', password='*****', …
```

[MODEL-12834] CustomTasks Network Access: 5 - scrub outputs

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311_genai/dr_requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python39_genai/dr_requirements.txt
public_dropin_environments/python39_genai/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

This bumps the version of drum to push up changes to scrubbing secrets for user output
##
Tested on staging here: https://kibana-staging.infra.ent.datarobot.com/goto/876fdf5f8cd24d71926345f0db8ab196  by using a dev version and checking credentials

[MODEL-12854] CustomTasks Network Access: 5 - bump drum version to 1.10.17

---

custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters_schema.py
model_templates/python3_sklearn_runtime_params/model-metadata.yaml
tests/unit/datarobot_drum/runtime_parameters/test_runtime_parameters.py

Adding new field for runtime parameters, to specify that a field must be set before registration. This field `allowEmpty` is optional and set to `True` by default.
The check will be done in the app, before registering any custom model, the runtime params that has `allowEmpty=False` need to have a current value, either a default value or override.

[AGENT-5226] add new field to indicate if a runtime parameter is mandatory

---

DEFINE-INFERENCE-MODEL.md
custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/julia_predictor/julia_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
tests/unit/datarobot_drum/drum/test_data_marshalling.py
tests/unit/datarobot_drum/resource/test_drum_server_utils.py

Allow custom models to return DataFrames with additional columns beyond the predictions column.
The new functionality applies only for `server` and `score` modes.
The response JSON scheme is as follows:
```
{
“predictions”: [<as-of-today], 
“extra”: {
"columns": ["col1", "col2", ...],
"index": ["index1", "index2", ...],
"data": [[value11, value12, ...], [value21, value22, ...], ...]
}
}
```
NOTE: the response schema can be later changed very easily (It's a one-line change).
In the context of the time-series initiative for custom models (PRD), we identified the need to add support to return additional columns, beyond the predictions column, in a prediction response from a custom model. This support was identified by the GenAI and time series projects.

[RAPTOR-10206] Add support for extra columns in Python predictor and extend response format

---

custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
tests/unit/datarobot_drum/runtime_parameters/test_runtime_parameters.py

Check for duplicates runtime parameters definitions and values, allow only one occurrence of same field_name.
With this check we don't allow same filed_name with same type or different type.
In DataRobot repo we also have this check : https://github.com/datarobot/DataRobot/pull/125198

[RAPTOR-10233] check duplicate runtime parameters

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311_genai/dr_requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python39_genai/dr_requirements.txt
public_dropin_environments/python39_genai/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json

Release DRUM v1.10.16, and update envs. which includes:
* Support for numeric runtime parameters
* Support for allowEmpty field for runtime parameters
* Check for duplicate runtime parameters definitions

[AGENT-5216] release DRUM v1.10.18

---

docker/dropin_env_base_jdk_ubi/Dockerfile
docker/dropin_env_base_jdk_ubi/README.md
docker/dropin_env_base_jdk_ubi/build_image.sh
docker/dropin_env_base_jdk_ubi/requirements.txt
public_dropin_environments/python311_genai/Dockerfile
public_dropin_environments/python311_genai/env_info.json

* Fix setting `DATAROBOT_MLOPS_VERSION` env var
* Build and push new base image into docker hub
* Update affected env to use new image.
`DATAROBOT_MLOPS_VERSION` env var was not properly propagated into Dockerfile.
As result: 
```
ENV MLOPS_MONITORING_AGENT_JAR_PATH=$JARS_PATH/mlops-agent-${DATAROBOT_MLOPS_VERSION}.jar
```
was not set correctly.

[RAPTOR-10266] fix dropin-env-base-jdk:ubi8.8 envs base image

---

DEFINE-INFERENCE-MODEL.md
custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py

In the context of [allowing extra model output in a prediction's response project](https://datarobot.atlassian.net/browse/PBMP-6259) it was discussed that the best name would be 'extraModelOutput'. Following this decision, this PR is all about renames.

[RAPTOR-10263] Rename 'passthrough' to 'extra_model_output'

---

custom_model_runner/datarobot_drum/resource/predict_mixin.py
tests/unit/datarobot_drum/resource/test_predict_mixin.py

Lately we added support for extra model output in a prediction response. One of the changes included handling the response format. A new bug was introduced, which added redundant left curly brace `'{'`. 
This PR fixes the related error.

[RAPTOR-10283] Fix invalid prediction's response format

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
custom_model_runner/datarobot_drum/drum/utils/dataframe.py
tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
tests/unit/datarobot_drum/drum/utils/test_dataframe.py

In the context of adding support for extra model output it is also required to add such support for R lang models. The idea is that R model may return additional columns beyond the expected predictions. These additional columns will eventually be will returned in the prediction response under a new key: `extraModelOutput`.

[RAPTOR-10222] Add support for extra model output in R predictor

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
tests/functional/test_inference_per_framework.py
tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py

For text generation models, the target column name is provided via environment. In order to extract the extra additional columns, it is required to take it into account.

[RAPTOR-10323] Fix extra model extraction for text generation models

---

custom_model_runner/datarobot_drum/resource/deployment_config_helpers.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
tests/functional/test_deployment_config.py

In the context of the new support for extra model output project, the changes in this PR is about adding the extra model output serialization to the PPS (Portable Prediction Server) response.

[RAPTOR-10205] Add support for extra model output in PPS response

---

public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python311_notebook/requirements.txt
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt

0.3.6 version https://pypi.org/project/datarobot-model-metrics/
notebooks PR: https://github.com/datarobot/notebooks/pull/3141

[MMM-16119] bump dmm library to 0.3.6

---

public_dropin_notebook_environments/python311_notebook/dr_requirements.txt
public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python311_notebook/requirements.txt
public_dropin_notebook_environments/python311_notebook/setup-ssh.sh
public_dropin_notebook_environments/python38_snowflake_notebook/dr_requirements.txt
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python38_snowflake_notebook/setup-ssh.sh
public_dropin_notebook_environments/python39_notebook/dr_requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/setup-ssh.sh
public_dropin_notebook_environments/python39_notebook_gpu/dr_requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/setup-ssh.sh
public_dropin_notebook_environments/python39_notebook_gpu_tf/dr_requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/setup-ssh.sh
public_dropin_notebook_environments/r_notebook/env_info.json
public_dropin_notebook_environments/r_notebook/setup-ssh.sh

- The latest https://pypi.org/project/datarobot-drum/  is in the notebooks repo (it took care of a Pillow CVE) but not in the public drop-in Envs in this repo. yet
- Pinning the version `jupyter-client==7.4.9` helped us (NBX) lower the kernel startup time (also I moved where `ipykernel` is pinned just to match where it shows up in the NBX notebooks repo. for consistency)
- Updated the `setup-ssh.sh` script - this fixes an issue that arose with Env Vars that had either spaces in them or special characters like `'!'`

[NB-5277] [NB-5278] [NB-5279] Recent NBX updates to kernels

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py

It turns out that DataRobot backend adds redundant quotation marks to the target name, when it sets up the `TARGET_NAME` environment variable for the text-generation model. Consequently, if the user tries to set the output column hard-coded, without reading the `TARGET_NAME` from the environment, the extraction of the additional columns will fail. 
For instance if the user sets the target column in the UI to `response` and try to return a DataFrame with the response column name hard-coded from the `score` method in `custom.py`, than the whole prediction will fail, saying that there is no `"response"` column in the output. But if the user reads the target column from the environment variable `TARGET_NAME` everything will work as expected, because the value in this environment variable …

[RAPTOR-10333] Handle redundant quotation marks in target name when extracting extra model output

---

custom_model_runner/datarobot_drum/drum/args_parser.py
tests/functional/test_runtime_parameters.py

Add environment  variable support for `--runtime-params-file`.  The new env var `RUNTIME_PARAMS_FILE` will allow to provide the filename of file that contains the values for runtime params.
Now we can run:
```
RUNTIME_PARAMS_FILE=/tmp/runtime.yaml  drum score  --code-dir ./ --input ./dataset.csv
``` 
is equivalent to:
```
drum score --runtime-params-file /tmp/runtime.yaml  --code-dir ./  --input  ./dataset.csv
```
* Adding parametrize to test cases that involve runtime-params-file

[AGENT-5370] Add env var support for runtime-parameter-file

---

custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py

I'm working on harness pipelines implementation.
The test case that checks java gateway startup started to fail in harness. Looks like it happens due to the small timeout interval. Increasing it a bit for the test only - helped

[RAPTOR-10452] bump py4j gateway polling time

---

public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python311_notebook/requirements.txt
public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt

- 0.3.7 version https://pypi.org/project/datarobot-model-metrics/
- notebooks PR https://github.com/datarobot/notebooks/pull/3329

[MMMDATA-226] bump dmm library to 0.3.7

---

custom_model_runner/datarobot_drum/drum/exceptions.py
custom_model_runner/datarobot_drum/drum/model_metadata.py
tests/unit/datarobot_drum/model_metadata/test_model_metadata.py

Yaml with flow style is not allowed by StrictYaml,  https://hitchdev.com/strictyaml/why/flow-style-removed/. so providing something like is not allowed.
```
name: runtime-params-example
type: inference
targetType: regression
runtimeParameterDefinitions: []
```
This PR propagates the error so it can be visible from user running in custom models.

[RAPTOR-10347] Propagate error with strict yaml

---

public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python311_genai/requirements.txt
public_dropin_environments/python39_genai/env_info.json
public_dropin_environments/python39_genai/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/requirements-gpu.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements-gpu.txt

In buzok we use Rouge for calculating confidence scores, adding rouge-score missing library to Gen AI drop-in env

[BUZOK-2248] Add rouge to GenAI drop in env

---

public_custom_application_environments/python39_streamlit/env_info.json

Bump the environment version id, otherwise release build fails with "An environment version with the supplied ID already exists"

[APPLS-1980] Bump Custom App Env version id

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
docker/dropin_env_base_jdk_ubi/requirements.txt
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311_genai/dr_requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python39_genai/dr_requirements.txt
public_dropin_environments/python39_genai/env_info.json
public_dropin_environments/python3_keras/dr_requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/dr_requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/dr_requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/dr_requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/dr_requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/dr_requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/dr_requirements.txt
public_dropin_environments/r_lang/env_info.json
public_dropin_gpu_environments/triton_server/dr_requirements.txt

Bump version to 1.10.21
* add new env vars for runtime parameter file
* Bug fixes for disallowed model-metadata file.
* Adds support for `datarobot-mlops` 10.0+

[AGENT-5372] Bump version to 1.10.21

---

DRCODEOWNERS

Remove buzok from owners of GenAI environment
Buzok no longer depends on GenAI custom environment: we have migrated to use an execution envrionment defined in our repository.

[BUZOK-2294] Remove buzok from owners

---

custom_model_runner/datarobot_drum/drum/runtime.py

We don't log exception stacktrace when DRUM is running in server mode.  Instead we start error server with only exception message.
Thus, add stacktrace logging to DRUM.

[RAPTOR-10612] add log stacktrace when there is exception

---

custom_model_runner/Makefile
docker/drum_builder/Dockerfile
docker/drum_builder/README.md
docker/drum_builder/build_docker.sh
tools/image-build-utils.sh

Updated `drum-builder` image.
Installed pytest as I'm going to use this image for DRUM tests with java predictor.
This new image is already pushed into dockerhub
https://hub.docker.com/layers/datarobot/drum-builder/ubuntu-22-04/images/sha256-8c878e69da7357dac535e5cc67a2b23fb33ae76577b45e46946ff0bf515562cf?context=repo

[RAPTOR-10663] update drum-builder image

---

public_dropin_notebook_environments/python311_notebook/Dockerfile
public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python311_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook/Dockerfile
public_dropin_notebook_environments/python39_notebook/env_info.json
public_dropin_notebook_environments/python39_notebook/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_rapids/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
public_dropin_notebook_environments/r_notebook/Dockerfile
public_dropin_notebook_environments/r_notebook/env_info.json

Updated notebooks kernels:
* Added `gh` (GitHub CLI)
* Added  `boto3` and `sagemaker`  to python kernels (except deprecated python3.8)
* Update `datarobot==3.4.0` CC @asuslov

[NB-5720][NB-5238] Add dependencies to kernels

---

public_dropin_gpu_environments/nim_llm/start_server.sh
public_dropin_gpu_environments/vllm/env_info.json
public_dropin_gpu_environments/vllm/start_server.sh

- Remove bashisms from GPU env entrypoints
- Bump version of vllm env
In the vLLM env especially, `/bin/sh` is not linked to `bash` so we need to be sure to not have bashisms in there. I fixed up the other envs for posterity.

[AGENT-5469] Fix bashisms in GPU envs

---

public_dropin_gpu_environments/nim_llm/dr_requirements.txt
public_dropin_gpu_environments/triton_server/dr_requirements.txt
public_dropin_gpu_environments/vllm/dr_requirements.txt

Bump `requests==2.32.2`
Fix CVE CVE-2024-35195.
Superseeds #1041 and #1039

Bump requests 2.32.2 in GPU envs

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

Release drum 1.11.2 after `werkzeug` dependency update.
Note:
Due to how harness pipelines are written now, bumping DRUM version and pinning them in the `public-dropin-environments` can not be done in the same PR.

[RAPTOR-10834] release DRUM v1.11.2

---

custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
public_dropin_gpu_environments/vllm/Dockerfile
public_dropin_gpu_environments/vllm/env_info.json
public_dropin_gpu_environments/vllm/start_server.sh

- Pass gpu count to vLLM server
- Add `autoawq` library to vllm env
- Bump version of vllm env
- Allow setting `--model` param via engine config file
To run larger LLMs (e.g. 70b+ param) one needs to split the model across multiple GPUs. This adds automatically handling of that so if we detect multiple GPUs, we configure vLLM accordingly. I'm also adding the `autoawq` package as it is used for quantization which is related running large LLMs (on smaller GPUs with minimal degredation to quality). Finally, users may want to set CLI flags via config file instead of runtime params so only hard code the most core params.

[AGENT-5795] Update vLLM env for large LLMs

---

custom_model_runner/CHANGELOG.md
custom_model_runner/requirements.txt
public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/java_codegen/requirements.txt

I turned out that `datarobot-drum` is not compatible with `numpy>=2.0.0`. The latter was release on Jun-16, 2024. Ever since then, the https://ci1.devinfra.drdev.io/job/Custom_Models_drop_in_environment_tests/ started to fail.
It is required to restrict the numpy version to <2.0.0

[RAPTOR-10986] Set proper dependency for numpy in the runner and java-codegen env

---

docker/dropin_env_base/Dockerfile
docker/dropin_env_base_jdk/Dockerfile
docker/dropin_env_base_jdk_ubi/Dockerfile
docker/dropin_env_base_r/Dockerfile

Change `chmod` to be recursive and add `/var/log/nginx` to make sure that nginx can write to required paths when running as non-root user.
Nginx needs to be able to write to `/var/lib/nginx/temp` and `/var/log/nginx` but currently we only add write permissions for `/var/lib/nginx`. 
We want to be able to run nginx when DRUM is running in production mode.

[CODEGEN-1913] Fix nginx permissions

---

public_dropin_notebook_environments/python311_notebook_base/Dockerfile
public_dropin_notebook_environments/python311_notebook_base/env_info.json

Related NBX PR:
https://github.com/datarobot/notebooks/pull/3775
Red Hat removed older git version as well as patch version of python 3.11.x
Confirmed this base image works here:

[NB-6229] Update git & python patch version in base notebooks image

---

tests/functional/test_performance_check.py

I'm working on moving this repo harness test pipelines from DR infra to Harness Hosted Infra (HHI)
Eventually, running this group of tests on HHI is faster: https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/module/ci/orgs/Custom_Models/projects/datarobotusermodels/pipelines/test_functional_general_on_hhi/executions/H-92-ljjSGm0MAmioPlnwg/pipeline?step=fq7EcqFORVmTO_wnyOCzrQ&stage=c-pgBNvJRd-S3CkwfPMn-w&childStage=&stageExecId=
than on DR K8S
https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/all/orgs/Custom_Models/projects/datarobotusermodels/pipelines/test_functional_general/executions/eJhVaJ1VSyi1nPL7LdogBQ/pipeline?storeType=INLINE&stage=35r8Iim9TUOg9lMTj9lQog&step=qBqEYKMDTRq2ICNdrrVEfQ&childStage=&stageExecId=
This test case started to fail because it became too fast. I …

[RAPTOR-11069] change test to make it run a couple of seconds longer

---

public_dropin_environments/python39_streamlit/Dockerfile
public_dropin_environments/python39_streamlit/env_info.json

The default env was causing:
```
File "/usr/local/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/PIL/Image.py", line 68, in <module>
from ._typing import StrOrBytesPath, TypeGuard
File "/usr/local/Caskroom/miniconda/base/envs/py39/lib/python3.9/site-packages/PIL/_typing.py", line 10, in <module>
NumpyArray = npt.NDArray[Any]
AttributeError: module 'numpy.typing' has no attribute 'NDArray'
```
because we use numpy 1.20 in the apps streamlit env, and that's not compataible with pillow 10.4.0

[APP-2886] Pin pillow

---

custom_model_runner/datarobot_drum/drum/runtime.py

Clean up final exception logging a bit:
* printing exception type/message does't bring any value, just print traceback.
* remove senseless  "Looks like there is a problem." message and an instruction  to use --verbose.

[RAPTOR-11201] cleanup final exception logging

---

custom_model_runner/datarobot_drum/drum/gpu_predictors/nemo_predictor.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/triton_predictor.py
public_dropin_gpu_environments/nim_llm/dr_requirements.txt
public_dropin_gpu_environments/nim_llm/env_info.json
public_dropin_gpu_environments/triton_server/dr_requirements.txt
public_dropin_gpu_environments/triton_server/env_info.json
public_dropin_gpu_environments/vllm/dr_requirements.txt
public_dropin_gpu_environments/vllm/env_info.json

- Update health check in Nemo predictor to return 513 if NIM server has crashed
- Bump DRUM version to v1.11.5
- Release new envs
- Add notes to add short-circuit to Triton env
Returning a 513 after the NIM server has crashed allows us to fail-fast and return status back to the user.

Add short-circuit to NIM env

---

jenkins/test_drop_in_envs.sh
tests/e2e/test_drop_in_environments.py

Trying to debug this intermittent failure: 
https://ci1.devinfra.drdev.io/job/Custom_Models_drop_in_environment_tests/4716/
I feel that disk runs out of space as env's images were recently updated and grew a bit.
This test is used only by DTS.

[RAPTOR-11248] add disk usage printing in the e2e test

---

public_dropin_gpu_environments/vllm/Dockerfile
public_dropin_gpu_environments/vllm/env_info.json

See full list of changes with vLLM in their release log: https://github.com/vllm-project/vllm/releases
Notable changes for us are Llama 3.1 support and also support for vision language models (i.e. MiniCPM-V)
vLLM is rapidly evolving so we will want to bump our official env periodically for demoing.

[AGENT-6033] Bump vllm env to 0.5.4

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
custom_model_runner/datarobot_drum/drum/enum.py
tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py

Modify the DRUM code so that moderation library could wrap the `chat` interface of the DRUM
Also, added unit tests

[AGENT-6110] Moderation support for chat interface

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
tests/unit/datarobot_drum/drum/test_prediction_server.py

`model` and `completion_create_params` are switched around in some places.
* Fix parameter order
* Add comment about why chat route has trailing slash

[CODEGEN-1945] Fix chat wrong parameter order

---

custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py

- Don't set vLLM cach dir env vars in DRUM predictor
- Bump version to `v1.11.6`
It is easier to react to changes in vLLM by requiring the docker env to setup the cache dirs. In a follow-up PR those changes will be made after publishing this new version of the library.

[AGENT-5722] Don't set cache dirs in DRUM

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/setup.py

Update Py support to Py>=3.9
* LLM lazy loading support in DRUM  needs to use a package that depends on Py>=3.8.
* Newer versions of DRUM has never been tested and likely are not used in the older Py versions.
* Py3.7 is already end-of-life, Py3.8 is end-of-life on Oct 31, 2024.
Please share your opinion.

[RAPTOR-11378] update Py support to Py>=3.8, bump version to 1.12.0

---

public_dropin_notebook_environments/python311_notebook/requirements.txt

Update the notebook environment to include the latest published version of the [datarobot-model-metric](https://github.com/datarobot/datarobot-model-metrics) code.
The datarobot-model-metrics (`dmm` module) is the basis for calculating custom-metrics as delivered by the templates in the [datarobot-custom-templates](https://github.com/datarobot/datarobot-custom-templates) code. Without these changes, the custom-metric templates do not work in a notebook.
Need to determine if schedule custom-metrics jobs need a similar update. The datarobot-custom-templates repository has an execution environment which may be used for the execution of these jobs, so there may not be any changes necessary.

[MMMDATA-687] Update notebook execution environment to use latest DMM

---

requirements_test.txt

The issue doesn't affect tests in harness as conflicting requirements files are not installed together. 
But affect when developer installs them locally together.

[RAPTOR-11401] unpin datarobot dep in test

---

custom_model_runner/drum_server_api.yaml

Update OpenAPI spec to include chat API.
This is useful when developing client applications that run against DRUM.

[CODEGEN-1924] Add chat to OpenAPI spec

---

custom_model_runner/datarobot_drum/drum/main.py
tests/unit/datarobot_drum/drum/test_main.py

Try to use CUSTOM_MODEL_WOKERS runtime parameter even if it was set without using runtime_params_file.

[CODEGEN-1949] Use custom model workers with and without runtime_params_file

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py

If deployment id is not set, don't initialize mlops.
Running without monitoring is useful e.g. when testing or running locally.

[CODEGEN-1957] Make chat work without monitoring

---

custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/nim_predictor.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
model_templates/gpu_vllm_textgen/model-metadata.yaml
public_dropin_gpu_environments/nim_llm/README.md
public_dropin_gpu_environments/nim_llm/env_info.json
public_dropin_gpu_environments/triton_server/env_info.json
public_dropin_gpu_environments/vllm/Dockerfile
public_dropin_gpu_environments/vllm/README.md
public_dropin_gpu_environments/vllm/dr_requirements.txt
public_dropin_gpu_environments/vllm/env_info.json
tests/functional/run_integration_tests_in_framework_container.sh
tests/functional/test_inference_per_framework.py

- Bump vLLM to v0.6.2
- Bump DRUM v1.13.0b1
- Set vLLM cache dir override env vars in Dockerfile
- Stop install `autoawq`
The new vLLM supports more models and also has performance improvements. The new version of drum allows us to be more nible to vLLM change by allowing us to have more changes in the `Dockerfile` rather than needing to rely on DRUM code changes to support new vLLM versions. We have stopped installing `autoawq` because it wasn't compatible with the newest version of vLLM and also isn't needed for all cases.

[AGENT-6033 AGENT-6065] Bump version of vLLM env to v0.6.2

---

custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/nim_predictor.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
public_dropin_gpu_environments/nim_llm/README.md
public_dropin_gpu_environments/nim_llm/dr_requirements.txt
public_dropin_gpu_environments/vllm/README.md
public_dropin_gpu_environments/vllm/dr_requirements.txt

- Bump the version of DRUM to latest version in the vLLM and NIM environments.
- Add watchdog to restart OpenAI server if it crashes randomly
- Refactor some code into base class
- Add support for `engine_config.json` for NIM server to support full set of NIM configuration
- Removed `trust_remote_code` runtime param
Changes to the base OpenAI predictor code was made recently. Also, this makes the NIM and vLLM envs more robust by adding a watchdog thread that will restart random crashes of the underlying service. Without this, the server may crash/OOM but DRUM may stay up so the user would have no recourse other than to deactivate their Deployment to restart the server.

Add watchdog to GPU predictors

---

model_templates/gpu_nim_textgen/model-metadata.yaml
model_templates/gpu_vllm_textgen/engine_config.json
model_templates/gpu_vllm_textgen/model-metadata.yaml

- Remove concurrency param from example
- Set vLLM model via engine config
This makes some minor improvements to our examples. First it is better to set the vLLM model param via the config file because then it is versioned and can't be overriden at runtime with no auditing. Also don't showcase the concurrency flag yet as we haven't tested it extensively.

Minor improvements to GPU examples

---

custom_model_runner/README.md
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
custom_model_runner/datarobot_drum/resource/predict_mixin.py
custom_model_runner/drum_server_api.yaml
tests/functional/test_inference_per_framework.py
tests/unit/datarobot_drum/drum/gpu_predictors/test_gpu_predictors.py
tests/unit/datarobot_drum/drum/language_predictors/python_predictor/test_python_predictor.py
tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py
tests/unit/datarobot_drum/resource/test_predict_mixin.py

DRUM has a `/capabilities` endpoint that can currently be used to determine what kind of payload formats are supported by the model, i.e. CSV, arrow, etc.
This PR will extend this endpoint to include information about supported methods, for now the only method that is included is chat.
The endpoint will be used by the DataRobot app to expose if a deployment supports chat or not.
Make it possible for clients to find out if a custom model deployment supports chat api.

[CODEGEN-1950] Add supported methods to capabilities

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

Bump version and changelog.
Do a release before updating environments in #1146.

[RAPTOR-11574] Release DRUM 1.13.0

---

custom_model_runner/datarobot_drum/drum/enum.py
custom_model_runner/datarobot_drum/drum/lazy_loading/constants.py
custom_model_runner/datarobot_drum/drum/lazy_loading/schema.py
custom_model_runner/datarobot_drum/drum/model_metadata.py
custom_model_runner/requirements.txt
tests/unit/datarobot_drum/drum/lazy_loading/test_schema.py
tests/unit/datarobot_drum/model_metadata/test_model_metadata.py

In the context of the lazy loading custom model, it is required to add relevant data entities to hold the lazy loading data. These are derived from pydantic BaseModel, which facilitates the validation.

[RAPTOR-11320] Add schema for lazy loading custom model data

---

.gitignore
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/datarobot_drum/drum/lazy_loading/constants.py
custom_model_runner/datarobot_drum/drum/lazy_loading/exceptions.py
custom_model_runner/datarobot_drum/drum/lazy_loading/lazy_loading_handler.py
custom_model_runner/datarobot_drum/drum/lazy_loading/schema.py
custom_model_runner/requirements.txt
tests/functional/test_lazy_loading.py
tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
tests/integration/datarobot_drum/drum/lazy_loading/test_lazy_loading.py
tests/unit/datarobot_drum/drum/language_predictors/python_predictor/test_python_predictor.py

In the context of the lazy loading custom model support, it is required to process the related environment variable, if exists, and download the required files to the root folder of the executed custom model.
* Add a new method to the `BaseLanguagePredictor` to handle lazy loading files and call it from the `PythonPredictor` within the configuration phase.
* Add a new handler `LazyLoadingHandler` to deal with processing the lazy loading structured data JSON from an environment variable and use `datarobot_storage` to download the lazy loading files in parallel.
* Small improvement to the `credential_type` attribute definition in `S3Credentials`.
* Minor change to `.gitconfig`.
* Unit, integration and functional tests - note that the functional test requires special environment variables in …

[RAPTOR-11322] Add lazy loading processor to download the associated lazy loading remote files to the local volume

---

public_dropin_environments/python3_keras/requirements.txt

Cause by new `datarobot-storage` dep 
https://github.com/datarobot/datarobot-user-models/blob/5378ea0d42465b7f3f20702ca61e50ea4d2e367b/custom_model_runner/requirements.txt#L29
We don't actively support keras (and other) envs in terms of the latest framework version installed.
So bump versions to make tests pass.

[RAPTOR-11614] update keras env deps

---

docker/dropin_env_base_jdk_ubi/Dockerfile

Use updated java package for UBI image

[RAPTOR-11618] update java package in the base JDK ubi env

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py

* Pass association id to moderations.
* Don't fail request if reporting deployment stats fails.
We need to use the same association for custom metrics in moderations and when reporting chat predictions to be able to join them in deployment data quality table.

[CODEGEN-1974] Pass association id from chat to moderations

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

Release v1.14.1 of drum
Include fix for LLM envs.

[AGENT-6475] Bump new version of Drum

---

custom_model_runner/requirements.txt

Inspired by [this post](https://iscinumpy.dev/post/bound-version-constraints/), I included the `datarboto-storage` package without specifying version constraints.

[RAPTOR-11626] Unpin 'datarobot-storage' package

---

.harness/test_functional_by_framework.yaml
custom_model_runner/requirements.txt
public_dropin_environments/java_codegen/dr_requirements.txt
public_dropin_environments/python311_genai/requirements.txt
tests/functional/test_fit_per_framework.py

Kind of POC PR, let me know what you think.
* Unpin upper constraint for many DRUM deps based on the ticket request and https://github.com/datarobot/datarobot-user-models/pull/1173.
* Pin some of those deps in the env itself.
* Had to remove some deps pinning in python311_genai env.
1. In the Dockerfile for our env we consequently call pip install for `dr_reqirements.txt` and then for `requirements.txt`.
https://github.com/datarobot/datarobot-user-models/blob/master/public_dropin_environments/python311_genai/Dockerfile#L11-L17
This doesn't make sense as they may list conflicting package and it will never be enforced.
E.g. req1.txt: pkg==1.2.3; req2.txt: pkg==3.4.5. In the end, pkg from the file used the last will be installed.
I suggest to get rid of `dr_requirements` and use only …

[RAPTOR-11620] try to unpin DRUM dependencies

---

custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py

Catch exception if raised when trying to report that chat request failed.
We want to continue and return a meaningful response even if mlops fails.

[CODEGEN-1974] Don't fail request if mlops reporting fails

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/requirements.txt

Releasing "DRUM unchained".
* mainly removing dep package's upper constraints in this release.
@ahamino 
##i Rationale

[RAPTOR-11647] release v1.14.2

---

custom_model_runner/datarobot_drum/drum/args_parser.py
custom_model_runner/datarobot_drum/drum/enum.py
custom_model_runner/datarobot_drum/drum/lazy_loading/__init__.py
custom_model_runner/datarobot_drum/drum/lazy_loading/constants.py
custom_model_runner/datarobot_drum/drum/lazy_loading/lazy_loading_handler.py
custom_model_runner/datarobot_drum/drum/lazy_loading/schema.py
custom_model_runner/datarobot_drum/drum/main.py
tests/functional/test_fit_per_framework.py
tests/functional/test_lazy_loading.py
tests/unit/datarobot_drum/drum/lazy_loading/test_lazy_loading_handler.py
tests/unit/datarobot_drum/drum/lazy_loading/test_schema.py
tests/unit/datarobot_drum/drum/test_args_parser.py
tests/unit/datarobot_drum/drum/test_prediction_server.py

Implement the following:
- Add new lazy-loading command line option to get a lazy-loading file-path with proper lazy-loading content.
- The content should have 3 sections - “files”, “repositories” and “credentials”
- Setup proper environment variables based on the lazy-loading file content
* Unit tests
* Tested it locally by running a local custom model with drum tool

[RAPTOR-11705] Implement lazy-loading command line option and set environment variables accordingly

---

public_dropin_notebook_environments/python311_notebook/Dockerfile
public_dropin_notebook_environments/python311_notebook/env_info.json
public_dropin_notebook_environments/python311_notebook/requirements.txt
public_dropin_notebook_environments/python311_notebook/start_server.sh
public_dropin_notebook_environments/python311_notebook/start_server_drum.sh
public_dropin_notebook_environments/python311_notebook_base/Dockerfile
public_dropin_notebook_environments/python311_notebook_base/env_info.json
public_dropin_notebook_environments/python311_notebook_base/requirements.txt
public_dropin_notebook_environments/python311_notebook_base/start_server.sh
public_dropin_notebook_environments/python311_notebook_base/start_server_drum.sh
public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu/start_server.sh
public_dropin_notebook_environments/python39_notebook_gpu/start_server_drum.sh
public_dropin_notebook_environments/python39_notebook_gpu_rapids/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_rapids/start_server.sh
public_dropin_notebook_environments/python39_notebook_gpu_rapids/start_server_drum.sh
public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile
public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
public_dropin_notebook_environments/python39_notebook_gpu_tf/start_server.sh
public_dropin_notebook_environments/python39_notebook_gpu_tf/start_server_drum.sh

Make Notebook custom environments to be compatible with Custom Models

[CFX-590] [CFX-539] Make Notebook custom environments to be compatible with custom models

---

custom_model_runner/requirements.txt

Following the removal of `mlpiper` dependency by [PR1](https://github.com/datarobot/datarobot-user-models/pull/1200) & [PR2](https://github.com/datarobot/datarobot-user-models/pull/1200), it is now safe to have the `flask` depdendency without version or other constraints.
NOTE: it will not be merged but only after the two PRs mentioned above.

[RAPTOR-11798] Set the 'flask' dependency without specifying version constraints

---

custom_model_runner/setup.py

Currently, the `setup.py` includes a reference to the drum entry point from `custom_model_runner/bin/drum`. The issue is that the installation process alters the script's shebang to use the python interpreter instead of the original `#!/usr/bin/env python3`. This is typically controlled by `setuptools` or `distutils` during the package installation. The result is this shebang `#!python` , which is not properly interpreted under the virtual environment.
Solution: instead of using the `scripts` argument in `setup.py`, we better switched to the modern `entry_points` mechanism. This approach avoids shebang manipulation entirely.
We still need the original script, because it’s being used for testings and local development.

[RAPTOR-11818] Ensure DRUM package installation uses the Python interpreter from the virtual environment

---

.gitignore
custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
custom_model_runner/requirements.txt
harness_scripts/base_check/integration_tests_entrypoint.sh
harness_scripts/common/create_and_source_venv.sh
harness_scripts/common/update_python_to_meet_requirements.sh
harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
harness_scripts/functional_general/custom_java_predictor_entrypoint.sh
harness_scripts/functional_general/general_tests_entrypoint.sh
harness_scripts/functional_general/mlops_reporting_entrypoint.sh
public_dropin_environments/python3_sklearn/requirements.txt.bak
public_dropin_environments/r_lang/requirements.txt
tests/fixtures/unstructured_custom_mlops.py
tests/functional/test_mlops_monitoring.py
tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py

As of today, the `mlops-agent-9.2.8.jar` has a critical CVE. This JAR file is included and used by DRUM for mlops reporting. It is suggested to change the approach and avoid using the agent inside the custom model. Instead, use different MLOps APIs for reporting, which do not require the agent.
* Provide the URL and API token to the MLOps API spooler. 
* Set numpy requirement to `numpy<2.0` to comply with latest `pandas` in PyPI
* Set requirement for `datarobot-mlops>=10.2.0`
* Small fix when running DRUM inside a docker
* Add new harness script to check and update Python version to comply with requirements.
* Update mlops reporting functional test to comply with the new spooler change.
* Fix various tests and make some tests as well as harness scripts more robust

[RAPTOR-11809] Avoid using the mlops tracking agent to report statistics to DataRobot

---

custom_model_runner/datarobot_drum/drum/perf_testing.py
tests/unit/datarobot_drum/drum/test_perf_testing.py

Generating the output file for a sparse matrix when the prediction check fails does not work.  This fixes creating that file, and adds testing around it.

[MODEL-14740]Fix how sparse matrix is handled for comparison.

---

custom_model_runner/CHANGELOG.md

- Remove 'mlpiper' dependency and replace its functionality with comparable built-in implementations.
- Avoid using the mlops tracking agent to report statistics to DataRobot.
- Deprecate the '--production' mode and replace its functionality with Flask running in multi-process mode.
Previously, this mode relied on the Nginx and uWSGI servers, which have now been removed.
- Add support for GeoPoint target type.
- Internal improvements.

[RAPTOR-11810] Release v1.16.0

---

public_dropin_gpu_environments/nim_llm/env_info.json

Make it so the NIM container cannot be downloaded.
The upstream NIM container is behind a paywall so we should respect that and make our fork also not downloadable. In the future we would like to have the image gated entirely by a premium entitlement.

Mark NIM container as not downloadable

---

DRCODEOWNERS

As DXS and NBX are now one team, we moved all corresponding code owners to CFX.

[DSX-3771] Move NBX to CFX

---

custom_model_runner/datarobot_drum/drum/drum.py
tests/unit/datarobot_drum/drum/test_drum.py

When running DRUM with the 'docker' input option, it first checks whether the Docker image needs to be built. During this process, a Docker tag is generated based on the path where the Docker files reside. However, if the path starts or ends with an underscore (_), it results in an invalid Docker tag, as tags cannot have an underscore as the first or last character.
The solution is to remove any invalid underscores from the beginning or end of the tag name.

[RAPTOR-11857] Fix docker tag name when running DRUM with the docker option

---

public_dropin_environments/python3_sklearn/Dockerfile
tests/functional/test_mlops_monitoring.py

Implement a reliable method to programmatically inject lines into a Dockerfile during MLOps monitoring functional test. Instead of relaying on specific instructions inside the Dockerfile, use a dedicated comment for it.

[RAPTOR-11859] Implement a reliable way to inject lines into a Docker file during testing

---

harness_scripts/functional_general/general_tests_entrypoint.sh

In a local development environment, the user login to Docker Hub, manually, from the shell. It is not necessary to login from the test script itself.

[RAPTOR-11860] Improve Harness script to skip Docker login in local development

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

[RAPTOR-11867] release DRUM 1.16.1

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/requirements.txt
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python311_genai/requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_onnx/requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/requirements.txt

Release envs with drum 1.16.1
We haven't update envs since mlpiper removal 3 weeks ago.
It is time to do this.
I see there are several more PRs on the way, but let's test this for now.

[RAPTOR-11866] update environments to have DRUM 1.16.1

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py

If the training data is not available for the deployment, drift tracking is disabled and no point reporting monitoring data.
It is possible that training data is available but drift is disabled, but it is not possible to check drift for every request.  DRUM will receive an error code in that case.
Ensured existing tests are running successfully
Added test cases for chat interface
Added test cases for score interface too
We originally tried to implement it by looking at drift tracking settings https://github.com/datarobot/datarobot-user-models/pull/1219 but modified it to look at training data.
Tested manually on a TextGen model to ensure that monitoring calls are not made.

[AGENT-6667]  No monitoring if training data is not available

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/gpu_predictors/nim_predictor.py

Support both `start-server.sh` and `start_server.sh` startup scripts
It appears that in newer NIMs NVIDIA has renamed their start server script.

[AGENT-6684] Update NIM predictor for newer start server script

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/nim_predictor.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
public_dropin_gpu_environments/nim_llama_70b/env_info.json
public_dropin_gpu_environments/nim_llama_70b/requirements.txt
public_dropin_gpu_environments/nim_llama_8b/env_info.json
public_dropin_gpu_environments/nim_llama_8b/requirements.txt
public_dropin_gpu_environments/vllm/Dockerfile
public_dropin_gpu_environments/vllm/env_info.json
public_dropin_gpu_environments/vllm/requirements.txt
tests/functional/test_inference_per_framework.py

- Bump DRUM version v1.16.3
- Bump DRUM pin in vLLM and NIM env image builds
- Bump base image of vLLM to v0.6.6.post1
- Update watchdog thread logic to work in a forked HTTP worker model
- Update health check to not rely on thread state and look directly at OS process state of exec'd NIM or vLLM process.
To take advantage of the NIM and vLLM dynamic batching capabilities and saturate the GPU, we need to be able to support concurrent requests. DRUM was single threaded until the introduction of `CUSTOM_MODEL_WORKERS` runtime param (https://docs.datarobot.com/en/docs/release/archive-release-notes/v10.2/v10.2.0-mlops.html#custom-model-workers-runtime-parameter) but the implementation did not support GPU workers.

[AGENT-6675] Add support for CUSTOM_MODEL_WORKERS param in GPU predictors

---

harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
public_dropin_environments/python311_genai/Dockerfile
public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_onnx/requirements.txt
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_xgboost/Dockerfile

Update the Python drop-in environments with the base image that was created after these PRs: https://github.com/datarobot/datarobot-user-models/pull/1229,  https://github.com/datarobot/datarobot-user-models/pull/1235.
The new base image is: `datarobot/dropin-env-base:1.0.0-python-3.11.11-slim-bookworm`
It is an intermediate change that is part of the FedRamp compliance initiative.
Additionally, an improvement has been made to `harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh`, ensuring that the requirements.txt from the tested environment is copied to a temporary file, leaving the original file unmodified.

[RAPTOR-11835] Build the Python based drop-in environments from DR base python image

---

public_dropin_gpu_environments/python311_genai/requirements.txt

@elatt pointed out https://github.com/datarobot/datarobot-user-models/pull/1234#discussion_r1936372645 that GPU GenAI exec env is broken. This fixes the problem by unrestricting pydantic version, just as we did in non-GPU env. cc @mkavf

[BUZZOK-24833] Fix issue with pydantic

---

public_dropin_notebook_environments/python311_notebook_base/env_info.json
public_dropin_notebook_environments/python311_notebook_base/sshd_config
public_dropin_notebook_environments/python39_notebook_gpu/sshd_config
public_dropin_notebook_environments/python39_notebook_gpu_rapids/sshd_config
public_dropin_notebook_environments/python39_notebook_gpu_tf/sshd_config
public_dropin_notebook_environments/r_notebook/sshd_config

This reverts commit 9b3357f812462149694ea95af11194068b4c4e85.
Need to revert as I deployed to Prods. too early
This change works in Staging

Revert "[CFX-1527] Update base notebook image for FIPS compliance as well as others that are purely examples (#1255)"

---

public_fips_dropin_environments/python3_sklearn/Dockerfile

During Harness pipeline improvements to support the FIPS-compliant sklearn environment, additional tools were added to the environment. These tools were only required by the Harness functional tests pipeline. However, the Harness pipeline was already cleaned up and no longer require these tools.

[RAPTOR-11951] Remove non-required tools from the FIPS-compliant sklearn environment

---

.harness/env_image_publish.yaml

The default image tag value should be constructed from the drop-in environments folder and the drop-in environment name.

[RAPTOR-11954] Fix the default image tag in the environment build and publish Harness pipeline

---

public_dropin_notebook_environments/python311_notebook_base/env_info.json
public_dropin_notebook_environments/python311_notebook_base/sshd_config
public_dropin_notebook_environments/python39_notebook_gpu/sshd_config
public_dropin_notebook_environments/python39_notebook_gpu_rapids/sshd_config
public_dropin_notebook_environments/python39_notebook_gpu_tf/sshd_config
public_dropin_notebook_environments/r_notebook/sshd_config

A re-do of this PR:
https://github.com/datarobot/datarobot-user-models/pull/1255
Updating our base notebook drop-in Env. to work with recent changes we've made to be FIPS compliant
In order for our terminals feature to continue to work with FIPS compliant images in our NBX services this update is required

[CFX-1527] Update base notebook image for FIPS compliance as well as others that are purely examples

---

public_dropin_notebook_environments/README.md
public_dropin_notebook_environments/python311_notebook/README.md
public_dropin_notebook_environments/python311_notebook_base/README.md
public_dropin_notebook_environments/python39_notebook_gpu/README.md
public_dropin_notebook_environments/python39_notebook_gpu_rapids/README.md
public_dropin_notebook_environments/python39_notebook_gpu_tf/README.md
public_dropin_notebook_environments/r_notebook/README.md

Update Notebooks custom image templates README's for clarity/ease of copying command
Also misc. improvements.
Users can often get tripped up in the process of creating custom notebook environments so I tried to make sure all the relevant README's were up to date and correct.
- Top level README still references a 3.9 notebook image example we no longer have/support
- The main "base" image we actively support I added a link to the public docs.
- Each respective image README I made the terminal command more easily readable and copyable
- Each respective image README I made sure the reference to the DR UI was up to date with the correct wording
- For the R README I updated to reference the correct `setup-common.R`
**How the base image README now looks:**
([seen …

[CFX-1596] Update Notebooks custom image templates README's for clarity/ease of copying command

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py

Be sure to check for other CLI options that are aliases for the parallelism modes. Also add runtime param to switch default mode.
For quantized models, you can't use `-tp` and need to use `-pp` so it is good to provide this flexibility.

Cleanup vllm multi-gpu handling

---

custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py

This is almost the revert of https://github.com/datarobot/datarobot-user-models/pull/1224
The predictionInputs/fromJSON/ needs to accept monitoring data if either the feature drift is enabled or predictions data collections is enabled.  For Textgen models, although we don’t have training data and no feature / target drift, typically we enable the predictions data collections.  We could check in DRUM if the predictions data collection flag is set on the deployment or not before reporting monitoring data, but that check has to be made for each report request. That is not scalable. Hence, we need to let the decision of whether to accept monitoring data for processing or not to be taken at API controller level and remove the check of training data from DRUM.
In the context of IR-747, we do …

[AGENT-6734] Revert the check of training data available

---

.harness/java_codegen_image_build_default_pr_input.yaml
.harness/python311_genai_image_build_default_pr_input.yaml
.harness/python3_keras_image_build_default_pr_input.yaml
.harness/python3_onnx_image_build_default_pr_input.yaml
.harness/python3_pmml_image_build_default_pr_input.yaml
.harness/python3_pytorch_image_build_default_pr_input.yaml
.harness/python3_sklearn_image_build_default_pr_input.yaml
.harness/python3_xgboost_image_build_default_pr_input.yaml
.harness/r_lang_image_build_default_pr_input.yaml

The 'latest' tag for drop-in environments was recently changed to include the related environment's root folder.  
To accommodate this change, the input-set in the Harness pipeline that builds these images needs to be updated accordingly.

[RAPTOR-11992] Fix Harness input sets for creating latest drop-in environments

---

.harness/fips_python311_genai_default_pr_input.yaml
.harness/fips_python311_genai_image_build_default_pr_input.yaml

As part of of the FedRAMP initiative, and following the addition of the FIPS-compliant Python3.11 GenAI drop-in environment, it is required to add related Harness resources to support the functional tests.

[RAPTOR-11991] Add Harness resources for GenAI FIPS-compliant drop-in environment

---

.harness/fips_python311_image_build_default_pr_input.yaml
.harness/fips_python3_keras_image_build_default_pr_input.yaml
.harness/fips_python3_onnx_image_build_default_pr_input.yaml
.harness/fips_python3_pytorch_image_build_default_pr_input.yaml
.harness/fips_python3_sklearn_image_build_default_pr_input.yaml
.harness/fips_python3_xgboost_image_build_default_pr_input.yaml

Whenever a change is introduce to a drop-in environment in a PR, upon merging  to master the given drop-in environment is being built and pushed as the latest image for that environment. Then, this latest image is being used by functional tests. 
In this PR new Harness input-set resources are added for the missing FIPS-compliant drop-in environments.
As part of this PR, new triggers will be created in Harness to use the related input-sets in order to build the images.

[RAPTOR-11993] Add missing Harness input-sets for creating latest FIPS-compliant drop-in environments

---

custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py

For chat api, the prompt could be in the form of list.  Make sure to serialize it before reporting for monitoring

[AGENT-6788] Prompt could be in the form of list

---

tests/e2e/test_drop_in_environments.py

Fix an invalid maximum memory setup in the FIPS-compliant keras drop-in environment function test.
This will fix the following error:
```
Maximum memory value ("786432000") must be higher than the desired memory value (2147483648)
```

[RAPTOR-12010] Fix the memory configuration in FIPS-compliant keras drop-in env functional test

---

public_fips_dropin_environments/python311/env_info.json

All FIPS-compliant drop-in environment names in `env_info.json` follow the pattern `[DataRobot] [FIPS-compliant] ...`. To maintain consistency, the FIPS-compliant python311 drop-in environment name should follow the same pattern.

[RAPTOR-12011] Rename experimental to DataRobot in the FIPS-compliant python311 name

---

public_dropin_environments_sandbox/.harness/publish_to_docker.yaml
public_dropin_environments_sandbox/.harness/publish_to_docker_python3_keras.yaml

Create Harness pipeline to build and push images to Docker Hub repositories.
These images will be tagged based on the target branch, current DR release version, and environment version ID.
Verified using the sandbox environment. 
- pipeline run: https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/all/orgs/Custom_Models/projects/datarobotusermodels/pipelines/publish_to_docker/executions/LyznpyYESNKhuqok3UuqrA/pipeline?connectorRef=account.svc_harness_git1&repoName=datarobot-user-models&branch=nolanm%2Fpublish-to-docker-pipeline&storeType=REMOTE
- image in DockerHub:
https://hub.docker.com/repository/docker/datarobotdev/env-python3-keras-sandbox/general

create publish to docker pipeline

---

public_dropin_nim_environments/nim_sidecar/env_info.json

Bump env info file because this was missed in #1294 
Needed to build new env and push it out to MTS

Bump nim_sidecar env version

---

tests/e2e/test_drop_in_environments.py

I see line in question was added here https://github.com/datarobot/datarobot-user-models/pull/1307/files#diff-99121e5effb6196d38161f1c5c12a2703fcf6ebf0abb133525fc29c2a6d46700R264-R265
But I don't see the reason.
Started test on this branch: https://ci1.devinfra.drdev.io/job/Custom_Models_drop_in_environment_tests/6107/

[RAPTOR-12052] Fix the memory in R drop-in env functional test

---

.harness/java_codegen_publish_to_docker_pr_input.yaml
.harness/java_codegen_trivy_scan_pr_input.yaml

Java-codegen InputSets for publish_to_docker and trivy_scan pipelines.
Enable these pipelines for the Java-codegen environment.
Successful pipeline run: https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/all/orgs/Custom_Models/projects/datarobotusermodels/pipelines/publish_to_docker/executions/ASlVmufnQs-YUS-HVMoh_Q/pipeline?connectorRef=account.svc_harness_git1&repoName=datarobot-user-models&branch=nolanm%2Ftest-java-codegen&storeType=REMOTE&step=iMyhDv1jQeuKE6X9v9OGJg&stage=fI8jzy6PRa-ezGk7hScZAA&childStage=&stageExecId=

java codegen publish_to_docker and trivy_scan

---

.harness/python3_pmml_publish_to_docker_pr_input.yaml
.harness/python3_pmml_trivy_scan_pr_input.yaml

Python3 pmml InputSets for publish_to_docker and trivy_scan pipelines.
Enable these pipelines for the python-pmml environment.
https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/all/orgs/Custom_Models/projects/datarobotusermodels/pipelines/publish_to_docker/executions/9OEnZ_GqRZe0LopsylfdmA/pipeline?connectorRef=account.svc_harness_git1&repoName=datarobot-user-models&branch=nolan/python-pmml-test&storeType=REMOTE

python3_pmml input sets for publish_to_docker and trivy_scan

---

.harness/python3_sklearn_publish_to_docker_pr_input.yaml
.harness/python3_sklearn_trivy_scan_pr_input.yaml

Python3 sklearn InputSets for publish_to_docker and trivy_scan pipelines.
Enable these pipelines for the python-sklearn environment.
https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/all/orgs/Custom_Models/projects/datarobotusermodels/pipelines/publish_to_docker/executions/vxhKRPsMSKCiLJ7fDp74aw/pipeline?connectorRef=account.svc_harness_git1&repoName=datarobot-user-models&branch=nolan/python-sklearn-test&storeType=REMOTE

python3_sklearn input sets for publish_to_docker and trivy_scan

---

.harness/python3_xgboost_publish_to_docker_pr_input.yaml
.harness/python3_xgboost_trivy_scan_pr_input.yaml

Python3 xgboost InputSets for publish_to_docker and trivy_scan pipelines.
Enable these pipelines for the python-xgboost environment.
https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/all/orgs/Custom_Models/projects/datarobotusermodels/pipelines/publish_to_docker/executions/oMbjs-rQRneKHiIU7BzNKg/pipeline?connectorRef=account.svc_harness_git1&repoName=datarobot-user-models&branch=nolan/python-xgboost-test&storeType=REMOTE

python3_xgboost input sets for publish_to_docker and trivy_scan

---

.harness/python3_pytorch_publish_to_docker_pr_input.yaml
.harness/python3_pytorch_trivy_scan_pr_input.yaml

Python3 pytorch InputSets for publish_to_docker and trivy_scan pipelines.
Enable these pipelines for the python-pytorch environment.
https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/all/orgs/Custom_Models/projects/datarobotusermodels/pipelines/publish_to_docker/executions/gzYWqtkgR066NdqZVhPcwA/pipeline?connectorRef=account.svc_harness_git1&repoName=datarobot-user-models&branch=nolan/python-pytorch-test&storeType=REMOTE

python3_pytorch input sets for publish_to_docker and trivy_scan

---

.harness/r_lang_publish_to_docker_pr_input.yaml
.harness/r_lang_trivy_scan_pr_input.yaml

R lang InputSets for publish_to_docker and trivy_scan pipelines.
Enable these pipelines for the r-lang environment.
https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/all/orgs/Custom_Models/projects/datarobotusermodels/pipelines/publish_to_docker/executions/sg-W1FsJTnOSIxsAI8fZ1w/pipeline?connectorRef=account.svc_harness_git1&repoName=datarobot-user-models&branch=nolan/r-lang-test&storeType=REMOTE

r_lang input sets for publish_to_docker and trivy_scan

---

.harness/python311_genai_publish_to_docker_pr_input.yaml
.harness/python311_genai_trivy_scan_pr_input.yaml

Python311 genai InputSets for publish_to_docker and trivy_scan pipelines.
Enable these pipelines for the python-genai environment.
Successful pipeline run: https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/all/orgs/Custom_Models/projects/datarobotusermodels/pipelines/publish_to_docker/executions/ZLeGNO9URnimM88VgwOQqw/pipeline?connectorRef=account.svc_harness_git1&repoName=datarobot-user-models&branch=nolan/python-genai-test&storeType=REMOTE

python311_genai input sets for publish_to_docker and trivy_scan

---

.harness/python3_onnx_publish_to_docker_pr_input.yaml
.harness/python3_onnx_trivy_scan_pr_input.yaml

Python3 onnx InputSets for publish_to_docker and trivy_scan pipelines.
Enable these pipelines for the python-onnx environment.
Successful pipeline run: https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/all/orgs/Custom_Models/projects/datarobotusermodels/pipelines/publish_to_docker/executions/htS26_DgR8KOJOH-MZ1Atw/pipeline?connectorRef=account.svc_harness_git1&repoName=datarobot-user-models&branch=nolan/python-onnx-test&storeType=REMOTE

python3 onnx input sets for publish_to_docker and trivy_scan

---

.harness/python3_keras_publish_to_docker_pr_input.yaml
.harness/python3_keras_trivy_scan_pr_input.yaml

Python3 keras InputSets for publish_to_docker and trivy_scan pipelines.
Enable these pipelines for the python-keras environment.
Successful pipeline run: https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/all/orgs/Custom_Models/projects/datarobotusermodels/pipelines/publish_to_docker/executions/xGR4lC3mTIijssLupkYCPQ/pipeline?connectorRef=account.svc_harness_git1&repoName=datarobot-user-models&branch=nolanm/python-keras-test&storeType=REMOTE

python3 keras publish_to_docker and trivy_scan

---

.harness/java_codegen_publish_to_docker_pr_input.yaml
.harness/python311_genai_publish_to_docker_pr_input.yaml
.harness/python3_keras_publish_to_docker_pr_input.yaml
.harness/python3_onnx_publish_to_docker_pr_input.yaml
.harness/python3_pmml_publish_to_docker_pr_input.yaml
.harness/python3_pytorch_publish_to_docker_pr_input.yaml
.harness/python3_sklearn_publish_to_docker_pr_input.yaml
.harness/python3_xgboost_publish_to_docker_pr_input.yaml
.harness/r_lang_publish_to_docker_pr_input.yaml

Get the target_branch for each publish_to_docker InputSet from the Trigger.
This will allow us to trigger publish_to_docker whenever changes are merged to a specific branch.

update target_branch of publish_to_docker Input Sets

---

tools/env_version_update.py

Add the `--env` argument to `env_version_update.py` script.
This argument allows running the script for a single environment.

add environment argument to env_version_update.py script

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/env_info.json

The primary reason for updating the environment versions is to enable their reinstallation on staging. This is necessary because we upgraded the installer to correctly set up descriptions that display the requirements for each environment.

[RAPTOR-12072] Update environment versions to enable proper dependencies display in the description

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
public_dropin_nim_environments/nim_sidecar/requirements.txt
tests/functional/run_integration_tests_in_framework_container.sh
tests/functional/test_inference_gpu_predictors.py

We should not hardcode model names when DRUM runs as a sidecar, along with the OpenAI Server (NIM Container).
Model name should be read either:
- user sends model name in request (applicable to /v1/chat/completions)
- from NIM_SERVED_MODEL_NAME runtime parameter, if we have `model-metadata.yaml` in the custom model templates;
- from OpenAI server endpoint `/v1/models/`, which is a standard endpoint, only if the `datarobot-deployed-llm` model name is sent in the request.
NOTE: model name is only required for LLM models. 
We don't have harness pipelines for GPU functional tests, so I run tests on EC2 instance with GPUs:
```
export NGC_API_KEY=<LOOK FOR NGC_API_KEY IN 1PASSWORD>
cd ~/workspace/datarobot-user-models/
bash jenkins/test_functional_per_framework.sh nim_sidecar
[gw0] [ 95%] …
```

AGENT-6925 Do not hardcode model name in DRUM

---

public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/java_codegen/Dockerfile.local
public_dropin_environments/python311/Dockerfile
public_dropin_environments/python311/Dockerfile.local
public_dropin_environments/python311_genai/Dockerfile
public_dropin_environments/python311_genai/Dockerfile.local
public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_keras/Dockerfile.local
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_onnx/Dockerfile.local
public_dropin_environments/python3_pmml/Dockerfile
public_dropin_environments/python3_pmml/Dockerfile.local
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_pytorch/Dockerfile.local
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_sklearn/Dockerfile.local
public_dropin_environments/python3_xgboost/Dockerfile
public_dropin_environments/python3_xgboost/Dockerfile.local
public_dropin_environments/r_lang/Dockerfile
public_dropin_environments/r_lang/Dockerfile.local

Currently, the `start_server.sh` starts as a child process of `/bin/sh`, meaning:
- The shell /bin/sh remains in memory.
- Signals (e.g., SIGTERM, SIGINT) may not reach start_server.sh properly.
It is desired to replace the parent shell process, using the `exec`, which means:
- The parent shell will not stay in memory.
- The start_server.sh and later drum becomes PID 1 inside the container.
- Signals (e.g., SIGTERM, SIGINT) will be handled properly.

[RAPTOR-12084] Use 'exec' in Dockerfile ENTRYPOINT for better signal handling and efficiency

---

custom_model_runner/CHANGELOG.md
public_dropin_nim_environments/nim_sidecar/env_info.json
public_dropin_nim_environments/nim_sidecar/requirements.txt

Bump DRUM version to 1.16.10
We need this change https://github.com/datarobot/datarobot-user-models/pull/1353/files , so UI will show correct Prediction code snippets.

AGENT-6954 Bump drum to 1.16.10

---

public_dropin_nim_environments/nim_sidecar/Dockerfile
public_dropin_nim_environments/nim_sidecar/env_info.json
tests/functional/test_inference_gpu_predictors.py

Set MAX_WORKERS to 10 via env var set in Dockerfile.
This instance of DRUM is primarily an HTTP proxy and we have found 10 HTTP works to be a good default for good performance with NIMs. This method also allows users to still override this default with a runtime param.

[AGENT-7023] Default to 10 HTTP workers for nim sidecar container

---

custom_model_runner/datarobot_drum/drum/root_predictors/drum_server_utils.py
tests/functional/test_inference_gpu_predictors.py

Set DRUM port to 8080 during GPU functinoal tests to make them more accurate.
We didn't detect an issue with a NIM running on a conflicting port as DRUM until we tried to launch the model in Staging. This is an attempt to give us an earlier signal on if we are missing an env var to make sure NIM servers don't run on DRUM port.

[AGENT-6982] More accurate NIM functional tests

---

public_dropin_nim_environments/nim_sidecar/Dockerfile
public_dropin_nim_environments/nim_sidecar/env_info.json
tests/functional/test_inference_gpu_predictors.py

Second try to backport https://github.com/datarobot/datarobot-user-models/pull/1361

[11.0] [AGENT-7023] Default to 10 HTTP workers for nim sidecar container

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
public_dropin_gpu_environments/vllm/Dockerfile
public_dropin_gpu_environments/vllm/env_info.json
public_dropin_gpu_environments/vllm/requirements.txt
tests/functional/test_inference_gpu_predictors.py

- Prepare release of 1.16.11 DRUM
- Prepare new vLLM env to use new DRUM version
- Add testcase for `extra_body` handling
- Update logic in default `chat()` hook to correctly pass `extra_body` args to the underlying OpenAI server (e.g. vLLM)
With the old code, users would have to nest `extra_body` args to have them correctly passed to vLLM server. This change makes DRUM more transparent and makes the user feel as though they are communicating directly with the underlying OpenAI server.

[AGENT-6674] Add support for extra_body argument in vLLM

---

harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
public_dropin_gpu_environments/vllm/Dockerfile
public_dropin_gpu_environments/vllm/env_info.json

Bump vLLM env to use vllm v 0.8.3.
+ additional changes in tests:
**NOTE: tests don't perform any functional check as we don't have GPUs available. Only new image is build to check buildability and DRUM install.**
Functional testing should be done manually.

[RAPTOR-12253] bump vllm env v0.8.3

---

public_dropin_environments/r_lang/Dockerfile
public_dropin_environments/r_lang/env_info.json

When we create a FIPS-complaint image, we want to have as small number of libs and tools as possible.
So we only copy required libraries/tools into the  resulting image.
In this case **libzstd** is added. Probably some new dependency requires it. 
Likely there will be more as time goes by.

[RAPTOR-12318] copy missing library into R env image

---

custom_model_runner/datarobot_drum/drum/model_metadata.py
tests/unit/datarobot_drum/model_metadata/test_model_metadata_hyperparameters.py

This PR is a companion to: https://github.com/datarobot/DataRobot/pull/143873  and will not merge until after that one.
The original limit seems to have been arbitrary, and we got a request for longer limits, so i'm making it 1024 len. 
some context on where to find advanced tuning code is here: https://datarobot.atlassian.net/wiki/spaces/MODEL/pages/1989771284/Advanced+Tuning+Parameters
searching in DR code you should grep for advanced_tuning

[MODEL-18996] update custom task select param to allow longer strings

---

custom_model_runner/datarobot_drum/drum/drum.py

A couple small changes to make working with docker images a little more understandable. 
When trying to verify the `drum` version, provide a smaller error message. For containers without `sh` access, it was not possible to get the version. So, just print a smaller INFO message about not being able to get the version.
Make the code more readable by splitting the version check into own function (`_check_docker_drum_version()`). 
Here's an example of a run using a container that does NOT have `sh` installed:
```terminal
datarobot-user-models % drum score --logging-level all --language python --target-type vectordatabase --deployment-id 680fcc706dcc9b6cad3ac521 --model-id 680fcc1f1bd0bd8ef07bc4b1 --code-dir adam/vector_database_assets/embedding_model --input prompt_predictions.csv --verbose …
```

[MMM-19318] Improve drum runner error messages when working with containers

---

tools/create-drum-dev-image.sh
tools/image-build-utils.sh

Allow specifying the moderations wheel file in `create-drum-dev-image.sh`. 
For some DRUM developers, we want to use a container with the moderations library included. This allows the user to specify the moderations wheel file, and the `Dockerfile` and `requirements.txt` will get updated automatically.

[MMM-19199] Allow building with moderations library 

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py

This consumes the changes in https://github.com/datarobot/moderations/pull/295 that make interfacing with the moderations library easier.
Use object-oriented `ModerationsPipeline` that has `score()` and `chat()` functions instead of tracking a different pipeline class and functions separately. This should make maintenance of the moderations library easier, particularly after we can remove the interfaces to the old moderations libraries.
Much of the change in the testing was due to issues encountered during test. The "last local module" was still in memory, so it was causing problems in other tests. The context is done so that the files are removed and the "local module" is unloaded following the test execution -- this is done to avoid bleeding that content between tests.

[MMM-19325] Use new object-oriented moderations pipeline

---

tools/image-build-utils.sh

The test builtin can't take multiple options in a single call, so this yields a syntax error. Additionally, `-n` (is set) and `-z` (is not set) presents a fun logic issue. :)
The intent appears to be to check if the related variable is set before proceeding, so this removes the `z` from `-nz` to accomplish that.

[RAPTOR-12446] Fix invalid test -nz

---

custom_model_runner/CHANGELOG.md

My recent change (#1393) added "list LLM models" hook support, but that was not included in the changelog. This 1-liner PR fixes that.
It’s rare to backdate a change, but we’ve done this before at the patch level (1.11.2 with 1.11.3) (#1045)
Developers and users can determine when "models" support was added without having to use git tools.
29 April: update to 1.16.13
24 April: update to 1.16.12 (#1395)  # I'll add change notice to this version
23 April: add "models" hook support (#1393)

[RAPTOR-12432] update changelog for list models

---

.harness/reconcile_dependencies_for_all_envs_based_on_parent_folder.yaml
tools/env_version_update.py
tools/reconcile_dependencies.sh

Add a new pipeline based on older reconciliation and env version id update pipelines.
Improvements are:
* this pipeline has only one trigger for the parent envs folder. Currently it is configured to run on only one: `public_dropin_environments` 
* When there are changes in any env, pipeline is triggered. Script goes over all the `CHANGED` `public_dropin_environments` subfolders, runs `pip-compile` to generate requirements, then updates environment version id and commits changes into PR.
Then all the tests are automatically retriggered.
Here is an example of running this pipeline: https://github.com/datarobot/datarobot-user-models/pull/1414/files
Later I'll expand functionality on all the environments folders

[RAPTOR-12416] add new reconciliation pipeline

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/server.py
tests/unit/datarobot_drum/drum/test_logger.py
tests/unit/datarobot_drum/drum/test_prediction_server.py

Added `request_id` to all log messages from DRUM containers. That is going to be one of the key attributes in the log format.
For DRUM API server the `request_id` is fetched from `X-Request-ID` header and propagated to API requests handlers.
In the followup PR I'm going to add inject the `request_id` into all outgoing API calls as well.
Provided that a custom model receives a request ID, print the request ID once for each request. Without this, it's very hard to understand if the request actually landed on the model.

[RAPTOR-12334] Tracking X-Request-id in API requests to DRUM server

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
custom_model_runner/datarobot_drum/drum/common.py
custom_model_runner/datarobot_drum/drum/main.py
custom_model_runner/datarobot_drum/drum/root_predictors/prediction_server.py
custom_model_runner/requirements.txt

Add OpenTelemetry support for drum internal server.
* Feature is disabled by default.
* All incomming requests are instrumented, if context is present subsequent trace is attached.
* Added dependency on opentelemetry libraries.
* Related changed for pred server https://github.com/datarobot/DataRobot/pull/144237

[MMM-19334] Add support for OTEL.

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

[RAPTOR-12492] unbump DRUM version back to 1.16.13 as it has not been released yet

---

custom_model_runner/datarobot_drum/drum/description.py
custom_model_runner/datarobot_drum/drum/root_predictors/drum_server_utils.py
custom_model_runner/datarobot_drum/drum/root_predictors/utils.py
tests/unit/datarobot_drum/drum/root_predictors/test_drum_server_utils.py

This adds a new functionality to the `DrumRunServer` that allows it to "stream the output to the terminal" instead of waiting for the execution to complete and then displaying the entire set of logic.
**Why would I want this?**
We need to use the `DrumRunServer` to execute `custom-models` for development of Agentic workflows. Agents can become confused during the process and the process can appear to hang for an extended period of time. Because of the complex nature of `custom-models` we would like to be able to run them within the context of a drum server. Due to the way codespaces and other environments work with `scripts/` based execution we **MUST** execute all of this logic from within the context of a `python` program.
The problem here is that we then have a `synchronous` call being …

[BUZZOK-25745] Add support for streaming drum server run outputs

---

DRCODEOWNERS

As Scoring Code team was moved to Deploy pod I am removing codege from owners

Removes codegen from owners

---

public_dropin_notebook_environments/python311_notebook_base/Dockerfile

Bump to PYTHON_EXACT_VERSION=3.11.11

[CFX-2759] Bump to PYTHON_EXACT_VERSION=3.11.11

---

public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_keras/env_info.json

Missed one env in the prev PR https://github.com/datarobot/datarobot-user-models/pull/1440

[RAPTOR-12536] add more required tools into envs 2

---

public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311/Dockerfile
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311_genai/Dockerfile
public_dropin_environments/python311_genai/env_info.json
public_dropin_environments/python311_genai_agents/env_info.json
public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/Dockerfile
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/Dockerfile
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/Dockerfile
public_dropin_environments/r_lang/env_info.json
public_dropin_environments_sandbox/fips_python3_keras/Dockerfile
public_dropin_environments_sandbox/fips_python3_keras/env_info.json
public_dropin_nim_environments/nim_sidecar/Dockerfile
public_dropin_nim_environments/nim_sidecar/env_info.json

Add `busybox` binary to ChainGuard based images
Many of the _standard_ binaries are copying into the final images are actually just symlinks to `busybox`. Docker appears to follow the symlink during the `COPY` operation but it seems this isn't part of the OCI spec and `Kaniko` doesn't always do this so it is safest to just also have the `busybox` binary in there too.

[RAPTOR-12536] Add busybox to the ChainGuard drop-in envs

---

custom_model_runner/datarobot_drum/drum/root_predictors/predict_mixin.py
tests/unit/datarobot_drum/drum/test_prediction_server.py

Update error message logic so that when `chat` is missing for agentic workflow models, the returning message say not implemented, instead of unsupported

[MMM-19441] Missing chat hook error message for agentic workflow

---

custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py

Association id is automatically generated in DRUM, but user does not get access to it.  Return the association id back to the user

[RAPTOR-12673] Return association id with chat API response

---

custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py

So that moderation_config.yaml can be located in the model_dir.
Corresponding moderation PR: https://github.com/datarobot/moderations/pull/321

[RAPTOR-12660] Pass model_dir to moderation library

---

custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py

When Text Gen deployment is created, the feature drift and predictions data collections are off by default.  When /chat/completions request is received DRUM will report monitoring data using API Spooler and will fail with 422 - creating big stack trace. If, by default both flags are off, particularly for this use case of DRUM + chat completions, DRUM shouldn’t be this verbose.
This patch will put the warning - but not the stack trace
Manually tested it to ensure warning is printed but not the stack trace.

[RAPTOR-12427] Less verbose 422 when reporting monitoring data from chat completions

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

New version to capture minor improvements in chat API and agentic metrics

[RAPTOR-12695] Bump DRUM Version

---

.harness/test_functional_general.yaml
harness_scripts/functional_general/general_tests_entrypoint.sh
harness_scripts/functional_general/mlops_reporting_entrypoint.sh
public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311/Dockerfile
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311_genai_agents/Dockerfile
public_dropin_environments/python311_genai_agents/env_info.json
public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/Dockerfile
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/Dockerfile
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/Dockerfile
public_dropin_environments/r_lang/env_info.json

[cherry-pick] Migrate opensource envs to chainguard (#1526)

---

public_dropin_gpu_environments/vllm/env_info.json
public_dropin_gpu_environments/vllm/requirements.txt

Fixes:
https://datarobot.atlassian.net/browse/RAPTOR-14113
Update DRUM in vLLM env.
I already updated in 11.1 and forgot in master :)

[RAPTOR-14113] bump drum in VLLM env to 1.16.20

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/java_codegen/requirements.txt
public_dropin_environments/python311/env_info.json
public_dropin_environments/python311/requirements.txt
public_dropin_environments/python311_genai_agents/env_info.json
public_dropin_environments/python311_genai_agents/requirements.txt
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_keras/requirements.txt
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_onnx/requirements.txt
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pmml/requirements.txt
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_pytorch/requirements.txt
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_sklearn/requirements.txt
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/python3_xgboost/requirements.txt
public_dropin_environments/r_lang/env_info.json
public_dropin_environments/r_lang/requirements.txt

Pillow dependency for DRUM is unpinned but we have the pin in execution environments.
For CVE-2025-48379 we have to use Pillow version 11.3.0
Also I bumped version of `requests` to solve CVE-2024-47081 and urllib3 for CVE-2025-50181  and CVE-2025-50182 .
All that CVEs are affecting release 11.1

[VUL-14360][VUL-9146][VUL-11518][VUL-11519] Fixing CVE-2025-48379, CVE-2024-47081, CVE-2025-50181 and CVE-2025-50182

---

.harness/reusable_build_images.yaml

Make stage node name unique by adding matrix iteration number so it will be shown as 
Though stage name is unique even without iteration number, it seems that it is trimmed for github PR status, so:
`image_build_env_python_1234` 
and 
`image_build_env_python_1234.local`
will be smth like `image_build_env_python`, so only one status is shown in PR.
I'll change pipeline name later.

[RAPTOR-14178] improve harness images build pipeline

---

public_dropin_environments/python311_genai_agents/Dockerfile
public_dropin_environments/python311_genai_agents/Dockerfile.local
public_dropin_environments/python311_genai_agents/env_info.json

There is an outdated `asyncio` package (https://pypi.org/project/asyncio/) being installed as part of `datarobot-moderations`. This package is unnecessary in python > 3.4 and it also breaks compatibility with a bunch of other packages. We need to ensure this package is not installed. I will open a parallel PR to remove this from moderations, but we need to have a fix faster then that turnaround for these environments.
⚠️ **Including this package is a critical failure as a codespace GUI cannot be started if this package is present.**
RELEASE 11.1 BACKPORT: https://github.com/datarobot/datarobot-user-models/pull/1575

[BUZZOK-26787] Force remove outdated asyncio package from container, it breaks codespaces

---

public_dropin_environments/python311_genai_agents/Dockerfile
public_dropin_environments/python311_genai_agents/Dockerfile.local
public_dropin_environments/python311_genai_agents/env_info.json

There is an outdated `asyncio` package (https://pypi.org/project/asyncio/) being installed as part of `datarobot-moderations`. This package is unnecessary in python > 3.4 and it also breaks compatibility with a bunch of other packages. We need to ensure this package is not installed. I will open a parallel PR to remove this from moderations, but we need to have a fix faster then that turnaround for these environments.
⚠️ **Including this package is a critical failure as a codespace GUI cannot be started if this package is present.**

[cherry-pick] [BUZZOK-26787] Force remove outdated asyncio package from container, it breaks codespaces

---

.harness/test_functional_by_framework_multisteps.yaml

It looks like, that statuses are automatically reported to github if "Clone database" is set to True for a stage:
otherwise it should be reported manually using github API, and by specifying commit sha.
The problem with our test/reconciliation pipeline is that at some point we push reconciliation commit, so PR is refreshed and statuses are lost. So I need to push statuses manually with API.
Anyhow, I updated reconciliation stage template to automatically push status. (Template is not in github, so changes are not reflected), but pipeline now uses template v2, and screenshot attached.
If reconciliation succeeds, this status will go away but we'll see image build statuses
If reconciliation fails, we'll see error status.

[RAPTOR-14205] update pipeline to a new reconcile template version to show status in PR

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311/env_info.json
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pmml/env_info.json
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/env_info.json

Note that this bumps all version ids in public drop environments to trigger rebuild, pulling in the latest base image, as the old one had CVE-2025-6069.
This impacts the following list of tickets:
* RAPTOR-14179
* RAPTOR-14180
* RAPTOR-14181
* RAPTOR-14182
* RAPTOR-14183
* RAPTOR-14199
* RAPTOR-14184
* RAPTOR-14185
* RAPTOR-14186
* RAPTOR-14187
* RAPTOR-14188
* RAPTOR-14189
* RAPTOR-14190
* RAPTOR-14191
* RAPTOR-14192
* RAPTOR-14200
* RAPTOR-14193
* RAPTOR-14194
* RAPTOR-14195

[RAPTOR-14179] Bump env ver ids for CVE-2025-6069

---

public_dropin_environments/python311_genai_agents/Dockerfile
public_dropin_environments/python311_genai_agents/Dockerfile.local
public_dropin_environments/python311_genai_agents/env_info.json

nemoguardrails use annoy library which is mostly in C++ with python bindings. On EKS clusters, running nemoguard in playground and prod results in "Invalid opcode (core dumped)". This is because while installation of the annoy library, it is compiled using gcc and the compiled .so has some optimized instructions which become invalid on EKS - leading to core dumped
With exporting compilation flags specifically for annoy lib, we make sure that the binary .so is compatible with x86_64 and works on all regression environments
Tested this change for EKS cluster to ensure that nemo guard works and on AKS cluster to ensure that it is not introducing regression

[cherry-pick][RAPTOR-14202] Fix annoylib compilation

---

public_dropin_environments/python311_genai_agents/Dockerfile
public_dropin_environments/python311_genai_agents/Dockerfile.local
public_dropin_environments/python311_genai_agents/env_info.json

nemoguardrails use annoy library which is mostly in C++ with python bindings. On EKS clusters, running nemoguard in playground and prod results in "Invalid opcode (core dumped)". This is because while installation of the annoy library, it is compiled using gcc and the compiled .so has some optimized instructions which become invalid on EKS - leading to core dumped
With exporting compilation flags specifically for annoy lib, we make sure that the binary .so is compatible with x86_64 and works on all regression environments
Tested this change for EKS cluster to ensure that nemo guard works and on AKS cluster to ensure that it is not introducing regression

[RAPTOR-14202] Fix annoylib compilation

---

public_dropin_apps_environments/python312_apps/Dockerfile
public_dropin_apps_environments/python312_apps/env_info.json

Dockerfiles owned by the Applications team got HIGH+ CVEs.
Use SDTK-provided base images for safer builds, along with updates to system packages that expose vulnerabilities.
Complements https://github.com/datarobot/datarobot-custom-templates/pull/379

[APP-4435] Fix CVEs in Apps Dockefiles

---

public_dropin_environments/python311_genai_agents/env_info.json

This will trigger a rebuild. The fixes are already available upstream, and as we do not pin binutils, this will resolve CVE-2025-1153 and CVE-2025-3198.

[RAPTOR-14304] Bump python311_genai_agents to fix CVEs

---

.harness/scripts/bump_env_info.sh

This adds a script which can be called to automatically version bump specified execution environments, add them to a new git branch, push, and create a PR. This will help more smoothly deal with CVEs.
Note that this script:
* bumps version id for all the relevant envs
* git add
* git new branch
* git push
* gh cli create pull request

[RAPTOR-14365] Automate env_info version bumps

---

tests/e2e/conftest.py

https://ci1.devinfra.drdev.io/job/Custom_Models_drop_in_environment_tests/
Tests run with these changes:
https://ci1.devinfra.drdev.io/job/Custom_Models_drop_in_environment_tests/7029/
These E2E tests are a bit obsolete.
Overall these tests are in Jenkins because here we run every env with DR. We can not spin up local DR in harness and we still haven't implemented E2E tests for every env in the SLA way.,
The intention of these tests is to make sure that our environments in the datarobot-user-models repo are buildable and functional at any given moment. So they build drum(from master), put it into context for every env, create this env in DR, create model and run predictions.
As we recently introduced CI into the DRUM repo, now after every PR that changes environment we publish updated …

[RAPTOR-14360] change tests to use env image published to datarobot dockerhub

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

Release new version that has OTL metrics and logs preconfigured.

[MMM-20322] Bump DRUM version.

---

public_dropin_environments/python3_pytorch/env_info.json

This will trigger a rebuild to pull in a more up-to-date version of pytorch, which will resolve CVE CVE-2025-3730.

[RAPTOR-13851] Bump pytorch to rebuild

---

custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
custom_model_runner/datarobot_drum/drum/root_predictors/prediction_server.py
tests/unit/datarobot_drum/drum/test_prediction_server.py

This PR introduces three new timeout settings: DRUM_OPENAI_CLIENT_TIMEOUT , DRUM_CLIENT_REQUEST_TIMEOUT and NIM_DIRECT_ACCESS_REQUEST_TIMEOUT. These settings are intended to prevent server freezing issues that occur when the internet connection is lost on the sync server.
Importance:
By adding these timeouts, the server can fail gracefully instead of hanging indefinitely due to network disruptions, improving system reliability and responsiveness.

[RAPTOR-14353] add client and NIM timeouts

---

custom_model_runner/CHANGELOG.md
custom_model_runner/datarobot_drum/drum/description.py

Added support for launching the web server externally via CLI (gunicorn app:app).

[RAPTOR-14353] Bump DRUM version

---

public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311/env_info.json
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/env_info.json

I installed public environments on Staging in a new way by providing image URI which points to the image in `datarobotdev` 
Eventually, IBS on Staging can no pull images from `datarobotdev`, so I need to reinstall environments in the old way and find a solution.
Bump env version IDs to be able to reinstall environments from provided image.

[RAPTOR-14653] bump env version IDs to reinstall

---

public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/java_codegen/Dockerfile.local
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311/Dockerfile
public_dropin_environments/python311/Dockerfile.local
public_dropin_environments/python311/env_info.json
public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_keras/Dockerfile.local
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_onnx/Dockerfile.local
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_pytorch/Dockerfile.local
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_sklearn/Dockerfile.local
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/Dockerfile
public_dropin_environments/python3_xgboost/Dockerfile.local
public_dropin_environments/python3_xgboost/env_info.json

This is for all relevant public dropin environments. This drops the pip install and update that happens, preferring to rely on the system site packages and system pip. This is currently to address CVE-2025-8869, which upstream pip has fixed but has not released yet, and its release date is undetermined at this time.
Chainguard however has fixed this in their images, so pip installing from pypi is re-introducing the vulnerability into our images. Relying on system site packages, especially for pip, allows us to use the fixes from Chainguard without re-introducing them.

[RAPTOR-14742] PDIE: All without pip

---

public_dropin_environments/java_codegen/Dockerfile
public_dropin_environments/java_codegen/env_info.json
public_dropin_environments/python311/Dockerfile
public_dropin_environments/python311/env_info.json
public_dropin_environments/python3_keras/Dockerfile
public_dropin_environments/python3_keras/env_info.json
public_dropin_environments/python3_onnx/Dockerfile
public_dropin_environments/python3_onnx/env_info.json
public_dropin_environments/python3_pytorch/Dockerfile
public_dropin_environments/python3_pytorch/env_info.json
public_dropin_environments/python3_sklearn/Dockerfile
public_dropin_environments/python3_sklearn/env_info.json
public_dropin_environments/python3_xgboost/Dockerfile
public_dropin_environments/python3_xgboost/env_info.json
public_dropin_environments/r_lang/Dockerfile
public_dropin_environments/r_lang/env_info.json
public_dropin_gpu_environments/vllm/Dockerfile
public_dropin_gpu_environments/vllm/env_info.json
tests/functional/test_drum_server_failures.py

When a user's custom.py script contained an unhandled exception (e.g., during module import or model loading), the DRUM model testing process would not fail immediately. Instead, the job would hang for approximately one hour before finally reporting the failure. 
The root cause of the delayed failure was an internal "Error Server" component. 
This change deactivates the "Error Server" mechanism during the model testing phase. With this component disabled, any unhandled exception in custom.py causes the main DRUM process to exit quickly with a non-zero exit code.
The fix was validated by running DRUM model tests against several custom.py files with intentionally injected exceptions, including ValueError on import and errors within the hooks. In all test cases, the DRUM job failed quickly. …

[RAPTOR-14658] disable error server in execution environments

---

custom_model_runner/datarobot_drum/drum/drum.py
custom_model_runner/datarobot_drum/drum/exceptions.py
custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
custom_model_runner/datarobot_drum/drum/main.py

This pull request introduces "fast fail" mechanism to the DRUM runner when failing to parse a configuration file.
The implementation includes:
- A new UnrecoverableError exception hierarchy to signal fatal errors. This is implemented for better maintenance.
- This change introduces a global `threading.excepthook` in `drum.py` to act as a final safety net. The hook catches any unhandled exception from any thread, logs a critical error with a full traceback, and immediately terminates the process with a non-zero exit code.
- A new try-except block for loading config-file and wrapping exception.
Closes: [RAPTOR-14422]
A model could fail to initialize correctly due to a simple typo in a config file, but the DRUM server would continue running. Users would only discover the problem after the …

[RAPTOR-14422] Drum fast fail when config file has issues

---

public_dropin_environments/python311_genai_agents/env_info.json

Need to reinstall this env in the old way to have image in the ECR registry

[RAPTOR-14807] bump agents env version ID

---

public_dropin_environments/python311_genai_agents/Dockerfile
public_dropin_environments/python311_genai_agents/Dockerfile.local

This drops the uv pip install, preferring to rely on the system installed pip and uv.  This is currently to address CVE-2025-8869, which upstream pip has fixed but has not released yet, and its release date is undetermined at this time.
Chainguard however has fixed this in their images, so pip installing from pypi is re-introducing the vulnerability into our images. Relying on system pip allows us to use the fixes from Chainguard.

[BUZZOK-27808] PDIE Genai agents: Use system pip
